### ISSUE TITLE
[BUG]: TMP Input Fields do not recongize caps lock or num lock

### ISSUE THREAD

**Issue by ComeOnAndSam** [Unity-Technologies/UnityRenderStreaming#1005]
### Package version

3.1.0-exp.7

### Environment

```markdown
* OS: Windows 11
* Unity version: 2022.3.19f1
* Graphics API: URP
* Browser: Microsoft Edge & Firefox
```

### Steps To Reproduce

Remote into Unity via render streaming on browser, select a TMP Input Field, hit the CapsLock or NumLock button, and type text.

### Current Behavior

When render streaming into Unity and typing into a TMP Input Field, CapsLock and NumLock are not respected. Even if they're on, or even pressed during the stream, text will remain in lower case unless Shift is held, and numpad numbers can be typed.

### Expected Behavior

When CapsLock and/or NumLock is on, Input Field text should be in uppercase and keys pressed on the keypad should not be input.

**Comment by SamJTeleqo** [comment]
Some users receive this error when pressing caps lock in the stream, though it doesn't appear for everyone 

```
CapsLock has no appropriate reverse map!
UnityEngine.Debug:LogWarning (object)
InputFieldBridge:<Awake>b__4_0 (UnityEngine.InputSystem.LowLevel.InputEventPtr) (at Assets/0_scripts/Utils/InputFieldBridge.cs:176)
UnityEngine.InputSystem.LowLevel.NativeInputRuntime/<>c__DisplayClass7_0:<set_onUpdate>b__0 (UnityEngineInternal.Input.NativeInputUpdateType,UnityEngineInternal.Input.NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate (UnityEngineInternal.Input.NativeInputUpdateType,intptr)
```

**Comment by ComeOnAndSam** [comment]
Some users receive this error when pressing CapsLock in stream, though it doesn't appear for everyone

```
CapsLock has no appropriate reverse map!
UnityEngine.Debug:LogWarning (object)
InputFieldBridge:<Awake>b__4_0 (UnityEngine.InputSystem.LowLevel.InputEventPtr) (at Assets/0_scripts/Utils/InputFieldBridge.cs:176)
UnityEngine.InputSystem.LowLevel.NativeInputRuntime/<>c__DisplayClass7_0:<set_onUpdate>b__0 (UnityEngineInternal.Input.NativeInputUpdateType,UnityEngineInternal.Input.NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate (UnityEngineInternal.Input.NativeInputUpdateType,intptr)
```
