### ISSUE TITLE
[BUG]: Setting up in cloud server, remote web browser can't display video

### ISSUE THREAD

**Issue by Heroizme** [Unity-Technologies/UnityRenderStreaming#1013]
### Package version

3.1.0-exp.7

### Environment

```markdown
* OS:Windows 10
* Unity version: 2022.3.49f1
* Graphics API:DirectX11
* Browser:Edge 130.0.2849.80
```

### Steps To Reproduce

The project contains only official examples

### Current Behavior

Local access is normal, and browsers on the cloud server can access it normally, but browsers outside the cloud server show a black screen.

**Comment by ubuyaolan** [comment]
不要运行inputplayer.html这个页面，这个页面没有没有配置iceserver。你可以试试其他页面，同时你要部署coturn服务并且配置
