### ISSUE TITLE
Is it possible to support a short cut button to reset camera position?

### ISSUE THREAD

**Issue by Nemo-G** [Unity-Technologies/UnityRenderStreaming#138]
In windows OS, very frequently the camera will be positioned in a strange angle upon connected. And it would be very hard to reset the position. It would be good if a button for reset camera being implemented.

**Comment by karasusan** [comment]
You are right.
It would be better we assign keyboard to reset the position.

**Comment by karasusan** [comment]
@Nemo-G 
I will fix that `ResetCamera` method change from `private` to `public`.
Is it okay? Do you have any other requests?

**Comment by sindharta** [comment]
Closing due to non-activity.
