### ISSUE TITLE
Is it possible/are there plans for stereo streaming (eg. AR remote rendering)

### ISSUE THREAD

**Issue by Volcore** [Unity-Technologies/UnityRenderStreaming#152]
Hi,

thanks for this great plugin!

We'd like to stream AR from a high performance edge server to a headset to enable super-high detailed rendering at interactive framerates in AR. Is this something that's on the roadmap, or would it be feasible to adjust the source code of the plugin ourselves to do this?

**Comment by karasusan** [comment]
We have a next version plan to implement the multi-stream, but we require browsers on the receiving side. At the moment, we don't have native iOS/Android support on the roadmap yet.

**Comment by Volcore** [comment]
https://github.com/microsoft/MixedReality-WebRTC

**Comment by Volcore** [comment]
Sorry, wrong button while I was writing. It should be possible to use https://github.com/microsoft/MixedReality-WebRTC or similar tech to play back the WebRTC streams inside of Unity itself, right?

**Comment by sindharta** [comment]
Correct. Technically, it should be possible.

**Comment by sumnerICS** [comment]
@Volcore @sindharta @karasusan - I see this issue was removed from 2.0.0 milestone recently.
I equally am interested in streaming from a HQ renderer to headsets.
Using a multi-stream out and MS/WebRTC for playback on the headsets seems viable.
So, can we setup stereo streaming?  How about 360-deg sphere rendering and clients look anywhere?
Thx for any info

**Comment by mahadevans87** [comment]
@karasusan I would be interested in this feature as well. We cannot really afford Azure Remote rendering at the moment and would love to have an on premise solution for AR Remote Rendering with this library.

**Comment by rooi** [comment]
@karasusan would be very interesting indeed. Connecting this to https://github.com/microsoft/MixedReality-WebRTC would be great! Should be just replacing the signaler right?

**Comment by FeldNico** [comment]
Do you guys have any new information about stereo streaming? I want to try this with the HL2 in my next project, but have no prior knowledge about WebRTC.

**Comment by karasusan** [comment]
Hi, does anyone want to discuss about this issue? I would like to close non-active ticket.
I guess there is a solution that combining textures for two eyes.

**Comment by kannan-xiao4** [comment]
This ticket is non-active, so I close.
If you have any question, please re-open issue.
