### ISSUE TITLE
Can this toolkit support native OpenGL desktop applications?

### ISSUE THREAD

**Issue by ofer-sin** [Unity-Technologies/UnityRenderStreaming#156]

**Comment by karasusan** [comment]
Currently, This software hasn't support OpenGL API.
We have a plan that Linux support (contains OpenGL support) will start on version 2.1.

**Comment by karasusan** [comment]
This PR contains OpenGL support (on LInux only)
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/206
