### ISSUE TITLE
Cannot open Webapp.exe on PC win10pro

### ISSUE THREAD

**Issue by Henrilux** [Unity-Technologies/UnityRenderStreaming#157]
Unity project is running fine however after downloading the Webapp.exe file, i couldnt open it.

see attached screenshot if helps.

![d065f5bd948bca2b7e5017d1dc7ddb0](https://user-images.githubusercontent.com/43144582/65768561-dd296400-e163-11e9-8d2c-3df8ae9c7efc.png)
![3b78457297ec86666121473605f9a60](https://user-images.githubusercontent.com/43144582/65768563-ddc1fa80-e163-11e9-86d4-0a12521f5e0a.png)
![8529f756123644d4a18557e02a29d5c](https://user-images.githubusercontent.com/43144582/65768564-ddc1fa80-e163-11e9-9eb6-679e9a1c4463.png)

**Comment by sindharta** [comment]
Can you please translate the error message into English ?
Also, what is the size of the downloaded WebApp.exe ?

**Comment by Henrilux** [comment]
Hi


The error message says “ this app cannot be run on your computer. If you want to find out which version suits your computer please ask developer.



I will find out size of the WebApp.exe shortly



发自我的iPhone


------------------ Original ------------------

**Comment by sindharta** [comment]
https://github.com/Unity-Technologies/UnityRenderStreaming/releases/download/1.1.1-preview/webserver.exe

This has been reported here as well #160 
So closing this issue as a duplicate.

**Comment by Henrilux** [comment]
hi

i downloaded the latest webserver.exe and opened in latest Chrome version with firewall turned off.
but the web page does not sync with Unity. 

i got error message in Unity here.

and a short snapshoot on what happened when i tried to stream. see attached mp4 video file





henry@winttin.com
 
From: Sindharta Tanuwijaya
Date: 2019-10-09 09:51
To: Unity-Technologies/UnityRenderStreaming
CC: Henrilux; Author
Subject: Re: [Unity-Technologies/UnityRenderStreaming] Cannot open Webapp.exe on PC win10pro (#157)
https://github.com/Unity-Technologies/UnityRenderStreaming/releases/download/1.1.1-preview/webserver.exe
This has been reported here as well #160
So closing this issue as a duplicate.

**Comment by Henrilux** [comment]
hi

i downloaded the latest webserver.exe and opened in latest Chrome version with firewall turned off.
but the web page does not sync with Unity. 

i got error message in Unity here.

and a short snapshoot on what happened when i tried to stream.





henry@winttin.com
 
From: Sindharta Tanuwijaya
Date: 2019-10-09 09:51
To: Unity-Technologies/UnityRenderStreaming
CC: Henrilux; Author
Subject: Re: [Unity-Technologies/UnityRenderStreaming] Cannot open Webapp.exe on PC win10pro (#157)
https://github.com/Unity-Technologies/UnityRenderStreaming/releases/download/1.1.1-preview/webserver.exe
This has been reported here as well #160
So closing this issue as a duplicate.

**Comment by sindharta** [comment]
@Henrilux I can't see the snapshot and the error log.

**Comment by Henrilux** [comment]
hi

re attached. can see now?



henry@winttin.com
 
From: Sindharta Tanuwijaya
Date: 2019-10-09 11:37
To: Unity-Technologies/UnityRenderStreaming
CC: Henrilux; Mention
Subject: Re: [Unity-Technologies/UnityRenderStreaming] Cannot open Webapp.exe on PC win10pro (#157)
@Henrilux I can't see the snapshot and the error log.

**Comment by sindharta** [comment]
Hm, unfortunately no. Very weird.

Since this is a different error than the title of this issue anyway, can you open a new issue ?

**Comment by Henrilux** [comment]
hi Sindharta

just posted please help!!



henry@winttin.com
 
From: Sindharta Tanuwijaya
Date: 2019-10-09 11:43
To: Unity-Technologies/UnityRenderStreaming
CC: Henrilux; Mention
Subject: Re: [Unity-Technologies/UnityRenderStreaming] Cannot open Webapp.exe on PC win10pro (#157)
Hm, unfortunately no. Very weird.
Since this is a different error than the title of this issue anyway, can you open a new issue ?
