### ISSUE TITLE
webserver.exe dowloaded as 0 bytes in size

### ISSUE THREAD

**Issue by ajeshyohan** [Unity-Technologies/UnityRenderStreaming#160]
While trying to download webserver.exe from edit->render streaming->Download webapp it downloads webserver.exe with 0 bytes in size
![webserver](https://user-images.githubusercontent.com/53516970/66022158-aa3bf300-e50a-11e9-9d22-cde21ce94f46.PNG)

**Comment by sindharta** [comment]
Is there any error log inside Unity Editor ?

**Comment by yosun** [comment]
no error 
can't seem to find that exe in the current repo 
also the documentation in edit > render streaming > sub menu are all broked

**Comment by ajeshyohan** [comment]
> Is there any error log inside Unity Editor ?

Not showing any error.

**Comment by sam598** [comment]
You can download the webserver.exe here:
https://github.com/Unity-Technologies/UnityRenderStreaming/releases

The documentation assumes that the file was downloaded with the project. This file should be included with the repo, or the documentation should say that the file can be downloaded under the releases page.

There should not be a button in Unity for downloading a file from GitHub. This is a very strange and unorthodox approach, and is prone to broken links as we can all currently see.

**Comment by sindharta** [comment]
@yosun That's interesting. Can you send a screenshot of the broken menus ?

**Comment by sindharta** [comment]
@sam598 Thanks for your feedback. 
The intention of that button is to make it easier for users to download the file from Github by one click. We will fix it if the link is broken.

You are right though, that we should also mention in the documentation that the webserver can be downloaded under the releases page.

**Comment by sam598** [comment]
@sindharta For me the menus link to a 404 github page.

I get the intention was convenience, but IMO it's an odd thing to put in the editor, as these github links are easily broken and are specific to the demo scene, not to what developers will actually be using the plugin for.

**Comment by sindharta** [comment]
webserver.exe is not specific to the demo scene.
Unless developers want to customize something internally, it should be something that can be used out of the box for frequent use cases.

We'll add a test to make sure this isn't happening in the future.

**Comment by sindharta** [comment]
@sam598  webserver.exe is not specific to the demo scene.
Unless developers want to customize something internally, it should be something that can be used out of the box for frequent use cases.

We'll add a test to make sure this isn't happening in the future.
