### ISSUE TITLE
Small typo in doc

### ISSUE THREAD

**Issue by hisaos** [Unity-Technologies/UnityRenderStreaming#161]
in L.93 of [Documentation~/en/https.md](https://github.com/Unity-Technologies/UnityRenderStreaming/blob/release/1.1.3/Packages/com.unity.template.renderstreaming/Documentation~/en/https.md) , we have "business unity" but it should be "business unit".

**Comment by hisaos** [comment]
found 3 more typos in the same file - opened a PR with a branch named fixes/https-md-typos

**Comment by sindharta** [comment]
Done.
