### ISSUE TITLE
UnauthorizedAccessException when importing the sample

### ISSUE THREAD

**Issue by tarabishy2020** [Unity-Technologies/UnityRenderStreaming#164]
On unity 2019.1.14f1, installed the package from the package manager, the input system dialog box appeared, clicked yes, now am stuck on the import unity package window, with an endless loop of "preparing package: decompressing" and an error "unauthorizedAccessException: Access to the path ...\RenderStreamingHDRPSettings.json is denied"

**Comment by sindharta** [comment]
We'll try to improve our error handling in the next version.
Do you always encounter this error everytime when starting a new project ?

**Comment by tarabishy2020** [comment]
@sindharta If I press import sample from the package manager, it gets stuck on “decompressing package”. If I close unity from the task manager, restart again, it gets stuck again. When installing the package I noticed the json file is set to “read only”. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sindharta** [comment]
@tarabishy2020 It's strange that you have it set as read-only.
Does it happen to you again if you create a new project ?
Also, what happens if you change the permission manually ?

We'll try to fix this problem by changing the permission of the file, if it is read only (assuming that the user account has the authority to do it)

**Comment by tarabishy2020** [comment]
@sindharta  Yes, it did work before when I changed the permission manually. 
Just checked now again with a new project and it is the same. 
All files actually in this directory ..\Samples\Unity Render Streaming\1.1.1-preview\HDRP\Editor are created with Read-only permission.

**Comment by sindharta** [comment]
Thank you, I am filing this as a bug.

**Comment by karasusan** [comment]
This issue is fixed https://github.com/Unity-Technologies/UnityRenderStreaming/tree/release/1.1.3 branch which releases soon.
