### ISSUE TITLE
Unity Editor does not connect to HTTPS WebServer.exe

### ISSUE THREAD

**Issue by sam598** [Unity-Technologies/UnityRenderStreaming#173]
I followed this guide to set up HTTPS certificates to run the demo on Safari on iOS:

https://github.com/Unity-Technologies/UnityRenderStreaming/blob/b17d351696643a04bc59cefc4189117e10584b5b/Packages/com.unity.template.renderstreaming/Documentation~/en/https.md

The Webserver starts and I am able to connect to the web app on iOS on port 443.

However in the editor this error appears:

```
Network Error: Cannot connect to destination host
UnityEngine.Debug:LogError(Object)
Unity.RenderStreaming.<Start>d__15:MoveNext() (at Assets/Scripts/RenderStreaming.cs:87)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

The iOS app never starts streaming.

**Comment by sindharta** [comment]
You need to set the URL signaling property of the RenderStreaming component to https as well.
Have you done this step ?

![image](https://user-images.githubusercontent.com/7379311/66532758-8ea89c00-eb4b-11e9-8447-7d3f9b14ffb6.png)

**Comment by sam598** [comment]
I do not see this step in the documentation.

**Comment by sindharta** [comment]
#189

**Comment by karasusan** [comment]
We added the notice on the document. https://github.com/Unity-Technologies/UnityRenderStreaming/pull/189
Thanks for your report!
