### ISSUE TITLE
The delay is so high

### ISSUE THREAD

**Issue by 823639792** [Unity-Technologies/UnityRenderStreaming#174]
When I use Unity Editor or export to .exe, the program runs well.
But when I use c++ CreateProcess API Or vb script 
```
    Set ws = createObject("WScript.shell") 
    ws.run "xxxx.exe",vbhide
```
to run the program with hidden window, the delay is so high(about 2-3s), that can't interact with program.

Where is the cause of such a high delay?
or
How it run with --batchMode (Silent mode)?

**Comment by 823639792** [comment]
If I used Unity Server Build, the terminate print:
`
[WebRTC] Hardware encoder initialization failed
`

**Comment by 823639792** [comment]
1. Open the xxx.exe ,  delay is low.
2. ShowWindow((HWND)(0x000D086E) ,SW_HIDE);    delay is high.
3. ShowWindow((HWND)(0x000D086E), SW_SHOWNORMAL);  delay is low.

**Comment by podborski** [comment]
> If I used Unity Server Build, the terminate print:
> `[WebRTC] Hardware encoder initialization failed`

I think this can be related to the problem which I mentioned in [this question](https://answers.unity.com/questions/1672109/native-texture-pointer-returns-0-in-headless-build.html)

In a Server Build the renderer is a Null Device and therefore the `GetNativeTexturePtr()` of the RenderTexture  returns `0`. Which probably causes the encoder initialization issue.

**Comment by karasusan** [comment]
This behavior is by design.

**Comment by JepsonPeng** [comment]
> When I use Unity Editor or export to .exe, the program runs well.
> But when I use c++ CreateProcess API Or vb script
> 
> ```
>     Set ws = createObject("WScript.shell") 
>     ws.run "xxxx.exe",vbhide
> ```
> 
> to run the program with hidden window, the delay is so high(about 2-3s), that can't interact with program.
> 
> Where is the cause of such a high delay?
> or
> How it run with --batchMode (Silent mode)?

Did you solve this problem？

**Comment by maximeLong** [comment]
Hi, is there a recommended (unofficial) solution for running Unity RenderStreaming from batchmode or a server build? Or does Unity need a desktop environment with a display output to generate its graphics full stop?

**Comment by karasusan** [comment]
> Where is the cause of such a high delay?
Is this caused by Unity? Could you test without Unity?

> How it run with --batchMode (Silent mode)?
No, The graphics device is needed for Unity.
