### ISSUE TITLE
The version of the hardware codec driver does not support API

### ISSUE THREAD

**Issue by Lakuman** [Unity-Technologies/UnityRenderStreaming#175]
I have the following error when i'm trying to load use Unity Render Streaming : 

_The version of the hardware codec driver does not support API_

I tried to look the dependencies on this website but i didn't found the solution, do you have an idea ? https://developer.nvidia.com/nvidia-video-codec-sdk

**Comment by sindharta** [comment]
Can you try updating your NVidia driver ?

**Comment by sindharta** [comment]
What is the version of your NVidia driver, and what is your graphic card ?

**Comment by Lakuman** [comment]
[cid:image003.png@01D58375.3218DC40]
There is all informations of my graphic card.
Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Sindharta Tanuwijaya <notifications@github.com>
Envoyé : Tuesday, October 15, 2019 4:24:22 PM
À : Unity-Technologies/UnityRenderStreaming <UnityRenderStreaming@noreply.github.com>
Cc : AdrienRoussel <roussel-adrien@outlook.fr>; Author <author@noreply.github.com>
Objet : Re: [Unity-Technologies/UnityRenderStreaming] The version of the hardware codec driver does not support API (#175)


What is the version of your NVidia driver, and what is your graphic card ?

**Comment by Lakuman** [comment]
My graphic Card is a GeForce GTX 1050
Pilote Version : 391.25

**Comment by Lakuman** [comment]
Okay it's all my fault my driver was not update.

**Comment by sindharta** [comment]
Ok, glad it helped.
Closing this issue.
