### ISSUE TITLE
 The screen of unity is normal, but in the browser, the scene cannot be displayed

### ISSUE THREAD

**Issue by xuchonghao** [Unity-Technologies/UnityRenderStreaming#176]
I have the following error and problem when i'm trying to load use Unity Render Streaming :

First , When I run this scene in unity  on my laptop,  Windows 10,the graphics card used by my device is NVIDIA GeForce 940MX.  The screen of unity is normal, but in the browser, the scene cannot be displayed, which means that the video stream is not coming and the sound is not coming . 
    Unity has error : The version of the hardware codec driver does not support API ....... It seems that what GitHub said is the hardware problem of the graphics card.
Second,  I used another desktop, Windows 7, which had a GTX1070 graphics card. The driver had been updated.This time there was no error, and the browser also does not show the scene.  
What's going on?Why can't the browser display the scene?

**Comment by sindharta** [comment]
I don't think Geforce 940 MX  is supported.
And this hasn't been tested on Windows 7 yet.

Please see our [FAQ](https://github.com/Unity-Technologies/UnityRenderStreaming/blob/release/1.1.3/Packages/com.unity.template.renderstreaming/Documentation~/en/faq.md) and [supported graphics cards on Nvidia site for more details](https://developer.nvidia.com/video-encode-decode-gpu-support-matrix).

**Comment by xuchonghao** [comment]
I see . Thank you  very much!
