### ISSUE TITLE
Play for more than ten hours, the delay is increased to 2 seconds

### ISSUE THREAD

**Issue by 823639792** [Unity-Technologies/UnityRenderStreaming#177]
Play for more than ten hours, the delay is increased to 2 seconds.
Refresh the page, the delay returns to normal.

**Comment by karasusan** [comment]
Thanks for your report.
I have never seen this issue. We should test to replicate the issue.

**Comment by karasusan** [comment]
memo: URS-390

**Comment by BruceKristelijn** [comment]
My guess would be the client keeps all received data and slowly falls behind decoding the frames. I have a device which might be too slow to decode aswell. Getting slower way quicker.

**Comment by karasusan** [comment]
Does anyone reproduce the same issue?
We want to close the ticket if no one have trouble.
