### ISSUE TITLE
Dead link in documentation.

### ISSUE THREAD

**Issue by peter-pimley-unity** [Unity-Technologies/UnityRenderStreaming#180]
In the English documentation page `tutorial.md`, there is a link called "supported browsers".  It does not link to anywhere.  The user just arrives at the list of files in the "en" directory.  I think the Japanese documentation has the same issue.

**Comment by karasusan** [comment]
Thanks for your report.
I'll fix that.

**Comment by karasusan** [comment]
The broken link is fixed and merged `release/1.1.3` branch.
We will release it soon.
Thank you!
