### ISSUE TITLE
RTCPeerConnection.OnTrack do not invoke as local offer

### ISSUE THREAD

**Issue by JiphuTzu** [Unity-Technologies/UnityRenderStreaming#187]
Hi, I want connect webserver in unity as the way in broswer, all is OK but the OnTrack handler is not called, I see in broswer it works well. It means, when setting the peer local as offer and remote as answer，OnTrack doesnot work。

**Comment by karasusan** [comment]
We have never tested your case.
I will try to check them.

**Comment by JiphuTzu** [comment]
> We have never tested your case.
> I will try to check them.

Thanks, Looking forward to you results.

**Comment by karasusan** [comment]
Hi, very sorry for the long time waiting.
We already added the test case below and it works well.
https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Tests/Runtime/MediaStreamTest.cs#L242-L249

If you have no problem, I will close this.
