### ISSUE TITLE
Microphone input interrupted by Render Streaming Component...

### ISSUE THREAD

**Issue by bwdan** [Unity-Technologies/UnityRenderStreaming#188]
Enabling the render streaming component stops (or lags) microphone input programmatically added to an audio source on a gameobject.  Is this by design?  When render streaming is on does it take over control of the microphone?  If so, is there a way to use the microphone while render streaming?

**Comment by karasusan** [comment]
Are you using this API?
https://docs.unity3d.com/ScriptReference/Microphone.html

We have never tested to use the microphone while render streaming.
I will try that.

**Comment by karasusan** [comment]
This issue is fixed by the changes.
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/222

We will make a sample to explain how to combine it with a microphone API.
