### ISSUE TITLE
Will not display on iPad Pro

### ISSUE THREAD

**Issue by polygonfuture** [Unity-Technologies/UnityRenderStreaming#191]
I've ran the test scenes, and all displays properly on my computer. When I test on iOS device (iPad Pro specifically), I do not get any visuals.

Creating an SSL certificate based on your tutorial, gives me errors in all browsers about invalid certificate.  I have followed your SSL tutorial 3 times now and each time the same result.

**Comment by sindharta** [comment]
The certificate is "invalid", because you created the certificate yourself and it wasn't assigned to you by a trusted Certificate Authority.
For local testing, this is okay and you should be able to ignore the warning and proceed to see the page.

Answer posted on the [forum](https://forum.unity.com/threads/unity-render-streaming-introduction-faq.742481/page-3#post-5213552) too

**Comment by polygonfuture** [comment]
> The certificate is "invalid", because you created the certificate yourself and it wasn't assigned to you by a trusted Certificate Authority.
> For local testing, this is okay and you should be able to ignore the warning and proceed to see the page.
> 
> Answer posted on the [forum](https://forum.unity.com/threads/unity-render-streaming-introduction-faq.742481/page-3#post-5213552) too

Unless the certificate is valid, iOS fails to load the RTC stream, and fails to allow any transmission of user input.   No buttons work, and no video is streamed. 

It works fine on my windows machine.

**Comment by sindharta** [comment]
It works, but you have to press some buttons to get past it.
Try googling "safari ios bypass certificate error".

To avoid double posting, please keep the conversation only here or only in the forum.

**Comment by polygonfuture** [comment]
It actually does not work.   You can access the page but it does not stream the video.

**Comment by polygonfuture** [comment]
If this is the case,  it should be documented.  There is no mention of any of this in the https documentation. I will be attempting this and reporting back.    It would be nice to thoroughly explain for iOS browser end points how to get this working, as it is a hassle currently.

**Comment by polygonfuture** [comment]
Also if you are simply saying clicking past the errors in the browser aka ‘proceed anyway...’ this definitely does not solve my problem of the webrtc stream and user input not working.  The site shows the main interface, but it remains blank with no streams on iOS devices.   Windows devices work fine.

**Comment by sindharta** [comment]
Can you let us know:
- The browser you are using and its version
- The version of iOS you are using

Also, when you set it to https, can you see the streaming on your Windows devices ?

**Comment by polygonfuture** [comment]
I can replicate the problem on the following devices:

iPad Pro 12.9 (2018)
-iPad OS 13.2.2
-Safari
-Chrome 78.0.3904.84

iPhone 6S Plus
-iOS 12.1
-Safari 
-Chrome 78.0.3904.84
-Firefox 20.2 (16690)

iPhone 6S
-iOS 13.2.2
-Safari
-Chrome 78.3904.84

HTTPS works without problem on my Windows machines.

**Comment by sindharta** [comment]
I just retried it using the following:
- iPhone 6S (iOS 13.2.3) & Safari

And it worked.

So some questions:
- Do you have any error logs appearing on Unity Editor ?
- Any screenshots that you can attach here ? Both from Unity Editor and your iOS
- Are you testing the latest branch (release/1.1.3) from this repo ?
- Just in case, could you try restarting your computer and retry ? Perhaps we have a bug there.

FYI, only Safari is supported on iOS.

**Comment by sindharta** [comment]
Closing due to non-activity. Please reopen if necessary.
