### ISSUE TITLE
Cannot receive stream (OnTrack) from remote peer in Unity 

### ISSUE THREAD

**Issue by SHanDesign1993** [Unity-Technologies/UnityRenderStreaming#194]
Hi, I want to made a videoplayer in unity like the web app sample. after I established ICE connection, I found that RTCPeerConnection.OnTrack event NOT being called.
It seems there might be some issues in Unity.WebRTC.dll ?

could you please check it? thank you.

**Comment by karasusan** [comment]
Sorry, late reply. I wrote an answer to your question.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/44
