### ISSUE TITLE
What is "Add HW Encoder" for V2?

### ISSUE THREAD

**Issue by L-Naej** [Unity-Technologies/UnityRenderStreaming#199]
Hi there,
I see there is "Add HW Encoder" featured in V2/2.1, but isn't the plugin already using hardware acceleration with NVIDIA cards? Or do you mean add support for AMD too?

Thanks :)

**Comment by karasusan** [comment]
We have a plan to support AMD cards with [AMFSDK](https://github.com/GPUOpen-LibrariesAndSDKs/AMF)

**Comment by L-Naej** [comment]
Ok thanks for the explanation karasusan!
