### ISSUE TITLE
Unity UI does not respond to WebRTC click events

### ISSUE THREAD

**Issue by L-Naej** [Unity-Technologies/UnityRenderStreaming#201]
Hi,

I tried to use Unity UI with RenderStreaming, with all types of UI (screen overlay, world, world overlay) and it does not respond to click event received from WebRTC.

Do you know if there is a special setting to make it work, or if it's simply not possible with the current implementation?

I looked into the new Input system documentation but had no luck so far.

Thanks for your help. :)

**Comment by karasusan** [comment]
Could you tell me a package version of the Input System and UnityUI? 
We'll try to check the behavior of the UI interaction.

**Comment by kannan-xiao4** [comment]
Hi, @L-Naej 
Please Try following step

1. Update `com.unity.inputsystem` to `1.1.0-preview2` on PackageManager.

2. In ProjectSetting->Player->OtherSetting, check `Allow unsafe code`.

3. Replace the floowing Component with `EventSystem` on the Scene.

```CSharp
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.LowLevel;

public class CustomEventSystem : EventSystem
{
    protected override void Awake()
    {
        base.Awake();
        unsafe
        {
            InputSystem.onDeviceCommand += InputSystemOnDeviceCommand;
        }
    }

    private static unsafe long? InputSystemOnDeviceCommand(InputDevice device, InputDeviceCommand* command)
    {
        if (command->type != QueryCanRunInBackground.Type)
        {
            // return null is skip this evaluation
            return null;
        }

        ((QueryCanRunInBackground*)command)->canRunInBackground = true;
        return InputDeviceCommand.GenericSuccess;
    }

    protected override void OnApplicationFocus(bool hasFocus)
    {
        //Do not change focus flag on eventsystem
    }
}
```

4. (Optional) For UnityEditor, Open Window->Analysis->InputDebugger and turn on `Lock Input to Game View` in Options.
