### ISSUE TITLE
Camera moves automatically on MacOS Unity Editor

### ISSUE THREAD

**Issue by karasusan** [Unity-Technologies/UnityRenderStreaming#219]
### Environment
- MacOS
- Unity Editor 2019.3.0f6 
- Input System 1.0.0-preview.4

### How to reproduce the problem
1. Open template project.
2. Open sample scene and play.
3. Switch other application from Unity Editor with the keyboard shortcut (Command+Tab)
4. Switch Unity Editor with the keyboard shortcut (Command+Tab)

### Status
This issue caused by "Input System". We are waiting for their answer.

**Comment by karasusan** [comment]
The same issue reported on Unity Issue Tracker. 
https://issuetracker.unity3d.com/issues/input-system-macos-keyboard-button-a-is-triggered-when-taking-a-screenshot-with-built-in-tools

We have to wait to solve the issue by the Input system development team.

**Comment by kannan-xiao4** [comment]
memo: URS-335

**Comment by karasusan** [comment]
This issue is already fixed 
https://issuetracker.unity3d.com/issues/macos-input-debugger-shows-invalid-key-state-after-a-shortcut-which-temporarily-freezes-the-screen
