### ISSUE TITLE
Unity Render Streaming not working 2019.3.1f1

### ISSUE THREAD

**Issue by Juanmaramon** [Unity-Technologies/UnityRenderStreaming#227]
If I click on play on the sample scene I get these errors:

DllNotFoundException: Packages/com.unity.webrtc/Runtime/Plugins/x86_64/webrtc.dll
Unity.WebRTC.WebRTC.Initialize (Unity.WebRTC.EncoderType type) (at Library/PackageCache/com.unity.webrtc@b00cafe0bc6fd7170eab00689eaafae2d1698299/Runtime/Scripts/WebRTC.cs:228)
Unity.RenderStreaming.RenderStreaming.Awake () (at Assets/Scripts/RenderStreaming.cs:63)

Assertion failed on expression: 'sceneRanges.empty()'

And streaming is not working.

**Comment by sindharta** [comment]
Thank you for your issue.
We are aware of this issue, and are currently working on it.

**Comment by Juanmaramon** [comment]
@sindharta any ETA for the fix and patch? Thanks

**Comment by sindharta** [comment]
We just released RenderStreaming 1.2.0
https://forum.unity.com/threads/unity-render-streaming-update.836362/

This should fix your issue.

**Comment by Juanmaramon** [comment]
Thanks for the update!

Unfortunately, the errors appear again with version 1.2.0. Maybe I'm doing something wrong?

![streaming](https://user-images.githubusercontent.com/2853271/75463647-639dd800-5986-11ea-8347-33eacf757712.png)

![err](https://user-images.githubusercontent.com/2853271/75463787-8f20c280-5986-11ea-8e26-c6e916030f06.png)

**Comment by karasusan** [comment]
I reproduced your issue.
I will make the hotfix version soon.

**Comment by karasusan** [comment]
I just finished releasing packages.
Please try the latest version!
