### ISSUE TITLE
which webbrowser can i used in wpf？ 

### ISSUE THREAD

**Issue by dupeng0224** [Unity-Technologies/UnityRenderStreaming#230]
i have used chromiumwebbrowser and added "enable-media-stream" params
settings.CefCommandLineArgs.Add("enable-media-stream", "enable-media-stream");
but the video can not displayed.
in RenderStreaming.cs there is a error.
at 187 line
opLocalDesc.isError is true
how can i  fixed this error?

**Comment by karasusan** [comment]
I am sorry but we have never tested with webview on WPF.
Could you tell me more information about the browser you are using?

I consider the browser might not support WebRTC.
I investigated the webview working on WPF and found WebView2 which is the Chrominium base browser. 
https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2

I expect it will work well.

**Comment by kannan-xiao4** [comment]
@dupeng0224 Do you have any update?
We will close this issue if you don't have update.

**Comment by karasusan** [comment]
Please reopen if you have another question about this issue. Thanks
