### ISSUE TITLE
URP Color Bug on ubuntu 18.04?

### ISSUE THREAD

**Issue by ahmkam** [Unity-Technologies/UnityRenderStreaming#239]
I am using the URP example and facing this weird color issue.

I am unable to change camera's target texture setting at runtime since that is not allowed

**Ubuntu:18.04**
**Render streaming version: 1.2.0**
**Unity: 2019.3.3f1**
**URP: 7.1.8**
![Screenshot from 2020-03-09 13-33-29](https://user-images.githubusercontent.com/28952221/76209679-213c8c80-620b-11ea-8d0d-dd1a49688854.png)

**Comment by karasusan** [comment]
Oh, This issue should be checked soon. Thanks!

**Comment by karasusan** [comment]
This issue is already fixed and the hotfix version has released as `1.2.3`. 
Great thanks!
https://github.com/Unity-Technologies/UnityRenderStreaming/releases/tag/1.2.3-preview
