### ISSUE TITLE
VideoStreamTrack file missing in feat/multicamera2.0

### ISSUE THREAD

**Issue by ahmkam** [Unity-Technologies/UnityRenderStreaming#243]
I am trying to test the multicamera2.0 branch but it seems that the **VideoStreamTrack** file is not added to the project

**Comment by karasusan** [comment]
`feat/multicamera2.0` is a feature branch, as you know, most of the feature branches are unstable.
This branch depends on this package `com.unity.webrtc` which is in development.

I hope you can wait for the next version containing the feature.

**Comment by ahmkam** [comment]
What is the expected release date for the multi-cam version?
