### ISSUE TITLE
Can it server build?

### ISSUE THREAD

**Issue by veyvin** [Unity-Technologies/UnityRenderStreaming#244]
![批注 2020-03-18 173206](https://user-images.githubusercontent.com/6776758/76946171-952f1100-693e-11ea-9cbe-020303d55253.png)

**Comment by karasusan** [comment]
No, it does not work.
Because "Server build" strips the graphics feature.

I understand what you are trying to do but I am afraid we can’t provide any information how to do it.

**Comment by karasusan** [comment]
This is by design of Unity runtime, so I will close the issue.
