### ISSUE TITLE
Make it work offline

### ISSUE THREAD

**Issue by lobellomatteo** [Unity-Technologies/UnityRenderStreaming#248]
Hi! 
Is it possible to make the streaming work via WiFi without an Internet connection?

**Comment by gtk2k** [comment]
I experimented.
I think it is possible.
First, pass the RTCConfiguration with null iceServers to the RTCPeerConnection constructor to avoid using the STUN / TURN server.

```
conf = new RTCConfiguration {iceTransportPolicy = RTCIceTransportPolicy.All, iceServers = null};
pc = new RTCPeerConnection (ref conf);
...
```

Start the signaling server in the LAN and set its URL to "URL Signaling".
If you execute this, you will be able to connect within the LAN without going through the Internet.

**Comment by lobellomatteo** [comment]
Thanks a lot!
