### ISSUE TITLE
way to monitor bandwidth?

### ISSUE THREAD

**Issue by ahmkam** [Unity-Technologies/UnityRenderStreaming#254]
Is there a way to monitor bandwidth consumed by the render streaming web client? The information in the browser network tab is redundant and not very useful as most of them are GET request for candidate and answer

**Comment by karasusan** [comment]
Have you tried "webrtc-internals" on Chrome?
https://testrtc.com/webrtc-internals-parameters/

It is useful for checking the bandwidth of video/audio streaming.

**Comment by karasusan** [comment]
@ahmkam 
Sorry for waiting a long time.
We implemented the stats API and reveal it soon.
