### ISSUE TITLE
Can not establish streaming to the embedded browser in unity scene.

### ISSUE THREAD

**Issue by iceleaf97** [Unity-Technologies/UnityRenderStreaming#260]
I have tried to use the unity asset "Embedded Browser" to receive the render streaming.
This is the asset:
https://assetstore.unity.com/packages/tools/gui/embedded-browser-55459
However I got the error message "Network Error: Unity.WebRTC.RTError."  in the scene of this UnityRenderStreaming project.

I run webserver.exe as a https server. It does work that the render streaming shows on different browsers, such as Chrome, Safari at Windows/macOS/iOs/Android devices.

Is it possible to show the render streaming on the embedded browser in the unity scene?

**Comment by iceleaf97** [comment]
It looks like the embedded browser that doesn't support h.264-encoded video.
It is possible that transcode the render streaming from h.264 to vp8?

**Comment by karasusan** [comment]
@iceleaf97 
Sorry for my late reply.
You can use VP8 encoder if you disable "Use HW encoder" on Render Streaming inspector.

**Comment by karasusan** [comment]
@iceleaf97 
Have you solved this issue?
Can I close this?

**Comment by iceleaf97** [comment]
@karasusan Sorry for my late reply. I have solved this issue. Thank you!

**Comment by MrSujitMarcus** [comment]
@iceleaf97 please tell us how did you solve it?
