### ISSUE TITLE
Is webserver.exe running as a websocket server?

### ISSUE THREAD

**Issue by iceleaf97** [Unity-Technologies/UnityRenderStreaming#263]
I run webserver.exe as a https server and the render streaming works.
I try to use the url "wss://(my domain name): port" to establish websocket connection in my unity project to this remote server.
However the websocket client can not connect to the remote server.
How can I establish the websocket connection?
I try to create a unity-to-unity render streaming.

**Comment by karasusan** [comment]
You can see the command arguments on this document.
https://docs.unity3d.com/Packages/com.unity.renderstreaming@2.0/manual/en/webapp.html
