### ISSUE TITLE
No Video Stream on MacOS (or Errors)

### ISSUE THREAD

**Issue by jdp1g09** [Unity-Technologies/UnityRenderStreaming#271]
Running this on MacOS. To reproduce:
- Have opened the `SimpleScene`.
- Ran the WebApp and navigated to `localhost`, where the web interface loads with the "play" icon as expected.
- Run the Unity Scene
- Click the "Play" icon in Google Chrome (Version 80.0.3987.132 (Official Build) (64-bit))
- Connection established (Browser Console logs as follows):
```
pc.iceConnectionState:connected
video-player.js:113 Datachannel connected.
```
- No errors reported in either Unity or Browser, but no video stream appears.
- I can however click the buttons in the browser to control the lighting inside the Unity Environment.

**Comment by jdp1g09** [comment]
also worth mentioning I am using `Unity 2019.3.9f1`

**Comment by karasusan** [comment]
Sorry, late reply. Could you tell me the package version you are using?

**Comment by jdp1g09** [comment]
@karasusan using `1.2.3-preview`

**Comment by karasusan** [comment]
Thanks, last week we released the new version 2.0.0.
Could you try the new version and let me know the results?

**Comment by jdp1g09** [comment]
@karasusan I'm now seeing hte following errors when trying to run the `samplescene`:

```
NullReferenceException: Object reference not set to an instance of an object
Unity.RenderStreaming.SimpleCameraController.FixedUpdate () (at Assets/Scripts/SimpleCameraController.cs:236)
```

**Comment by jdp1g09** [comment]
When trying to run `SimpleRenderStreaming HDRP` there is a log about 2 audio listeners too for what it's worth. Although that isn't a hindrance on it not working I believe. Just thought it worth mentioning.

**Comment by jdp1g09** [comment]
I seem to be able to successfully `Play` the `SimpleRenderStreaming HDRP` scene and am seeing logs showing `Signaling: Posting HTTP data: {"connectionId":"5c5ad732-f241-4648-94a8-9460236324d3","candidate":"candidate:1751352921 1 tcp 1518217471 2a02:c7f:a878:6400:d6c:f0e3:6a3e:bdbc 56471 typ host tcptype passive generation 0 ufrag DSHI network-id 2 network-cost 50","sdpMid":"0","sdpMLineIndex":0}`

However, no success on receiving this data int he web app at all now, or being able to establish a connection through the web app.

The only error I'm seeing in the WebApp console is:
```
Uncaught (in promise) DOMException: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Error processing ICE candidate
```
and
```
x: NaN, y: 0, scale: Infinity, originX: NaN, originY: 0 mouse button:0
video-player.js:247 Connection not ready
```

**Comment by karasusan** [comment]
Please let me know which browser are you using.
If you use Mac OS Safari, you have to access the webpage via https protocol.
https://docs.unity3d.com/Packages/com.unity.renderstreaming@2.0/manual/en/faq.html#web-app-doesnt-run-on-safari-browser

**Comment by jdp1g09** [comment]
Using Chrome as per my original post

**Comment by karasusan** [comment]
We need to get more info to solve the issue.
Could you access the URL `chrome://webrtc-internals/` on your chrome and download a dump file?

We can check the dump file using an import tool.
https://fippo.github.io/webrtc-dump-importer/

**Comment by rooi** [comment]
Hi, 
I ran into the same problem, so I subscribed to this issue. I just tried again and it works on mac and ios, both in a safari browser.
I cannot seem to pinpoint what caused it from before. Perhaps something with a certificate?
I'm using a wss:// signaliing url in with a let's encrypt certificate (generated using [acme](https://github.com/acmesh-official/acme.sh)) and connect using https:// btw

**Comment by AdamFrisby** [comment]
> I seem to be able to successfully `Play` the `SimpleRenderStreaming HDRP` scene and am seeing logs showing `Signaling: Posting HTTP data: {"connectionId":"5c5ad732-f241-4648-94a8-9460236324d3","candidate":"candidate:1751352921 1 tcp 1518217471 2a02:c7f:a878:6400:d6c:f0e3:6a3e:bdbc 56471 typ host tcptype passive generation 0 ufrag DSHI network-id 2 network-cost 50","sdpMid":"0","sdpMLineIndex":0}`
> 
> However, no success on receiving this data int he web app at all now, or being able to establish a connection through the web app.
> 
> The only error I'm seeing in the WebApp console is:
> 
> ```
> Uncaught (in promise) DOMException: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Error processing ICE candidate
> ```
> 
> and
> 
> ```
> x: NaN, y: 0, scale: Infinity, originX: NaN, originY: 0 mouse button:0
> video-player.js:247 Connection not ready
> ```

Also seeing same issue.

**Comment by jimengying** [comment]
Hi,
I ran into the same problem, whether this problem has been solved?

**Comment by jimengying** [comment]
Hello, I ran into the same problem as @jdp1g09  on two different computers(windows10 64bit).

- Connection established
- No errors reported in either Unity or Browser, but no video stream appears.
![~8)2{QI9%NT585$7GV47~8O](https://user-images.githubusercontent.com/38742946/88025318-b01cc680-cb66-11ea-87b8-5d0a1239840e.png)
- I can however click the buttons in the browser to control the lighting inside the Unity Environment.

`Unity 2019.3.9f1`
`Google Chrome  84.0.4147.89(64bit)`
`2.0.2-preview`

**Comment by karasusan** [comment]
Please check the Firewall of your local environment like this.
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/252#issuecomment-682292789

**Comment by karasusan** [comment]
@jdp1g09 
Could you check this comment?
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/271#issuecomment-682356418

**Comment by karasusan** [comment]
@jdp1g09, @jimengying
Long time no see. 
Can I close it? Thanks.
