### ISSUE TITLE
URP unstable with high resolutions (4K support)

### ISSUE THREAD

**Issue by a82kd** [Unity-Technologies/UnityRenderStreaming#303]
If I try to stream 4k in a URP project, Unity crashes.

Steps to reproduce:
1. Created project from URP template (2019.3.13f) 
2. Installed UnityRenderStreaming 2.0.2
3. Loaded URP Demo Content
4. Setting 4k for the first Stream Render Camera Script
5. Stream starts up and is visible for some seconds in the browser, then Unity crashes.

The HDRP example included in the package works fine with 4k.

**Comment by a82kd** [comment]
Hi, short update: I also tried it with a large VM, NV6 on Azure (Tesla M60, 8GB, 32GB shared).
4K is possible sometimes, but not stable. 5K again crashes.
So the issue seems not to be related to the hardware. Moreover, stable 4K should be possible with this setup. This most likely seems to point to a memory leak, or?

**Comment by kannan-xiao4** [comment]
@a82kd 
Does this issue occur with the latest packages now?

Also, support for 4K resolution is not yet supported by us, so please wait for it.
related issue : #303

**Comment by karasusan** [comment]
memo: WRS-221
