### ISSUE TITLE
[REQUEST]  Fixed rendering pipeline to transmit the fused image of multiple cameras

### ISSUE THREAD

**Issue by NetEagle1** [Unity-Technologies/UnityRenderStreaming#307]
**Is your feature request related to a problem? Please describe.**
When I don't use hdrp and URP, how to get the final screen picture after multiple cameras are mixed? The picture I get through id3d11rendertargetview contains all the contents of game window (as shown in the figure below). But I just want to get the real result picture of the operation, and I don't need unity's own window
![RenderPluginTest](https://user-images.githubusercontent.com/8072571/84353577-04d93300-abf2-11ea-80b1-2c0c049936cd.png)

**Describe the solution you'd like**
It is hoped that the renderstreaming plug-in can also support multi camera mixed rendering output to webrtc in non hdrp or URP modes

**Describe alternatives you've considered**
I want to directly obtain the pictures submitted to the screen by unity through DX, just like AV Pro capture, but I don't know how to obtain the game screen pictures with high performance, rather than the whole game window.

**Additional context**

**Comment by karasusan** [comment]
This issue is fixed by #322.
