### ISSUE TITLE
[BUG] Video Stream doesn't work at MacOS (without HDRP or URP)

### ISSUE THREAD

**Issue by noseeevil** [Unity-Technologies/UnityRenderStreaming#308]
Hello!

I created empty project and added only WebRTC (prev - 2.0.0) and Unity Render Streaming 
(prev - 2.0.0), without HDRP/URP and its work fine at Windows 10, I can see video (in web browser), but the same setup doesn't work at MacOS, I hear the sound from the stream, and it looks like there is a stream according to logs, but the picture is always black (in web browser). But, if I add HDRP in project and setup it - video stream starts work at MacOS.

Is there a way to use it without hdrp/urp? 

 - OS: MacOS 10.15.2
 - Browser: Chrome 83.0.4103.106
 - Unity Version: 2019.3.15
 - WebRTC: [2.0.0-preview]
 - UnityRenderStreaming: [2.0.0-preview]

**Comment by karasusan** [comment]
We made a new sample with build-in render pipeline. #315
