### ISSUE TITLE
[BUG] PUT request is being sent without Content Length being set

### ISSUE THREAD

**Issue by philzeh** [Unity-Technologies/UnityRenderStreaming#311]
**Describe the bug**
PUT request is being sent without Content Length being set

**To Reproduce**
PUT request is being sent without Content Length being set

**Expected behavior**
PUT request is being sent without Content Length being set

**Screenshots**
PUT request is being sent without Content Length being set

**Environment (please complete the following information):**
PUT request is being sent without Content Length being set

**Additional context**
PUT request is being sent without Content Length being set

File
UnityRenderStreaming/com.unity.template.renderstreaming-hd/Assets/Scripts/Signaling/HttpSignaling.cs

HttpWebRequest request = (HttpWebRequest)WebRequest.Create($"{m_url}/signaling");
request.Method = "PUT";
request.ContentType = "application/json";
request.KeepAlive = false;

This needs
request.ContentLength = 0;

**Comment by karasusan** [comment]
Already fixed on the develop branch
