### ISSUE TITLE
4K streaming ,The Unity crumbled

### ISSUE THREAD

**Issue by huihui-gao** [Unity-Technologies/UnityRenderStreaming#317]
i try to stream 4K(3840*2160) in SimpleRenderStreamingHDRP Scene, Link to Chrome, and after a few seconds, Unity crumbles

1. creat Uinity project
2.Installed UnityRenderStreaming 2.0.2
3. Loaded SimpleRenderStreamingHDRP
4. change Camera streamingSize 3840*2160
5.Enter the address in Chrome  Drag the mouse,
6.Unity crumbles
7.When I switched back to 1920*1080, the program worked fine
**Expected behavior**
the program worked fine

**Unexpected behavior**
Microsoft Visual C++ Runtime Library
This application has requested the Runtimeto terminate it in an unusual
![图片1](https://user-images.githubusercontent.com/69502543/89870227-189c1800-dbe8-11ea-8f4e-865daf38a42a.png)

**Environment
 - OS: [Windows] (NVIDIA GeForce RTX 2080 Ti)
 - Browser [chrome]
 - Unity Version [e.g. 2019.3.0f5]
 - Package version [e.g. 2.0.2-preview]

**Comment by karasusan** [comment]
Related issue for 4k support #236 #303

**Comment by gushenjie** [comment]
I have the same problem. Has it been resolved?

**Comment by gushenjie** [comment]
my resolution is  4096x2160, If you use H264, it will crash, if you use VP8, it will not,I have the same problem. Has it been resolved?

**Comment by pilzinho** [comment]
Still the same problem here with the newest versions. I streamed 8k in software using VP8 but with hardware encoding it already crashes when using something higher than 1920x1080. But software isn't really an option with higher resolutions. Actually in general ;)

**Comment by kannan-xiao4** [comment]
4k support depends on Nvidia Codec updates. We are planning to support it as well.
memo: WRS-151

After that, streaming in 4k with H264 may be possible in the future.
