### ISSUE TITLE
Linux build doesn't stream anything[BUG]

### ISSUE THREAD

**Issue by tahameg** [Unity-Technologies/UnityRenderStreaming#318]
I have tested this package in the editor that runs in windows and everything works like charm. Also, when I take a build on windows, everything keeps working. However, when I take a build for linux, it just doesn't stream video or controls. I have spent a fair amount of time for resolving this issue but no results yet.

**Comment by karasusan** [comment]
I think you are using vulkan as a graphics API. Please check the player settings.
Vulkan API is not supported by the currently version.

In our plan, the support vulkan API by the next version 2.2.

**Comment by karasusan** [comment]
The graphics driver on your PC may be old.
If you are using HW encoder, you can check the software encoder.

Using HW encoder requires the graphics driver. The graphics driver on your PC may be old. 
Please try to upgrade it.

**Comment by subjectdenied** [comment]
the current libwebrtc.so has cuda.so linked, so even if software encoding might be possible, it doesnt work on a system without nvidia, cause it errors with DLLNotFoundException (at least for me this went away when installing cuda). however installing cuda for most linux-systems means to download a lot of nvidia (driver) dependencies - even if intel or amd is available only

**Comment by karasusan** [comment]
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/318#issuecomment-716230145
Regarding this comment, we are investigating the issue in this [page](https://github.com/Unity-Technologies/com.unity.webrtc/issues/238).

**Comment by karasusan** [comment]
This issue is already fixed in this change
https://github.com/Unity-Technologies/com.unity.webrtc/issues/243

We appreciate your patience as it might take some time for the new release.
