### ISSUE TITLE
[BUG] Safari 13+ users are prompted to allow access to the microphone, they should not be

### ISSUE THREAD

**Issue by doctorpangloss** [Unity-Technologies/UnityRenderStreaming#340]
**Describe the bug**

Safari 14 users are prompted to allow access to the microphone, they should not be.

**To Reproduce**

 1. Run a sample on 586b4818e7 or later (current develop branch)
 2. Open the project
 3. Run the web server.
 4. Use `ngrok` or similar tunneling service to create a valid `https` URL.
 5. Visit the URL on an iOS 14 or later device.
 6. Observe you are prompted with "..." Would Like to Access the Microphone.

A similar prompt appears on Safari.

**Expected behavior**
You should not be prompted to grant access to the microphone.

**Screenshots**

**Environment (please complete the following information):**
 - OS: iOS and macOS
 - Browser: Safari 13 and later
 - Unity Version: 2019.4.13
 - Package version: `develop` direct checkout, tag 586b4818e7

**Additional context**
You should probably narrow your `getUserMedia` call.

**Comment by karasusan** [comment]
Is this issue caused by `ngrok` ?
OK, we have never tested it with the tool, we will try that.

**Comment by doctorpangloss** [comment]
Very possible. I used `ngrok` because it's very simple and works with `https`.

**Comment by doctorpangloss** [comment]
I think this is always true of any domain, and it has nothing to do with `ngrok`. It's like you guys have been testing on `localhost` or have already existing trust with a domain, and just didn't realize this is how it always is.

**Comment by kannan-xiao4** [comment]
Hi @doctorpangloss 
Could you check this PR: https://github.com/Unity-Technologies/UnityRenderStreaming/pull/354 ?

This code is workaround for old version Safari, but no need for latest version Safari.

**Comment by doctorpangloss** [comment]
It works, thank you!
