### ISSUE TITLE
[BUG] Adding multiple ice servers crashes unity editor on new RTCPeerConnection()

### ISSUE THREAD

**Issue by thedrhax14** [Unity-Technologies/UnityRenderStreaming#343]
**Describe the bug**
If you try to add more stun or turn servers when creating RTCConfiguration, it will crash unity editor on new RTCPeerConnection()

**To Reproduce**
1. Go to MediaStream scene from examples
2. Open MediaStreamSample.cs
3. Change original code:
`
private static RTCConfiguration GetSelectedSdpSemantics()
    {
        RTCConfiguration config = default;
        config.iceServers = new[]
        {
            new RTCIceServer { urls = new[] { "stun:stun.l.google.com:19302" } }
        };
        return config;
    }
`
to this
`
private static RTCConfiguration GetSelectedSdpSemantics()
{
        RTCConfiguration config = default;
        config.iceServers = new[] {
            new RTCIceServer {
                urls = new[] { "stun:bn-turn1.xirsys.com" }
            },
            new RTCIceServer {
                urls = new[] { "turn:bn-turn1.xirsys.com:80?transport=udp" }
            },
            new RTCIceServer {
                urls = new[] { "turn:bn-turn1.xirsys.com:3478?transport=udp" }
            }
        };
        return config;
}
`
or you can choose any other ice servers you know
4. Run the example
5. Unity Editor crashes

**Expected behavior**
At least it shouldn't crash

**Environment (please complete the following information):**
 - Windows 10
 - 2019.4.1f1
 - 2.2.0-preview

**Comment by karasusan** [comment]
Fixed crash bug in this change.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/255

You need to set `username` and `credential` to specify the TURN server.

**Comment by thedrhax14** [comment]
@karasusan thanks for the response. Let me try it and I will get back. Also, could you please explain how to the set those values?

**Comment by karasusan** [comment]
> @karasusan thanks for the response. Let me try it and I will get back. Also, could you please explain how to the set those values?

`RTCIceServer` has these parameters.
https://docs.unity3d.com/Packages/com.unity.webrtc@2.2/api/Unity.WebRTC.RTCIceServer.html
