### ISSUE TITLE
[REQUEST] Streaming VFX from Docker

### ISSUE THREAD

**Issue by BabaevDevelop** [Unity-Technologies/UnityRenderStreaming#349]
Hello everyone, we are trying to run vilkan unity project in docker.
Several unpleasant moments arose in the work: when starting the build, the screen blinks once and turns black, the second moment it is not clear how to push all this into the docker and one more faced the problem of streaming from Linux to webRTC, please HELP US what and where you can see and if there are any then similar projects or solutions / analogue
we are using unity samples: https://github.com/Unity-Technologies/VisualEffectGraph-Samples
For base image we try to use Linux/Docker/WebRTC for streaming from docker

**Comment by karasusan** [comment]
Hi, what kind of issues do you have? thanks.
