### ISSUE TITLE
[REQUEST] Please expose the parameters for Color Format and Anti-Aliasing

### ISSUE THREAD

**Issue by Alex-Hughes** [Unity-Technologies/UnityRenderStreaming#350]
**Is your feature request related to a problem? Please describe.**
Currently there is no apparent way to change the color format and anti-aliasing (MSAA) of the render texture used by render streaming. This means that there is no MSAA on the image and not possible to correctly use HDR dependent effects like bloom.

**Describe the solution you'd like**
Please expose the parameters of the render texture used by render texture, so the user can set these options, or add them to the Camera Streamer Component.

![image](https://user-images.githubusercontent.com/41030615/99336284-a876ef80-28c4-11eb-954d-ed9bbc781b83.png)

**Comment by CM2Walki** [comment]
Whilst `Depth Buffer` and `Anti-aliasing` is now exposed. `Color Format` is not. This leads to bloom not working as described by @Alex-Hughes. Just to show-case that it's important to have, here's the side-by-side comparison between in-editor and stream:

![unknown](https://user-images.githubusercontent.com/12199415/171995936-660d9cbf-7893-4d3d-a6e1-40c6a9aca66b.png)

**Comment by CM2Walki** [comment]
I created a temporary standalone workaround `VideoStreamSender` called `HDRCameraStreamSender`:
```
using Unity.WebRTC;
using UnityEngine;

namespace Unity.RenderStreaming
{
    /// <summary>
    /// 
    /// </summary>
    [RequireComponent(typeof(Camera))]
    public class HDRCameraStreamSender : VideoStreamSender
    {
        /// <summary>
        /// 
        /// </summary>
        [SerializeField, RenderTextureDepthBuffer]
        private int depth = 0;

        /// <summary>
        /// 
        /// </summary>
        [SerializeField, RenderTextureAntiAliasing]
        private int antiAliasing = 1;

        /// <summary>
        /// 
        /// </summary>
        public override Texture SendTexture => m_sendTexture;

        private RenderTexture m_sendTexture;
        private Camera m_camera;
        private bool m_running;

        protected virtual void Awake()
        {
            m_camera = GetComponent<Camera>();
        }

        private void OnPostRender()
        {
            if (!m_running)
                return;

            Graphics.Blit(m_camera.targetTexture, m_sendTexture);
        }

        protected override MediaStreamTrack CreateTrack()
        {
            RenderTextureFormat format = WebRTC.WebRTC.GetSupportedRenderTextureFormat(SystemInfo.graphicsDeviceType);

            RenderTexture rt = new RenderTexture(streamingSize.x, streamingSize.y, depth, format)
            {
                antiAliasing = antiAliasing
            };

            rt.Create();
            m_sendTexture = rt;

            if (m_camera.targetTexture == null)
            {
                RenderTexture rtCam = new RenderTexture(streamingSize.x, streamingSize.y, depth, RenderTextureFormat.DefaultHDR)
                {
                    antiAliasing = antiAliasing
                };

                rtCam.Create();
                m_camera.targetTexture = rtCam;
            }

            m_running = true;

            return new VideoStreamTrack(rt);
        }
    }
```
Result:
![HDR](https://user-images.githubusercontent.com/12199415/172004222-9dbcd39a-cf56-46af-a8bd-21ddb0446978.PNG)

Obviously, this creates a bit of overhead and the data that arrives via the stream doesn't have any HDR information. However, at least Bloom is now visible.

Is it fine if I rework this to properly inherit from `CameraStreamSender` and then submit a Pull Request?
