### ISSUE TITLE
[BUG] WebApp keycodes for NumapdAdd and NumpadSubtract are wrong

### ISSUE THREAD

**Issue by sofusoe** [Unity-Technologies/UnityRenderStreaming#352]
**Describe the bug**
In the Keymap dict in register-events, keys 80 and 81 are referenced by the keycodes "NumpadPlus" and "NumpadMinus".
This should be "NumpadAdd" and "NumpadSubtract"

**To Reproduce**
1. Start the Sample Scene and add a script listening for numpad +/-
2. Press these buttons in the browser
3. Notice that the Keycode events do not get sent to Unity, only the chars '+' and '-'

**Expected behavior**
When Numpad plus/minus is pressed in the browser, it should be sent to Unity.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Unity Version 2019.4.13
 - Package version 2.0.0-preview

**Comment by sofusoe** [comment]
Also, I found the following:
NumpadPeriod should be NumpadDecimal
LeftBracket should be BracketLeft
RightBracket should be BracketRight
Equals should be Equal

**Comment by karasusan** [comment]
This PR is already merged and released a new version 3.0.0-preview.
Thanks a lot!
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/383/files
