### ISSUE TITLE
[BUG] Odd-numbered encoding sizes cannot be decoded on iOS device

### ISSUE THREAD

**Issue by doctorpangloss** [Unity-Technologies/UnityRenderStreaming#358]
**Describe the bug**
Setting the streaming size to e.g. 750x750 produces artifacts when decoded, whereas 1024x1024 or 512x512 do not. The reason 750 is a significant number is that it is the actual display pixel width of an iPhone 6-8 device.

Take a look at this list for all the iOS devices whose browsers or displays report odd numbered sizes: https://developer.apple.com/library/archive/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/Displays/Displays.html

I was using software rendering because hardware rendering has motion artifacts.

**To Reproduce**
1. Set rendering size to 750x750.
2. Disable hardware encoding.
3. Visit the page on an iOS device.
4. Observe an incorrectly decoded image of sideways stripes.

**Expected behavior**
The video stream should decode fine at any size.

**Environment (please complete the following information):**
 - OS: iOS 14, Windows 10
 - Browser: Mobile Safari
 - Unity Version: 2020.1
 - Package version: afda2fe376e32ad3c379186b6791f55e5e0d7978 (**before WebRTC 2.2.1**)

WebRTC 2.2.1 is showing other issues so I reverted to an earlier build. I believe all versions of WebRTC have this issue, but I haven't yet tested.

**Comment by doctorpangloss** [comment]
This reproduces in `com.unity.webrtc` 2.3.1.

**Comment by karasusan** [comment]
Sure. We will check it.
Thanks

**Comment by doctorpangloss** [comment]
The software codec appears to fail in NPOT sizes.

**Comment by karasusan** [comment]
memo: WRS-162

**Comment by doctorpangloss** [comment]
To clarify, it appears to be that iOS only decodes software (VP8) with horizontal multiples of 64.

**Comment by kannan-xiao4** [comment]
@doctorpangloss
Thank you for clarifying the problem
We will confirm it in the next development.

**Comment by karasusan** [comment]
This issue would be fixed for the PR in WebRTC package.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/843
