### ISSUE TITLE
Multi stream not supported

### ISSUE THREAD

**Issue by AtiqRaja** [Unity-Technologies/UnityRenderStreaming#361]
**Describe the bug**
for single stream its working fine but my scenario is I want to do a multi stream like cricket game i want to stream multi matches at a time with some unique id so if any user want to view that specific match he can simple put the match unique id and get the stream for that match

**Tried**
I tried different test using send a unique id in URL but its auto generated URL with signaling give me error 

**Environment:**
 - OS: IOS/Window
 - Browser chrome
 - Unity Version latest
 - Package version latest

**Comment by karasusan** [comment]
May I check the error log which you got?

**Comment by karasusan** [comment]
@AtiqRaja
Have you tried the latest version `2.2.2`?
I would like to close this ticket if there is no reply from you.

**Comment by tkbala** [comment]
Is this working in 2.2.2?

**Comment by karasusan** [comment]
@tkbala Yes, it should work.
