### ISSUE TITLE
Video stream not showing up in browser, already tried checking firewall

### ISSUE THREAD

**Issue by aawill** [Unity-Technologies/UnityRenderStreaming#370]
I'm trying to run the SimpleRenderStreamingURP scene in a remote VM via Azure. I'm able to get the "lights off" and "lights on" buttons working in chrome (latest version) via localhost, as well as the audio button, but the video stream doesn't show up. I've tried disabling windows defender firewall, adding rule exceptions for node.js, webserver.exe, and unity, and nothing seems to work. I'm not seeing any errors in the unity console or the chrome console.

Is there a way for me to see verbose logging from the node server? I suspect that might help some.
I also understand that azure support may not be a stated goal of unity render streaming, but I'm not seeing why it should behave any differently than on my local machine.

**Comment by aawill** [comment]
sike

**Comment by tkbala** [comment]
I have the same issue. I am trying to access the stream from a different laptop. The webpage and everything loads for me, whereas the video stream does not show up. Any thoughts on what I might be missing?
