### ISSUE TITLE
[BUG] Audio stream only supports one channel

### ISSUE THREAD

**Issue by aawill** [Unity-Technologies/UnityRenderStreaming#371]
**Describe the bug**
I've downloaded the legacy render pipeline package via package manager, and I'm trying out the provided example scene. The video stream appears to be working correctly, but when I replace the "Audio" object's AudioClip in Unity with a stereo (2-channel) test file, the audio coming from my browser is still mono. I've verified that unity is playing the audio in stereo, and that the browser can play stereo audio correctly. I've checked this in both chrome and firefox.

**To Reproduce**
1. Open the SimpleRenderStreamingLegacyRP scene in unity
2. Replace the AudioClip asset of the object called "Audio" in the scene with any stereo .wav, .mp3, or other supported audio file
2. Start webserver.exe
3. Hit play in unity
4. Open a browser window, navigate to localhost, and click "play audio"
5. Mute unity in the computer's volume mixer, so you're sure to only hear the sound rendered in the browser
6. Listen with headphones, see if left/right information is reproduced correctly

**Expected behavior**
The audio file should sound the same as it does when played in unity, with left/right information reproduced accurately.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser chrome or firefox
 - Unity Version 2019.4.17f
 - Package version 2.2.2-preview

**Comment by karasusan** [comment]
Thanks for your feedback.

We are going to get started with development to enhance the functionality of audio soon.
Stereo audio is not supported yet, but it should be able to use with the `RTCRtpCodecCapability.channels` property.
https://www.w3.org/TR/webrtc/#dom-rtcrtpcodeccapability-channels

**Comment by aawill** [comment]
Gotcha, thanks for the response. I will need stereo audio a bit sooner for my company's current project, so I'll look into implementing it myself for now. Do you know if I will need to modify the UnityWebRTC package as well as RenderStreaming? From what I can see in the API docs here (https://docs.unity3d.com/Packages/com.unity.webrtc@2.2/api/Unity.WebRTC.AudioStreamTrack.html), it doesn't look like the AudioStreamTrack interface supports channels.

**Comment by karasusan** [comment]
@aawill
> For starters, can you tell me if the WebRTC package for unity supports stereo audio, or do I need to modify that as well?

It is not supported. At least, we have not considered the multi-channel audio streams in this project.
We need to change the implementation of audio processing when passed multi-channel data from `OnAudioFilterRead` method.
https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnAudioFilterRead.html

> Also, I think the instructions here for editing the native webrtc plugin are out of date, could you help me set up the dev environment?

I guess there is no problem to set up the dev environment if only you follow the docs. What kind of issues do you have?

**Comment by aawill** [comment]
I've been attempting to follow the docs here: https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Plugin~/README.md

When I got to the "Embedding libwebrtc" section, I downloaded webrtc-win.zip from the M88 release. I placed the contents inside a folder called "webrtc" inside of Plugin~, as shown here: 
![image](https://user-images.githubusercontent.com/33765493/103560795-40c53580-4e6d-11eb-93bd-d9d355c96a5e.png)
(I notice that the "lib/x64" folder is empty, should there be something there?)

When I then try to execute the cmake command, this is the error:
![image](https://user-images.githubusercontent.com/33765493/103560883-6f431080-4e6d-11eb-9385-9959332c14ac.png)

**Comment by aawill** [comment]
Turns out I had a space in the name of my project folder, cmake didn't like that. Whoops.

I do have a follow-up question about adding stereo support, now that I've explored the WebRTC codebase pretty thoroughly.
I have found that if I pause the chrome debugger here, in video-player.js:
![image](https://user-images.githubusercontent.com/33765493/103711686-cf6cac00-4f6c-11eb-9582-c6db015ab57f.png)
I can then type this into the console:
![image](https://user-images.githubusercontent.com/33765493/103711799-0e9afd00-4f6d-11eb-98ad-ad2a0072cbf0.png)
Notice the absence of the channelCount property.

However, if I query the track settings once the stream has begun, such as in resizeVideo():
![image](https://user-images.githubusercontent.com/33765493/103711994-89fcae80-4f6d-11eb-8bf1-f6c9bc7b6cef.png)

Then I see the following:
![image](https://user-images.githubusercontent.com/33765493/103711964-70f3fd80-4f6d-11eb-9b91-c1ef135b3fb9.png)
Where we can see channelCount has been set to 1, which is a problem.

Do you have any idea where this channelCount=1 property is being set? I've dug around in the WebRTC c++ code looking for it, but the AudioTrackInterface class makes no mention of channels.

**Comment by karasusan** [comment]
@aawill
I appreciate you reported the detail of the issue.
I guess the channel count is exchanged between two peers via SDP. We need to check the description in SDPs whether the value of channel count is contained or not.

**Comment by aawill** [comment]
I did some googling around, and added the following lines before setting both the local and remote descriptions:
```javascript
answer.sdp = answer.sdp.replace('m=audio 9 UDP/TLS/RTP/SAVPF 111', 'm=audio 10 UDP/TLS/RTP/SAVPF 111');
answer.sdp = answer.sdp.replace('useinbandfec=1', 'useinbandfec=1; stereo=1; sprop-stereo=1');
```
The first is to replace [RTP payload type 9 with type 10](https://en.wikipedia.org/wiki/RTP_payload_formats#Audio_and_video_payload_types), in order to support 2 channels. The second line explicitly adds stereo support, as discussed [here.](https://bugs.chromium.org/p/webrtc/issues/detail?id=8133)

The good news is, I now see 2 channels from the audio track getSettings(), as shown here.
![image](https://user-images.githubusercontent.com/33765493/103731191-694a4e00-4f99-11eb-81d6-fd2cf5b319dc.png)

However, the audio still sounds like it's getting downmixed to mono. Any ideas?

**Comment by aawill** [comment]
Small update - it does appear that this issue might(?) have been resolved in a [recent webrtc update](https://webrtc.googlesource.com/src.git/+/46ea5d7f8206d2d64d6a5596721e422ad3810fb7), is there a way for us to incorporate this into UnityRenderStreaming?

**Comment by karasusan** [comment]
> Small update - it does appear that this issue might(?) have been resolved in a [recent webrtc update](https://webrtc.googlesource.com/src.git/+/46ea5d7f8206d2d64d6a5596721e422ad3810fb7) (or at least made more visible), is there a way for us to incorporate this into UnityRenderStreaming?

Already you more knowledgeable about this topic than me!
This change is very recent and we need to update the library in our package which contains it.
We will get started with this update task next month.

**Comment by aawill** [comment]
Gotcha, I'll keep an eye out for the new update. For now, I've managed to send and receive stereo audio through a data channel.

**Comment by karasusan** [comment]
This change is for supporting multiple audio channel
https://github.com/Unity-Technologies/com.unity.webrtc/pull/440

**Comment by karasusan** [comment]
@aawill 
We supported the stereo channel as the next release version **3.1.0-exp.2**

**Comment by karasusan** [comment]
@aawill
I am going to close this issue.
If you have not solved the issue yet, please notify me.
