### ISSUE TITLE
[BUG] Overlay canvases are not rendered to the WebRTC recipient

### ISSUE THREAD

**Issue by doctorpangloss** [Unity-Technologies/UnityRenderStreaming#375]
**Describe the bug**
Screen space overlay canvases should be supported out of the box. Currently, they are not.

**To Reproduce**
1. Create a screen space overlay canvas.
2. Connect to the render streaming site of your choice.
3. Observe the overlay canvas is not rendered.

**Expected behavior**
Render overlay canvases.

**Environment (please complete the following information):**
 - OS: iOS & Windows 10
 - Browser: Mobile Safari 14
 - Unity Version: 2020.2.1f1
 - Package version: Latest develop at time of writing.

**Additional context**
If it wasn't so difficult to remove motion blur from a canvas, it wouldn't be as big of a deal.

**Comment by karasusan** [comment]
Yes, the package streams a texture, not a screen.
The canvas which selected Screen Space Overlay is not streamed so we need to make the feature that treats a screen as a texture.

**Comment by karasusan** [comment]
@doctorpangloss 
This API might fix the issue.
We will try that.
https://docs.unity3d.com/ScriptReference/ScreenCapture.CaptureScreenshotIntoRenderTexture.html

**Comment by doctorpangloss** [comment]
Yes you should use AsyncGPUReadback no matter what :)

**Comment by pilzinho** [comment]
Are you currently working on that issue and plan to integrate AsyncReadback in Render Streaming? This could be very helpful and gain some performance. That's why we might try to do something like this unless it is being worked on anyway.
I found that this particular file of this repository that we already use some code of provides some good functionality: 
https://github.com/keijiro/KlakNDI/blob/master/Packages/jp.keijiro.klak.ndi/Runtime/Component/NdiSender.cs

**Comment by pilzinho** [comment]
In the meantime we set a camera for all your canvases that need to be streamed to get it to work

**Comment by karasusan** [comment]
@pilzinho @doctorpangloss 
We added `ScreenStreamSender` for fixing this issue. This will be released for the next release in a few days.
Could you review this change meets requirements?
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/562

**Comment by doctorpangloss** [comment]
This looks good and makes sense.

**Comment by pilzinho** [comment]
Hi! Thanks for adding this! Looks good 👍 We basically use almost the same code already but we still have our own modification to allow to downscale the render texture so we can create an HD stream of an application running in 4k.

**Comment by karasusan** [comment]
Very thanks for checking.

> allow to downscale the render texture
That would be very nice. It might be better to support.

**Comment by pilzinho** [comment]
At the moment I have very little time but if this would be interesting for you I could send you our modified code with a description of the changes.
