### ISSUE TITLE
[BUG]Plugins、Scripts、Sounds、TextMesh Pro was broken

### ISSUE THREAD

**Issue by ForeignSone** [Unity-Technologies/UnityRenderStreaming#387]
In my project,some scripts was missing,and Plugins、Scripts、Sounds、TextMesh Pro no longer been a folder！
[image](https://user-images.githubusercontent.com/48970773/105685772-6c4db400-5f31-11eb-9507-5a0129b9693e.png)

**Comment by karasusan** [comment]
These files are the symbolic links.
See https://github.community/t/git-bash-symbolic-links-on-windows/522
