### ISSUE TITLE
[BUG] TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ForeignSone** [Unity-Technologies/UnityRenderStreaming#389]
**Describe the bug**
I'm using RS_LegacyRPSampleSrc Project.When unity connect to http://localhost:8080,there is an error log "TypeError: Cannot read property '0' of undefined".
![image](https://user-images.githubusercontent.com/48970773/105946612-8bb81e80-60a2-11eb-9d1a-23decdc3d310.png)

**Screenshots**
screenshots
![bug](https://user-images.githubusercontent.com/48970773/105936716-2ad31b00-608f-11eb-86ce-81510acbd8bd.png)
![bug](https://user-images.githubusercontent.com/48970773/105936769-41797200-608f-11eb-9eee-5f0dcd615be6.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome]
 - Unity Version [e.g. 2019.4.11]
 - Package version [e.g. 2.1.0]

**Additional context**

![bug](https://user-images.githubusercontent.com/48970773/105937088-d54b3e00-608f-11eb-960d-730eb9ffb4dc.png)

**Comment by karasusan** [comment]
How about WebSocket?

**Comment by ForeignSone** [comment]
> WebSocket怎么样？

There is another problem with this model.
![image](https://user-images.githubusercontent.com/48970773/106081409-d04fc280-6153-11eb-881d-c4a673b2a63d.png)

**Comment by karasusan** [comment]
@ForeignSone 
Please change the `URLSignaling` value on the inspector.
`http://localhost` -> `ws://localhost`

**Comment by kannan-xiao4** [comment]
Hi, @ForeignSone 
I can't reproduce it in my environment. (windows, package version 2.1.1 and 2.2.3)

In addition, develop (version 3.0) adds other bug fixes and refactorings.
Try the `WebBrowserInput` sample in the` RenderStreaming ~ `project in the develop branch.

Please refer this document. https://github.com/Unity-Technologies/UnityRenderStreaming/blob/develop/com.unity.renderstreaming/Documentation~/sample-browserinput.md

Thanks.
