### ISSUE TITLE
[BUG] Chrashes when using https for signaling

### ISSUE THREAD

**Issue by salvolannister** [Unity-Technologies/UnityRenderStreaming#390]
This error occurs every time I try to signal  the localhost url with https, to avoid this I have to signal before with an http URL then stop unity, change it to https and then it works.
Otherwise after playing Unity, it crashes and a pops  a window  that says **"Runtime Error!"**

**To Reproduce**
1. Create a new project with unity and unity render streaming 2.1.1
2. Se the Url Signaling to https in Render Streaming script on Render Streaming GameObject
3. Press Play

**Screenshots**
![immagine](https://user-images.githubusercontent.com/34481854/105980107-bef3b100-6094-11eb-820a-d43feb6b14f0.png)

**Environment (please complete the following information):**
 - OS:  Windows 10
 - Unity Version:  2019.4.11f1
 - Package version:  2.1.1-preview

**Comment by karasusan** [comment]
Could you try the latest version of the package `2.2.2-preview`?

**Comment by salvolannister** [comment]
So i did some tryes: 

Empty project with 2.2.2-preview and https ---> No crush
Scene with a model, 2.2.2 preview and https --> Crush
Same as last but starting before with http and then switching to https --> works

**Comment by karasusan** [comment]
I would like to check the log file when crashing. Could you have a log?

**Comment by salvolannister** [comment]
Here's the log, I deleted it and then I just opened Unity editor and clicked on play (using as url https:// )so it should be easier to read

[Editor.log](https://github.com/Unity-Technologies/UnityRenderStreaming/files/5917399/Editor.log)

**Comment by karasusan** [comment]
There is no clue in this log, unfortunately.
Could you try the websocket?

**Comment by salvolannister** [comment]
I enabled the other RenderStreamingCamera and now I don't have this problem anymore

**Comment by kannan-xiao4** [comment]
Hi, @salvolannister.
I check this bug, but I can't reproduce it.

Can I close this issue?

thanks
