### ISSUE TITLE
Unity RenderStreaming  error after executing

### ISSUE THREAD

**Issue by Jucrox** [Unity-Technologies/UnityRenderStreaming#416]
I run the sample URP on Unity editor but when I write the URL in Chrome, Microsoft  Edge or Firefox after 4 or 5 seconds I get this error on Unity console:
Network Error: Failed to set remote answer sdp: Called in wrong state: kStable
UnityEngine.Debug:LogError(Object)
Unity.RenderStreaming.<OnAnswer>d__41:MoveNext() (at Assets/Scripts/RenderStreaming.cs:380)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

And the streaming is paused because Unity stop the execution

OS: Windows 10
Unity Version: 2019.4.14f1
![RenderS](https://user-images.githubusercontent.com/49349921/108259888-a1fc4c00-712f-11eb-9879-49dd51ad6e33.PNG)

**Comment by karasusan** [comment]
@Jucrox
How about the 3.0.1-preview version?
