### ISSUE TITLE
[BUG] Clients streaming incorrect camera views

### ISSUE THREAD

**Issue by cvachha** [Unity-Technologies/UnityRenderStreaming#435]
**Describe the bug**
The first two clients perform properly, but the third client is showing a previous render streaming camera view. I am still able to control the 3rd camera properly, but the 3rd client does not display the 3rd camera's view. This occurs in the software encoding as well.

**To Reproduce**
1. Set up example scene
2. Duplicate one of the streaming cameras
3. Assign UI controller to the new duplicated camera's UI
4. Run webserver and play the scene
5. Open and start 3 new clients

**Expected behavior**
I expect that each client should show its corresponding camera view. However, the third client is showing the camera view of the 2nd camera. The third client is able to control the 3rd camera properly, but it is displaying the incorrect camera view.

**Screenshots**
The two camera views:
![client_camera_error](https://user-images.githubusercontent.com/9502341/109658786-d30b5200-7b1b-11eb-98a0-7528b00d5394.PNG)

A video overview of the error:
https://user-images.githubusercontent.com/9502341/109660017-38137780-7b1d-11eb-925a-ecf330a81bc7.mp4

**Environment:**
 - OS: Windows
 - Browser: Chrome
 - Unity Version [e.g. 2019.4.17]
 - Package version [e.g. 2.2.2-preview]

**Additional context**
It seems like after the first two render streaming cameras, the following clients do not display the correct camera views for following and additional cameras.

**Comment by tkbala** [comment]
I am facing the same issue. What is the best way to stream textures from different cameras that are places in a scene? and how do we 1-1 map each of those streams to a separate client?

**Comment by karasusan** [comment]
@tkbala @cvachha 

Hi,
This behavior you reported is operating as intended. However, I am understanding what you are saying.
Right now, You need to implement the web client yourself to achieve what you want.

Many people argue about this topic, so we are considering making a new sample to satisfy your requests.

**Comment by tkbala** [comment]
At a higher level, What would the web client need to do, to uniquely access a render streaming camera? Is there anything we need to do when creating the cameras in Unity?

**Comment by karasusan** [comment]
@tkbala 
It is easy to create the cameras in Unity (but be careful about the graphics performance). 
Generally, we use a prefab for the camera. instantiate the prefab dynamically when receiving the signaling message from browsers.

**Comment by karasusan** [comment]
@tkbala @cvachha
Sorry for your waiting.
I created a multiplay sample. We are testing this sample and going to release next month.

**Comment by karasusan** [comment]
@tkbala @cvachha
Hi, we have released the latest version. Could you try that?
