### ISSUE TITLE
[BUG] v3.0.1 WebBrowserInput Scene iOS safari show black screen

### ISSUE THREAD

**Issue by Piler-Tam** [Unity-Technologies/UnityRenderStreaming#440]
**Describe the bug**
iOS safari show black screen, already use https and turn off firewalls

works without problem on my Windows Chrome.

**To Reproduce**
1. run https server
2. run WebBrowserInput scene
3. enter the website using iOS safari
4. unity show no error, server side show no error but safari show black screen

**Expected behavior**
safari show streaming from unity

**Screenshots**
![image](https://user-images.githubusercontent.com/31006388/109905210-68a01080-7cd9-11eb-970e-a39a221c99a7.png)

**Environment**
 - OS: iOS 14.4
 - Browser Safari
 - Unity Version 2019.4.20f1
 - Package version 3.0.1

**Comment by karasusan** [comment]
Can I see a browser log?

**Comment by Piler-Tam** [comment]
> @Piler-Tam
> Can I see a browser log?

sorry, I don't have any Mac machine now.
But it works with WebApp v2.2.2 even using http

**Comment by karasusan** [comment]
@Piler-Tam
Have you solved yourself? I would like to know the status of the issue.
Thanks.

**Comment by Piler-Tam** [comment]
> @Piler-Tam
> Have you solved it yourself? I would like to know the status of the issue.
> Thanks.

It still not work if I use the WebApp from v 3.0.1,  it works with WebApp v2.2.2 .

**Comment by karasusan** [comment]
@Piler-Tam

I am testing Unity Render Streaming with iOS Safari and Windows but it works. 

In my side, we have not been seen the log `Already answered this connectionId ...`.
So the signaling process causes this issue.

Can I see the signaling server log?

**Comment by karasusan** [comment]
@Piler-Tam 
Hi, I am waiting for your response. Thanks.

**Comment by doctorpangloss** [comment]
I think this might be related to having Low battery mode enabled on iOS.

**Comment by doctorpangloss** [comment]
#376
