### ISSUE TITLE
How can I improve the video quality when running locally at 1920*1080 that looking like a Mosaic in the browser

### ISSUE THREAD

**Issue by Evil-li** [Unity-Technologies/UnityRenderStreaming#443]
when running locally at 1920*1080 that looking like a Mosaic in the browser

**Comment by h-rlpl** [comment]
@Evil-li I have similar issue. Does the following works for you ?
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/446#issuecomment-796488416

**Comment by Evil-li** [comment]
no，i dontkhow where i can use it

**Comment by pilzinho** [comment]
If you are still trying to get ChangeVideoParameters to work in the latest version have a look at my answer in #453 if it works for you

**Comment by kannan-xiao4** [comment]
memo: URS-330

related issues
#453
#446
#611
