### ISSUE TITLE
[REQUEST] Is there a way make the browser input work using Input.GetKey()/Input.GetMouseButton()?

### ISSUE THREAD

**Issue by Piler-Tam** [Unity-Technologies/UnityRenderStreaming#447]
**Is your feature request related to a problem? Please describe.**
To use render streaming for a old unity project. I am trying not to modified the original code for input such as Input.GetKey(), Input.GetMouseButton(). 

**Describe the solution you'd like**
Can I make the browser input work using that? Can I map the browser input(i.e. RemoteInput.Keyboard.aKey) to the old Input Manager(i.e. Axes: Horizontal / Vertical)?

**Comment by karasusan** [comment]
Unity Render Streaming uses `InputSystem` package.
This document describes a migration from the old input system to new one. 😅 
https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/manual/Migration.html

**Comment by karasusan** [comment]
@Piler-Tam
Hi, do you have any questions?
