### ISSUE TITLE
[BUG] 3.0.1 - Linux - No input & crashes on attempted stream

### ISSUE THREAD

**Issue by bramford** [Unity-Technologies/UnityRenderStreaming#449]
**Description**
When attempting to run the URS sample v3.0.1-preview on a fresh Universal Render Pipeline project, it:
1. Does not accept any input and appears to be frozen.
2. Crashes with `Segmentation fault` when attempting to stream from the browser

**To Reproduce**
1. On a Debian or Ubuntu GNU/Linux machine
2. Create a new Universal Render Pipeline project
3. Install URS 3.0.1-preview and import the Example.
4. Open the scene `WebBrowserInput.unity`
5. Configure RenderStreaming element to use my own webserver (in my case, `ws://urs.derp.tech`)
6. Build & run (i.e. start the player)
7. Start the video player from the browser

**Expected behavior**
The game should run, input should work (both in the local game window and via webRTC) and the streaming data should flow to/from the browser.
Note: In URS 2.2.2 everything works perfectly on the same machine/environment.

**Screenshots & Logs**
[Player.log](https://pastebin.com/zi4WTQde)
[Screenshot](https://imgur.com/a/dSQwNvy) 

**Environment:**
 - OS: Debian Testing/Unstable
 - Linux Kernel:  5.10.0-3-amd64
 - Browser: Firefox 86.0
 - Unity: 2019.4.20f1
 - URS: 3.0.1-preview

**Comment by karasusan** [comment]
@bramford
Hi, 
First, Debian is not recommended environment to run Unity.
You can use Ubuntu20.04 instead.
https://docs.unity3d.com/Manual/system-requirements.html

I would like to know that your project works correctly using Unity Editor on Ubuntu20.04.
And it might be caused by the hardware encoder. I recommend checking using the software encoder at first.

**Comment by karasusan** [comment]
Hi, Do you have any updates?

**Comment by bramford** [comment]
No @karasusan thanks for your help. I won't bother testing this again as we've moved to a different stack.
