### ISSUE TITLE
Poor quality over good connection!

### ISSUE THREAD

**Issue by ZeoWorks** [Unity-Technologies/UnityRenderStreaming#450]
Hi!
I am using a RTX 2060 (hardware encoding) to stream a camera with 3.0.1.

The stream bitrate/bandwidth is quite low.  It stays at around 2-3mbps download.

I noticed that you can no longer edit the description to increase the max bit-rate;
` _desc.sdp = Regex.Replace(_desc.sdp, pattern, "$1;x-google-start-bitrate="+((int)((float)maxBitrate/2)).ToString()+";x-google-max-bitrate="+maxBitrate.ToString()+"\r\n");  `

How do you increase the bitrate in this latest build?

I am experiencing a lot of artifecting .etc that was non-existent in previous builds.

I'm hoping to stick with 3.x.x as it's the best build yet. :)

Thanks!

**Comment by karasusan** [comment]
Is this the same issue?
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/446

**Comment by ZeoWorks** [comment]
Hi, that's correct yes.  It's happening in 3.0.1.
I believe this is due to the bandwidth usage.  I tested an older version earlier (2.x) and adjusted the bandwidth to 15mbps at 1080p and the issue disappeared.  In 3.0.x, the bandwidth sits at around 2-3mbps.

**Comment by karasusan** [comment]
Are you expecting the C# API that makes editing SDP for adjusting bandwidth?
Certainly, it might be useful.

**Comment by ZeoWorks** [comment]
> Are you expecting the C# API that makes editing SDP for adjusting bandwidth?
> Certainly, it might be useful.

Thank you, yes this is correct. 
This would be great for streaming over the internet as users will be able to adjust the bandwidth usage for the best quality based on their upload/download speeds.

I've redownloaded 2.2 to use "ChangeVideoParameters" in the meantime, it works great.
In older versions <2.1 you have to change the description string (mentioned in the first message).

Thank you for your help, this would be terrific!

**Comment by pilzinho** [comment]
Have you managed to use ChangeVideoParameters in the newest version? If not you can try if my answer in #453 works for you

**Comment by karasusan** [comment]
memo: URS-330

**Comment by LiangHuangBC** [comment]
This is still buggy.
