### ISSUE TITLE
[BUG]The type or namespace name 'ReceiveVideoViewer' could not be found

### ISSUE THREAD

**Issue by Zxinwei** [Unity-Technologies/UnityRenderStreaming#452]
![image](https://user-images.githubusercontent.com/35294149/111947807-16ece800-8b19-11eb-9afc-9d413aaa1c95.png)
Build WebGl errors
unity2019.4.10

**Comment by karasusan** [comment]
Hi, WebGL platform is not supported.

**Comment by corona89** [comment]
I got a same error on PC build.
![renderstreaming](https://user-images.githubusercontent.com/8100875/116524569-7f966400-a912-11eb-9b3e-3da5eebbb85c.JPG)

**Comment by mykr13A** [comment]
I get the same error, how did you fix it?

**Comment by karasusan** [comment]
Currently, WebGL platform is not supported.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/470

**Comment by mykr13A** [comment]
I don't use WebGL platform, I use Windows and I get the same error!

**Comment by karasusan** [comment]
@mykr13A
What version of the package are you using?

**Comment by mykr13A** [comment]
Version 3.0.1-preview

**Comment by mykr13A** [comment]
Any update about the error?

**Comment by karasusan** [comment]
Could you try the version 3.1.0-exp.1?

**Comment by mykr13A** [comment]
When I install the package of version 3.1.0-exp.1 , I get this error:
 "Library\PackageCache\com.unity.webrtc@2.4.0-exp.3\Editor\BuildProcessor.cs(128,46): error CS0117: 'BuildPipeline' does not contain a definition for 'GetBuildTargetName' "

**Comment by karasusan** [comment]
What Unity version are you using?
I cannot reproduce the issue as you say.
![image](https://user-images.githubusercontent.com/1132081/134851194-5abfcea9-4ebd-4e4e-a16c-32e1b0f469c2.png)

**Comment by mykr13A** [comment]
The Unity version is 2019.4.14f1 and when I build the project, it shows this erro
![github](https://user-images.githubusercontent.com/33093860/134878335-4c5941b5-291c-4c0d-916e-e7d4ddaf87d8.png)
r

**Comment by mykr13A** [comment]
The Unity version is 2019.4.14f1 and when I build the project , it show this error
![github](https://user-images.githubusercontent.com/33093860/134878685-7630bd96-e910-41c5-8b83-d9632047a276.png)
r

**Comment by karasusan** [comment]
@mykr13A 
The error might be caused by the Unity version.
Could you try the latest version 2019.4.30f1?

**Comment by mykr13A** [comment]
Now I get this error
![github](https://user-images.githubusercontent.com/33093860/134888307-39a6c03f-b298-4318-92be-a47928afa654.png)

**Comment by karasusan** [comment]
@mykr13A
@Zxinwei

Have your issues been solved? If so, please close the ticket.

**Comment by FlyBrid1** [comment]
@mykr13A ！ @Zxinwei  Now I switch my  Render-Streaming-project from windows platform to WebGL platform,during this time，when I run the project,it hava no compile erros。But when I  attemp to build the project to WebGL,click the Build,the console shows many error CS0246,which messages is "The type or namespace "SignalingManager" could not be found (are you missing a using directive or an assembly reference) "

**Comment by FlyBrid1** [comment]
> 

Could you show me you solution to the error cs2046
