### ISSUE TITLE
[BUG] No setting RTCtpEncodingParameters

### ISSUE THREAD

**Issue by Evil-li** [Unity-Technologies/UnityRenderStreaming#453]
it's unuseful when i use 'ChangeVideoParameters' method. because the length of 'sender.GetParameters()'.

How can i set RTCRtpSendParameters?

**Comment by karasusan** [comment]
We have similar requests so will work on it in near future.
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/450

**Comment by Evil-li** [comment]
thank you

**Comment by pilzinho** [comment]
If you are still trying to get this to work I made a [forum post](https://forum.unity.com/threads/webrtc-renderstreaming-code-improvements.1145162/#post-7351925) where I shared some code changes I made. Also how to use ChangeVideoParameters.
The problem for me was that the parameters are not immediately available and therefore the array is empty. I just added a small delay before setting the parameters after the new sender was created and set. Something like this:

` cameraStreamer.OnStartedStream += id => { StartCoroutine(HandleStreamStarted(cameraStreamer, id)); };`

and

```        
private IEnumerator HandleStreamStarted(CameraStreamer cameraStreamer, string connectionId)
{
        // The parameters are not available right away so wait for them
        yield return new WaitForEndOfFrame();
        Debug.Log($"WebRTC stream connected: {cameraStreamer.name} has {cameraStreamer.Senders.Count} active connections");
        cameraStreamer.ChangeVideoParameters(connectionId, maxBitrate, encodingFps);
}
```

**Comment by karasusan** [comment]
memo: URS-330
