### ISSUE TITLE
[BUG] Loss of stream on the test scene

### ISSUE THREAD

**Issue by flchazelas** [Unity-Technologies/UnityRenderStreaming#456]
On your test scene "WebBrowserInput", I do a tutorial at this link link : https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.0/manual/tutorial.html to the 3.0.1 version of render streaming.
But after run the scene and the webserver included in package I test on my webBrowser and the video stream appears once in two. Or the second screen stream is off.

![Problem 2](https://user-images.githubusercontent.com/44674852/113891653-8d4e4300-97c5-11eb-9f2b-ab9c54def750.PNG)

I have these errors in my  consol in Unity : 

![Problem 1](https://user-images.githubusercontent.com/44674852/113891716-a22ad680-97c5-11eb-8d80-dea2128b5ced.PNG)

I just followed your tutorial and I don't know if I need to configurate something else?

**To Reproduce**
1. Install "Render Streaming" package 3.0.1 in Unity 19.4.23 version
2. Just follow your tutorial
3. Launch"WebBrowserInput Stream" scene in Unity
4. Execute webserver app
5. Go to localhost and launch videoplayer sample

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser : firefox
 - Unity Version : 2019.4.23f1
 - Package version : 3.0.1-preview and 2.2.2-preview

**Comment by karasusan** [comment]
@flchazelas 
Could you try the latest version? And I want the video recording the issue if you reproduce it.
