### ISSUE TITLE
RenderStreaming namespace not linking correctly in Visual Studio

### ISSUE THREAD

**Issue by gkapellmann** [Unity-Technologies/UnityRenderStreaming#459]
I created an empty project and downloaded the package from "com.unity.renderstreaming". 

I have tried in Unity 2020 and unity 2019, with the same result. 

![image](https://user-images.githubusercontent.com/7535220/114416034-8bfb8c80-9bb0-11eb-9cae-e29437e7f17e.png)

I have tried regenerating the project files, and deleting the library. 

There is no way I can get Monobehaviour to get recognized in the project. 

Any ideas?

**Comment by krisrok** [comment]
This is not related to this project. It's relatively new and hidden feature:

Go to Preferences->External Tools->Generate .csproj file for:
And then tick the box corresponding to the way how you acquired the package. From your description I guess it'd be covered by "Git packages".

**Comment by kannan-xiao4** [comment]
Thank you for following @krisrok 

@gkapellmann
This issue is closed because it not related our project.
Please check the settings of Visual Studio.
