### ISSUE TITLE
[BUG] Unable to find com.unity.webrtc.tgz download location

### ISSUE THREAD

**Issue by little-snow-fox** [Unity-Technologies/UnityRenderStreaming#460]
Hello, the help document prompts me to download the **com.unity.webrtc.tgz** file from GitHub, but I can't find it in the GitHub warehouse. Could you please tell me where it is?
<img width="713" alt="截屏2021-04-13下午4 01 26" src="https://user-images.githubusercontent.com/23468639/114518024-82862900-9c71-11eb-940c-e47bb6b2c1a0.png">
<img width="1660" alt="截屏2021-04-13下午4 03 46" src="https://user-images.githubusercontent.com/23468639/114518344-d85ad100-9c71-11eb-91a6-b93a01623464.png">

**Comment by karasusan** [comment]
This document might be old. Please see this document to start it.
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.0/manual/samples.html

**Comment by little-snow-fox** [comment]
thank~
