### ISSUE TITLE
[REQUEST] Whether to support multi-person collaboration？

### ISSUE THREAD

**Issue by gushenjie** [Unity-Technologies/UnityRenderStreaming#461]
Hello, I have used the video-player sample and found that only one person can collaborate. Is there a switch to allow multiple people to collaborate?

**Comment by gushenjie** [comment]
Has the function been implemented？

**Comment by karasusan** [comment]
We could make a sample that demonstrating the usage for multi-players near future.
Related issue
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/435#issuecomment-789356441

**Comment by gushenjie** [comment]
> We could make a sample that demonstrating the usage for multi-players near future.
> Related issue
> [#435 (comment)](https://github.com/Unity-Technologies/UnityRenderStreaming/issues/435#issuecomment-789356441)

thank u

**Comment by karasusan** [comment]
Please check the `Multiplay` sample when we will release the new version.

**Comment by teexiii** [comment]
I believe this ticket should be closed, since the `Multiplay` example is working as expected 😄

**Comment by karasusan** [comment]
@gushenjie
Already published the new version for solving the issue, so I am closing this.
