### ISSUE TITLE
[REQUEST] Is there any video demo about arfounctaion demo?

### ISSUE THREAD

**Issue by chaoslife** [Unity-Technologies/UnityRenderStreaming#463]
We are very interested in using URS and ARFoundation related applications. Is there any video or document introduction?
I can't run using  arfoundation examples

**Comment by karasusan** [comment]
You can see the document here.
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.0/manual/sample-arfoundation.html

**Comment by chaoslife** [comment]
thanks a lot

**Comment by karasusan** [comment]
@chaoslife
Can I close this issue? Thanks.
