### ISSUE TITLE
[BUG] Spaces in Stream GameObject name causes error

### ISSUE THREAD

**Issue by mksbamford** [Unity-Technologies/UnityRenderStreaming#464]
If the name of a gameobject with a Streamer component contains a space e.g. "Render Streaming Camera", this will result in the following error:
RTCErrorException: Expected format "msid:<identifier>[ <appdata>]".

This is because the [ <appdata>] part of this is set to the gameobject name e.g. "a=msid:xxx-xxx-xxx-xxx-xxx Render Streaming Camera"

**Comment by karasusan** [comment]
@mksbamford
I got it.
I understood that it is not good to use the gameobject's name for that.
I will change the logic for naming

**Comment by kannan-xiao4** [comment]
@mksbamford 
We already fixed for this issue.
Thanks for reporting.
