### ISSUE TITLE
How to link gstreamer webrtc to unity render streaming "receiver" sample ?

### ISSUE THREAD

**Issue by bharathraja** [Unity-Technologies/UnityRenderStreaming#465]
I tried linking gstreamer webtrcbin "sendrecv" demo to the unity render streamer "receiver" sample. I can share sdp, candidates. But cannot setup peer connection from the unity to gstreamer. Can any sample/plugin/documentation be added to custom change the receiver to load videos from gstreamer webrtcbin or from other sources ?

**Comment by bharathraja** [comment]
solved by creating custom websocket server to connect unity and gstreamer webrtc.

**Comment by dustinkerstein** [comment]
@bharathraja, would you be able to share your solution? I'm looking to accomplish the same thing. Thanks!

**Comment by dustinkerstein** [comment]
FYI, I posted this question on the Unity forum and GStreamer repo:

https://forum.unity.com/threads/gstreamer-webrtc-signaling-compatibility.1165895/
https://gitlab.freedesktop.org/gstreamer/gst-examples/-/issues/52

**Comment by bharathraja** [comment]
@dustinkerstein, some pointers to check to make sure that the link between the unity and gstreamer works. It is tricky by the way.I used sample video recieve from unity webrtc 2.4 and send_recv sample from gstreamer webrtc.

1. make sure you follow the order of call between both sides (handle all errors/calls):
	- gstreamer side
		- connect, register to server
		- setup call
		- start pipleline
		- send offer
		- ice gathering state change to complete
		- recieve answer
		- ice gathering state change to gathering
		- 

	- client side (browser-js/UNITY Webrtc)
		- register with server, recieve HELLO
		- wait for call
		- recieve offer
		- create RTCPeerConnection
		- created peer connection for call, waiting for SDP
		- recieve candidates
		- incoming stream
		- remote sdp set
		- got sdp offer
		- recieved candidates
		- adding local stream
		- got local stream, creating answer
		- got local descrition
		- sending sdp answer
2. Rewrite the Unity webserver with a simple echo server (for initial testing)
3. Filter the messages sent from self
4. Open all firewall
5. Disable tls, there is version miss-match between gstreamer and unity c# tls, or make sure you follow same tls standard
6. You have to rewrite handling message parsing on both the sides
7. By the way, there is a bug in unity side, give time delay between ice-candidate sharing offer/answer , -> https://github.com/Unity-Technologies/com.unity.webrtc/issues/347
8. There is also bug in the release of gstreamer, use latest develop verion. 
-> git revert !2260 commit in the gst-plugin-bad
-> git revert !2260 commit in the gst-plugin-bad
-> replace conflicting with older version files
(use gst logging for debugging from gstreamer side )

If you can make sure of all the above, you can establish connection between unity webrtc and gstreamer.

**Comment by dustinkerstein** [comment]
Fantastic @bharathraja, thanks! That will help a ton. If you're able to, it would be awesome to see some of that code directly.

**Comment by bharathraja** [comment]
@dustinkerstein, please do try it out yourself. I am not in the position to be able to share the code. Thanks.

**Comment by dustinkerstein** [comment]
Kk, no worries. Thanks again.

**Comment by bayvr** [comment]
@dustinkerstein Have you managed to solve the problem? I modifed the VideoReceiveSample but no success. I have set and exhchanged the proper offer+answer+ice candidates (on both sides) but the OnIceConnectionChange callback is never fired in Unity (the state is always new) so basically there's is some problem with the ice connection and I cannot figure out what can it be. Basically it should work the same as the gstreamer browser client but it does not.

I can share my code if that helps.

**Comment by dustinkerstein** [comment]
@bayvr, unfortunately I didn't end up getting too far with this. I ended up with a mjpeg solution that is functional, but not nearly as efficient as WebRTC. Sorry I couldn't be of any help. I would definitely still love to get WebRTC + Gstreamer working. Please do let me know if you get it working.

**Comment by bayvr** [comment]
I managed to solve the problem. The problem was with the 9th entry on @bharathraja's list. I found an [other topic](https://github.com/microsoft/MixedReality-WebRTC/issues/653) which explains and solves the issue (the key is in line 198).

I use the gstreamer signalling solution so I needed a websocket client for Unity. I chose [WebsocketSharp](https://github.com/sta/websocket-sharp). Also as the signalling uses JSON so a handling library is needed for it. I used [Json.NET](https://www.newtonsoft.com/json).

Set your server's address at line 219 and you peer id below. Be aware that this client always accepts the server's certificate, you have to implement custom certificate handling for yourself (see line 226).

[VideoReceiveSample2.txt](https://github.com/Unity-Technologies/UnityRenderStreaming/files/7641068/VideoReceiveSample2.txt)

**Comment by dustinkerstein** [comment]
Nice! Glad to hear you got it working. I'll have to give it another shot later this week. Is the VideoReieveSample2.txt your working code?

**Comment by bayvr** [comment]
Yes, and sorry for not clarifying this up. And the lines I mentioned are referencing to my file.

The server code is untouched except the pipeline (you need to use vp8 encoding as currently Unity does not support h264 decoding.) If it does not work let me know it and I will help again.

**Comment by dustinkerstein** [comment]
Ok cool that you got it working with the default server code. 

Unity should definitely support h264, but it will depend on your particular system. I was able to get hardware h264 decoding working on Android in Unity using the built-in video player API. What platform are you using?

**Comment by bharathraja** [comment]
@dustinkerstein and @bayvr, as far my testing, only vp8 software decoding is available for the android platform. h264, h265 hardware decoding is not currently supported in android platform.

**Comment by bharathraja** [comment]
@dustinkerstein , @bayvr , currently only software decoding vp8 is supported. hardware decoding is not supported. check the documentation. 
[documentation - video streaming](https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/videostreaming.html)

I am also waiting for the addition of hardware decoding. check this issue.
[unity webrtc not sending answer for recieved offer for H265/VP9 hardware decoding in android platform !](https://github.com/Unity-Technologies/com.unity.webrtc/issues/474)

**Comment by dustinkerstein** [comment]
Bummer. Hardware decoding is definitely a requirement for my use-case unfortunately. I'll stay in tune with developments along that front. Thanks.

**Comment by bayvr** [comment]
A bit correction: there's no h264 software decoder yet, so on Windows and Linux it's not possible to implement it, but devices which support h264 hardware encoding (like Android, iOS) are fine (if I understand it correctly).

But VP8 (as @bharathraja said) and VP9 (tested!) are supported on the desktop platforms.

And yeah, the h264 decoder is still being developed, see these issues: [1](https://github.com/Unity-Technologies/com.unity.webrtc/issues/272), [2](https://github.com/Unity-Technologies/com.unity.webrtc/issues/454), [3](https://github.com/Unity-Technologies/com.unity.webrtc/issues/391). It's one of the entries in the next release's [milestone](https://github.com/Unity-Technologies/com.unity.webrtc/milestone/17).
