### ISSUE TITLE
[BUG] UnityRenderStreaming Example

### ISSUE THREAD

**Issue by Eelam** [Unity-Technologies/UnityRenderStreaming#488]
The ‘com.unity.renderstreaming@3.1.0-exp.1’ did not work.
The ‘com.unity.renderstreaming’ is download the Version 3.0.1-preview - March 04, 2021. In this, ‘WebBrowserInput’ works. However, ‘Bidirectional’ did not work. I tested these using Unity 2020.3.11f1 on Windows.
How do I get the latest examples?
Thanks,

**Comment by karasusan** [comment]
@Eelam 
We are testing the latest version and will release it soon.
