### ISSUE TITLE
[REQUEST] Change codecs?

### ISSUE THREAD

**Issue by ZeoWorks** [Unity-Technologies/UnityRenderStreaming#504]
Hello!
I was wondering if the ability to change what codec to encode is supported for unity render streaming?
It'll be great to switch between VP8 to VP9 for non-hardware encoding. 

Thanks!

**Comment by karasusan** [comment]
Thanks.

Related issue.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/249

**Comment by ZeoWorks** [comment]
Thanks, in addition; will it be possible to have software/cpu encoding run on a separate thread and not the main unity thread?
(As it really hinders the performance & frame rate of in-game)

**Comment by karasusan** [comment]
memo: URS-106
