### ISSUE TITLE
[BUG] Frame rate drops after reconnecting in 3.x onwards

### ISSUE THREAD

**Issue by ZeoWorks** [Unity-Technologies/UnityRenderStreaming#506]
Hello Karasusan, hope you're doing well. :)

I've been experimenting with renderstreaming 3.1 & 3.0, 
When a user disconnects from the video sample and reconnects; the actual ingame frame rate drops and will continue to drop each time the user disconnects and reconnects.
This is when using software encoding, the CPU percent keeps rising and rising.

Thanks.

**Comment by karasusan** [comment]
@ZeoWorks 
Thanks.
I will fix the issue next month.

**Comment by karasusan** [comment]
Is it the same issue #462 ?

**Comment by karasusan** [comment]
memo: URS-316

**Comment by karasusan** [comment]
@ZeoWorks
The pull request is merged and you can check it on the **develop** branch.
Thanks.
