### ISSUE TITLE
[QUESTION]Can I use this with Hololens2?

### ISSUE THREAD

**Issue by Sakitakazawa** [Unity-Technologies/UnityRenderStreaming#508]
Hi,
I want to display real time video from Hololens2 on browser(or unity editor) ,
and send x and y information where the mouse clicked on browser(or unity editor) to Hololens2.

Is it possible??

**Comment by karasusan** [comment]
UWP platform is not supported yet.
Users discussed the same topic in this thread.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/15

**Comment by kannan-xiao4** [comment]
@Sakitakazawa Any question? If no question, we will close this issue.
