### ISSUE TITLE
[QUESTION]  How to render individually

### ISSUE THREAD

**Issue by ctc-furukawa-shun** [Unity-Technologies/UnityRenderStreaming#509]
1アプリに複数ユーザーを収容したいと考えています。
各ユーザーはカメラを保持しており、ブラウザからオブジェクトを操作した際、
その操作が他のユーザーに干渉しないようにする方法はありますでしょうか？
あれば、その方法を教えていただけますでしょうか？

I want to accommodate multiple users in one app.
Each user holds a camera and when manipulating an object from a browser
Is there a way to prevent that operation from interfering with other users?
If so, could you tell me how to do that?

**Comment by karasusan** [comment]
Same issue #461

**Comment by karasusan** [comment]
@ctc-furukawa-shun
We made the "Multiplay" sample to demonstrate multi-person game using this package.
Please check it and report your impression. Thanks
