### ISSUE TITLE
[Question] Render multiple streams over a headless server

### ISSUE THREAD

**Issue by xavierpuigf** [Unity-Technologies/UnityRenderStreaming#510]
Hi, I need to be able to render multiple games stored in a headless server that I can connect via a web. For every game I have up to two video streaming tracks, as well as up to two input streams to control characters in the game. 

One issue is that, when I start running more than 2 games in the server, the video streaming stops working, even though the input stream still allows me to control characters. If I run multiple games locally this issue does not arise, and I can stream multiple games at the same time. I wanted to check if there is any way I can increase the number of concurrent games, and what would be the best way to do so. I currently have a machine with 8 GeForce GTX 1080 gpus, but I still cannot stream more than 3 tracks at the same time.

From [this documentation ](https://docs.unity3d.com/Packages/com.unity.webrtc@2.0/manual/en/videostreaming.html) it seems like hardware encoding limits the number of concurrent streams, but software encoding does not seem to work on a headless server. If it is not possible to have multiple streams in a given server, would it make sense to simply send a static image from a camera every time a user takes an action? What would be the best approach?

**Comment by karasusan** [comment]
Is this the same issue?
https://forum.unity.com/threads/unity-render-streaming-introduction-faq.742481/page-15#post-7311016

**Comment by xavierpuigf** [comment]
Yes, it is that issue. Is it possible to use the software encoder on a headless server? I can run the hardware encoder (with limitations on the maximum number of streams) but I cannot get to work the software encoder.

Thank you

**Comment by kannan-xiao4** [comment]
@xavierpuigf 
Sorry for the late reply.
Yes, you can also do multiple streams with a software encoder.
But, Server build is intended for network games, etc., and graphics and sound functions cannot be used.
Unity needs to recognize the display to use the graphics features.

**Comment by kannan-xiao4** [comment]
@xavierpuigf
We will close this issue if you don't have any updates.

**Comment by karasusan** [comment]
Thank you for your response.
First,  you said that software encoding does not seem to work on a headless server. Could you let me know more detail?
Second, NVIDIA Geforce GPU has restriction of number of encoder, so you need to use other GPUs like Quadro series.

**Comment by custstu** [comment]
@xavierpuigf Could you tee me how to render multiple games  in a headless server through render streaming?

**Comment by karasusan** [comment]
@xavierpuigf
Any update? Thanks.

**Comment by xiasun** [comment]
@xavierpuigf you can use this unofficial [patch](https://github.com/keylase/nvidia-patch) to avoid the restriction of max concurrency number.

BTW, how did you run a built game on headless server? I tried to run `xxx.x86_64 -batchmode`, it worked on ubuntu desktop, but failed in container and remote server.

**Comment by fegarza7** [comment]
I'm trying to do the same, but I can't get it to work on a headless server.. any way to make it work?

**Comment by Bullseye25** [comment]
Hi Everyone,
I am having an issue with the headless server. I have tried making a build targeting linux server and windows server, but when I try xxx.x86_64 -batchmode, I am getting a black screen on my WebRTC webpage. can any assist please. 

Thank you!

**Comment by deprofundiis** [comment]
+1 on this one!
