### ISSUE TITLE
[REQUEST]Multiplayer collaboration

### ISSUE THREAD

**Issue by gushenjie** [Unity-Technologies/UnityRenderStreaming#512]
Does it support multi-person control of the main camera? Currently using the demo project, there will be two cameras. The first person who enters will control the main camera, and the second person will control the secondary stream after entering. The third person will not be able to control any camera after entering. Up.

**Comment by karasusan** [comment]
Same issue #461

**Comment by karasusan** [comment]
We made a **Multiplay** sample. We will release it for a new package version **3.1.0-exp.2**.
