### ISSUE TITLE
[BUG] webrtc2.4.0-exp.3  BuildPipeline unityrenderstream3.1.0

### ISSUE THREAD

**Issue by gushenjie** [Unity-Technologies/UnityRenderStreaming#513]
Library\PackageCache\com.unity.webrtc@2.4.0-exp.3\Editor\BuildProcessor.cs(128,46): error CS0117: 'BuildPipeline' does not contain a definition for 'GetBuildTargetName'

**Comment by gushenjie** [comment]
unity version 2019.4.9

**Comment by karasusan** [comment]
@gushenjie
Have you tried version 2019.4.28?
I could not reproduce it.

**Comment by gushenjie** [comment]
2019.4.28 version solved
