### ISSUE TITLE
[QUESTION] Missing browser demo for InputSystem?

### ISSUE THREAD

**Issue by krisrok** [Unity-Technologies/UnityRenderStreaming#516]
Hi there,

I'm currently trying to use the new InputSystem (https://github.com/Unity-Technologies/UnityRenderStreaming/pull/392) and I see the implementation on the Unity-side but cannot find the implementation of the protocol on the browser-side. 

Does it exist yet? Or did you only test Unity-Unity connections?

**Comment by karasusan** [comment]
@krisrok 
Do you mean that you want to use it for WebGL?

**Comment by krisrok** [comment]
No, I was looking for a more complete example for input events coming from the browser all the way to the InputSystem. If I remember correctly (it's been over a month since I last worked with this package) I think all of it is in fact in there but it's a bit hard to piece together in its current state.

**Comment by karasusan** [comment]
I guess the sample you said is *WebBrowerInput* sample scene.

**Comment by karasusan** [comment]
@krisrok
Hi, we implemented the feature that controlling input using InputSystem on browsers.
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/574

**Comment by karasusan** [comment]
@krisrok
We already released the latest version, please reopen it if you have any questions about the issue.
Thanks.
