### ISSUE TITLE
[BUG] Resolutions higher than 1080p crash with hardware encoding.

### ISSUE THREAD

**Issue by ZeoWorks** [Unity-Technologies/UnityRenderStreaming#517]
Hi, hardware encoding unfortunately crashes when using any resolution higher than 1920x1080.  Happens in all versions of render-streaming.  This only occurs over the net (not local).

Hardware encoding is the preferred method as it has the lowest latency and lowest cpu use.

**Comment by karasusan** [comment]
I see. We will support it near future.

FYI
https://zenn.dev/blkcatman/articles/c2cb8517fd290b

**Comment by ZeoWorks** [comment]
Thank you, I'll follow the tutorial. :)

So, is HW_62 prebuilt in WebRTC 2.4.0?

Is it prebuilt in Render Streaming 3.1.0?

**Comment by gushenjie** [comment]
Has it been solved?

**Comment by ZeoWorks** [comment]
Following the tutorial resolves the issue.

**Comment by karasusan** [comment]
memo: URS-371

**Comment by karasusan** [comment]
We reproduced the issue on also macOS, and understood that we need to upgrade libwebrtc package M90 or later.
Related thread.
https://groups.google.com/g/discuss-webrtc/c/AVeyMXnM0gY

**Comment by karasusan** [comment]
@ZeoWorks 
Hi, we upgraded the package but not finished the issue on Windows.
We are going to upgrade NvCodec version in the next milestone.

**Comment by karasusan** [comment]
This issue is fixed in the PR.
#683
