### ISSUE TITLE
[REQUEST] DirectX12  SUPPORT

### ISSUE THREAD

**Issue by gushenjie** [Unity-Technologies/UnityRenderStreaming#519]
how can i enable DirectX12  ?

**Comment by karasusan** [comment]
Please set `Auto Graphics API for Windows` in Project Settings Window
https://docs.unity3d.com/Manual/class-PlayerSettingsStandalone.html#Rendering

![image](https://user-images.githubusercontent.com/1132081/127083893-6c159159-0ddb-40f1-9d34-8091c1b34232.png)

**Comment by gushenjie** [comment]
thank u

**Comment by gushenjie** [comment]
![image](https://user-images.githubusercontent.com/10531802/127998654-b9b907e2-12db-4c62-919b-7d3a79dae8da.png)
