### ISSUE TITLE
[BUG] Couldn't run any sample scene due to fail of finding libwebrtc.so in linux/ubunto20.04

### ISSUE THREAD

**Issue by robinzhx** [Unity-Technologies/UnityRenderStreaming#520]
**Describe the bug**
Cannot run any sample scene due to fail of finding libwebrtc.so

**To Reproduce**
Go to Asset/Sample/Receiver, and run the scene Receiver

**Expected behavior**
`Plugins: Couldn't open /***/Library/PackageCache/com.unity.webrtc@2.4.0-exp.3/Runtime/Plugins/x86_64/libwebrtc.so, error: libc++.so.1: cannot open shared object file: No such file or directory`

`DllNotFoundException: Packages/com.unity.webrtc/Runtime/Plugins/x86_64/libwebrtc.so
Unity.WebRTC.WebRTC.Initialize (Unity.WebRTC.EncoderType type, System.Boolean limitTextureSize) (at Library/PackageCache/com.unity.webrtc@2.4.0-exp.3/Runtime/Scripts/WebRTC.cs:341)
Unity.RenderStreaming.RenderStreamingInternal..ctor (Unity.RenderStreaming.RenderStreamingDependencies& dependencies) (at Library/PackageCache/com.unity.renderstreaming@3.1.0-exp.1/Runtime/Scripts/RenderStreamingInternal.cs:118)
Unity.RenderStreaming.RenderStreaming.Run (System.Nullable`1[T] conf, System.Nullable`1[T] hardwareEncoder, Unity.RenderStreaming.Signaling.ISignaling signaling, Unity.RenderStreaming.SignalingHandlerBase[] handlers) (at Library/PackageCache/com.unity.renderstreaming@3.1.0-exp.1/Runtime/Scripts/RenderStreaming.cs:103)
Unity.RenderStreaming.Samples.ReceiverSample.Start () (at Assets/Samples/Unity Render Streaming/3.1.0-exp.1/Example/Receiver/ReceiverSample.cs:35)`

**Environment (please complete the following information):**
Ubuntu20.04
Unity 2020.3.14f1
Unity Rendering Streaming 3.1.0-exp1

**Comment by karasusan** [comment]
Hi, could you check this page?
https://github.com/Unity-Technologies/com.unity.webrtc/issues/491#issuecomment-887925971

**Comment by robinzhx** [comment]
Thanks @karasusan for getting the question so quick. Apparently it is due to a dumb developer (me) not reading the documentation carefully. The issue got solved by https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/index.html

> On Linux, libc++1 libc++abi1 packages should be installed. Please install like command below
> `sudo apt install -y libc++1 libc++abi1`
