### ISSUE TITLE
[REQUEST] Setup RenderStreaming component from code

### ISSUE THREAD

**Issue by GMyjak** [Unity-Technologies/UnityRenderStreaming#521]
Hi,

In my case I get all signaling server connection data from API. Then I cannot properly set up connection in `RenderStreaming` component, because almost all its fields are private (`urlSignaling`, `signalingType`, ...).

Obvious solution would be making these fields public. Alternatively, could you help me find another solution?

**Comment by pilzinho** [comment]
Hi! Did you have a look at the Run() method of RenderStreaming? You can pass a lot of parameters there. E.g. that's the way I do it
```
renderStreaming.Run(null, hardwareEncoder: true, 
    new WebSocketSignaling($"ws://localhost:{port}", 5, SynchronizationContext.Current));
```
