### ISSUE TITLE
[REQUEST] How to access multiple users?

### ISSUE THREAD

**Issue by sherlockat** [Unity-Technologies/UnityRenderStreaming#522]
I'm implementing Render Streaming on a windows server.
We are creating an environment where a large number of users can use the service.

Are the following two examples possible?

Example 1)
1. 100 users connected
2. Add 100 cameras to the scene
3. Send the rendering result screen for each camera

Example 2)
1. 100 users connected
2. Add 100 cameras to the scene
3. Allocate 100 objects to the camera
4. Each one sends their own object rendering result screen

The number of users is an example.
If both methods are not possible, should I add a server instance every time a user connects?
Is there a better way?

**Comment by karasusan** [comment]
We have never tested the situation that over 100 users connect the same scene.
It should happen the performance issue because each camera needs to render the scene individually.

**Comment by karasusan** [comment]
@sherlockat
Hi, any question?

**Comment by kannan-xiao4** [comment]
@sherlockat We released `Multiplay` sample on latest version.
Please try this sample.
