### ISSUE TITLE
[BUG] Signalling server continues to run even when project is not in play mode

### ISSUE THREAD

**Issue by HugoJHall** [Unity-Technologies/UnityRenderStreaming#526]
Intermittently I am encountering situations where the signalling server continues to print messages to the console while the application is not running in the editor. I think this may also be causing trouble with build applications too as they hang for a long time on exit and the logs are full of standard signalling messages at the end such as this:

[impolite-Unity.RenderStreaming.PeerConnection] this candidate can't accept current signaling state Stable.

I wonder if the thread is not being closed correctly in some cases.

1. Run a render streaming enabled application
2. Repeatedly establish and close the connection
3. Attempt to close the app or stop it running while the connection is active
4. There is then a roughly 20% chance it hangs or continues to print signalling messages

Expected behavior:
That when the application exits or stops running the signalling system also shuts down

 - OS: Windows
 - Unity Version 2021.1.17f1
 - Package version 2.4.0-exp.3

**Comment by karasusan** [comment]
@HugoJHall 
Hi, do you mean the polling of signaling on the application is not stopped when the application is exited?

**Comment by HugoJHall** [comment]
Yes, something like that.

**Comment by karasusan** [comment]
memo: URS-370

**Comment by karasusan** [comment]
@HugoJHall
This issue is fixed in the latest verion 3.1.0-exp.2.
