### ISSUE TITLE
Multi-touch doesn't work, touches handling code seems broken

### ISSUE THREAD

**Issue by doctorpangloss** [Unity-Technologies/UnityRenderStreaming#527]
https://github.com/Unity-Technologies/UnityRenderStreaming/blob/d0e5140acf51dd0b730b4b215710cd31f7fa2e8a/WebApp/public/js/register-events.js#L299

It isn't really making sense what's going on here, so maybe take another look at it.

Multi-touch produces a bunch of errors. For example, if you press two buttons, you'll get "Pointer should exit" errors.

Otherwise the code that solves for the coordinate in the video feed only works when the video element is `object-fit: contain`.

**Comment by karasusan** [comment]
Sure, this line isn't making sense. I will fix it.

> Otherwise the code that solves for the coordinate in the video feed only works when the video element is object-fit: contain.
Thanks for the info, I will try that
