### ISSUE TITLE
[BUG] iOS Error when render streaming is closed and reopened

### ISSUE THREAD

**Issue by karasusan** [Unity-Technologies/UnityRenderStreaming#529]
## Describe the bug
On iOS when I close a connection and start a new one, I get an instance has been disposed error.

## To Reproduce

```
RenderStreaming.Run(...);
RenderStreaming.Stop();
RenderStreaming.Run(...);
```

## Expected behavior
No error.

## Screenshots
![image](https://user-images.githubusercontent.com/1132081/133196103-12b5f0fd-dbe8-4c32-9a76-0f8150c1bf6f.png)

## Environment (please complete the following information):

OS: iOS
Unity Version 2019.4.19f1
WebRTC Package version 2.4.0-exp.3
RenderStreaming Package version 3.1.0-exp.1

**Comment by karasusan** [comment]
memo: URS-350

**Comment by alvarocabrero** [comment]
Hello, I get this error also in Android and PC, not only IOS. Its any solution available yet? I need to create a system which needs to change between different devices, so I need to be able to run and stop the streaming multiple times in the same device.

**Comment by karasusan** [comment]
@alvarocabrero
I think this error relates GC. 
we will check it soon.
