### ISSUE TITLE
[BUG] Jitter over 40mbps 

### ISSUE THREAD

**Issue by ZeoWorks** [Unity-Technologies/UnityRenderStreaming#530]
Hi, when you set the bitrate/bandwidth to anything over 40mbps, jittering occurs.  Is there a way to alter the FEC (forward error correction) settings in order to prevent this?  Or any other method to prevent jitter?

**Comment by karasusan** [comment]
@ZeoWorks 
There is no options for prevent jitter. 
Are you using the Hardware encoder? Could you compare the software encoder?
Thanks.

**Comment by ZeoWorks** [comment]
Hi, I resolved the issue.
It turns out I was using software decoding which caused the jitter on the clients end.
Switching to hardware decoding resolved the issue.

**Comment by karasusan** [comment]
Thanks for your checking, this is known issue here and planned to fix.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/205

**Comment by karasusan** [comment]
@ZeoWorks
Hi, could you tell me how to solved this issue? thanks.

**Comment by ZeoWorks** [comment]
@karasusan Hello again!
Yes absolutely, it turns out that on Ubuntu Linux; Linux web browsers have hardware acceleration disabled by default.  Resulting in h264 software decoding as opposed to h264 hardware decoding.  This means if the bitrate is too high, the CPU has difficulty decoding.  The solution is to manually enable hardware acceleration on Linux web browsers or use Windows.
Linux web browsers tested are as follows;  
-Chromium, 
-FireFox, 
-Brave

**Comment by karasusan** [comment]
@ZeoWorks
I would like to know how do you switch enable the hardware acceleration on linux browser.

**Comment by ZeoWorks** [comment]
> @ZeoWorks I would like to know how do you switch enable the hardware acceleration on linux browser.

It should work by following this tutorial;
https://www.howtogeek.com/412738/how-to-turn-hardware-acceleration-on-and-off-in-chrome/

However, I think some particular versions of the browser actually have the feature hard-disabled through the package itself. 
You'll need to make sure you have a version with it supported.

**Comment by karasusan** [comment]
@ZeoWorks
This is very helpful. Thanks!

**Comment by karasusan** [comment]
@ZeoWorks 
Can I close this issue? Thanks.

**Comment by ZeoWorks** [comment]
Sure, no problem.  Thanks.
