### ISSUE TITLE
Bidirectional cannot connect to server

### ISSUE THREAD

**Issue by mykr13A** [Unity-Technologies/UnityRenderStreaming#558]
**Describe the bug**

I use the Bidirectional Sample and I try to connect via Unity app (PC1) to the web page in Chrome (PC2). The web app server is running on PC2 but I cannot connect via Unity app to the web page.

When I run the web app server on PC1, the connection is successful. 

I notice that when I play the scene,  in the Unity Editor,  the URL automatically changes from ws://139.XX.XXX.XXX to ws://localhost. 
That is, the server should only run on the PC running Unity app? And if the server is running on other PC how I can connect to.

**Environment (please complete the following information):**
 - Windows 10
 - Chrome
 - Unity Version 2019.4.30f1
 - Package version 3.1.0-exp.1

**Comment by karasusan** [comment]
@mykr13A
Hi, Have you solved your issue?
Can I close this ticket?

**Comment by mykr13A** [comment]
Yes, I solved it. Thank u!

Στις Τρί, 9 Νοε 2021 στις 4:26 π.μ., ο/η Kazuki Matsumoto <
***@***.***> έγραψε:
