### ISSUE TITLE
[BUG] Android app unable to connect

### ISSUE THREAD

**Issue by mykr13A** [Unity-Technologies/UnityRenderStreaming#568]
**Describe the bug**

I would like to use the Bidirectional project on a smartphone as an android app. 
But it is unable to connect to the websever and thus to any peer. 
I have build the project on Android platform, I have access to smartphone's camera but I cannot be connected anywhere. 
Instead on Windows everything works fine.
Do you have any idea why is this happening?

**Environment (please complete the following information):**
 - OS: Android 5 and Android 9 
 - Unity Version  2019.4.30f1
 - Package version 3.1.0-exp.1

**Comment by karasusan** [comment]
Could you tell me what android devices you are using? 
And how about other platforms like windows or macOS?

**Comment by mykr13A** [comment]
I fixed it. I haven't selected the ARM64 and IL2CPP at the player settings.
Thank you!

Στις Τρί, 9 Νοε 2021 στις 4:25 π.μ., ο/η Kazuki Matsumoto <
***@***.***> έγραψε:

**Comment by karasusan** [comment]
@mykr13A
May I close this issue? Thanks.
