### ISSUE TITLE
Replace Webcam Streamer with other video stream

### ISSUE THREAD

**Issue by mykr13A** [Unity-Technologies/UnityRenderStreaming#595]
I would like to ask if the web camera streamer can be replaced by other video stream.
For example, a video stream that is external such as an rtmp.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Unity Version: 2019.4.30f1
 - Package version:  3.1.0-exp.1

**Comment by karasusan** [comment]
Hi, RTMP means like Youtube live streaming?

**Comment by mykr13A** [comment]
Hi, 
 we have two cases:
1.we receive an rtmp stream from a 360 video cam (Insta360 OneR Twin Edition) that can also stream on youtube.
2.we can create an rtmp or rtsp stream from an ffmpeg

**Comment by ZeoWorks** [comment]
> Hi, we have two cases: 1.we receive an rtmp stream from a 360 video cam (Insta360 OneR Twin Edition) that can also stream on youtube. 2.we can create an rtmp or rtsp stream from an ffmpeg

This is unrelated to WebRTC which is the backend of RenderStreaming.

**Comment by karasusan** [comment]
We don't focus on the RTMP support. I am not sure how to use RTMP in Unity, but is this asset useful for you?
https://assetstore.unity.com/packages/tools/video/easy-movie-texture-video-texture-10032?_ga=2.261186637.1127634173.1637728076-1256027805.1597314045

**Comment by mykr13A** [comment]
I have tried another video player but video players have a big delay to
display live streams. That's why I want to use the webrtc protocol.


Στις Τρί, 30 Νοε 2021 στις 7:24 π.μ., ο/η Kazuki Matsumoto <
***@***.***> έγραψε:

**Comment by ZeoWorks** [comment]
> 

You will not get a low delay with RTMP, the technology is simply not made for that.
WebRTC sends the encoded h264 packets (encoded with nvidia SDK) straight over the network through UDP to the receiver for instant decoding.  Hope that helps.

**Comment by mykr13A** [comment]
I think that you misunderstood.
I want to use webrtc but I want to replace the webcam that is used in the
Samples with an rtmp stream.

Στις Τρί, 30 Νοε 2021 στις 1:49 μ.μ., ο/η ZeoWorks ***@***.***>
έγραψε:

**Comment by ZeoWorks** [comment]
> 

You'll then need to set up a rtmp stream and use a plugin that streams into unity, then stream a camera via webrtc that is showing the rtmp stream. :)

**Comment by mykr13A** [comment]
I did not understand the last part.
Could you please explain it?

Στις Τετ, 1 Δεκ 2021 στις 3:34 μ.μ., ο/η ZeoWorks ***@***.***>
έγραψε:

**Comment by kannan-xiao4** [comment]
@mykr13A

The current discussion has nothing to do with UnityRenderStreaming, so please discuss it on the Unity Forum.
This ticket will be closed if there is nothing to discuss here.

**Comment by winlinvip** [comment]
You can use a media server to covert RTMP(from your camera) to WebRTC, then you're able to use unity WebRTC to play it. See https://github.com/Unity-Technologies/com.unity.webrtc/issues/33#issuecomment-1377044987
