### ISSUE TITLE
[BUG] Screen is flipped vertically when streaming from Android device

### ISSUE THREAD

**Issue by burakkaraceylan** [Unity-Technologies/UnityRenderStreaming#597]
Stream broadcasted from an Android device is shown vertically flipped on the web applicaton.
**To Reproduce**
1. Build and run broadcast sample on Android device
2. Go to receiver sample on the web app
3. Click play

**Expected behavior**
Stream should be shown exactly as it is on the android application

**Screenshots**
![image](https://user-images.githubusercontent.com/84451726/143615943-7fbc09e9-ec57-470e-bb7a-224ce84c8f4c.png)

**Environment (please complete the following information):**
 - OS: Android 11
 - Browser: Chrome
 - Unity Version: 2020.3.21f1
 - Package version [e.g. 3.1.0-exp2]

**Comment by karasusan** [comment]
@burakkaraceylan 
Thanks for the feedback.
There is a workaround that change graphics API to Vulkan.

**Comment by burakkaraceylan** [comment]
Is that possible? As far as I know you can't compile AR core when vulcan is enabled.

**Comment by karasusan** [comment]
memo: WRS-166

**Comment by karasusan** [comment]
@burakkaraceylan
Unfortunately, AR core is needed to build GLES graphic API.

There is a workaround that customizing `ScreenStreamSender` using another constructor of `VideoStreamTrack`.
https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Runtime/Scripts/VideoStreamTrack.cs#L113-L119

**Comment by burakkaraceylan** [comment]
For now I am handling it like this. Can it be done better or faster?

`        IEnumerator RecordFrame()
        {
            yield return new WaitForEndOfFrame();

            ScreenCapture.CaptureScreenshotIntoRenderTexture(_flippedTexture);
            Graphics.Blit(_flippedTexture, m_sendTexture, new Vector2(1.0f, -1.0f), new Vector2(0.0f, 1.0f));
        }`

**Comment by karasusan** [comment]
@burakkaraceylan 
Nice. We have a plan fixing this issue that adding a flag to flip texture to `VideoStreamTrack`.

**Comment by yinhew** [comment]
> For now I am handling it like this. Can it be done better or faster?
> 
> ```cs
>        IEnumerator RecordFrame()
>         {
>             yield return new WaitForEndOfFrame();
> 
>             ScreenCapture.CaptureScreenshotIntoRenderTexture(_flippedTexture);
>             Graphics.Blit(_flippedTexture, m_sendTexture, new Vector2(1.0f, -1.0f), new Vector2(0.0f, 1.0f));
>         }
> ```

@burakkaraceylan How did you apply this work around?
This code is part of the package.
How did you edit the code after you installed the package?

I installed the WebRTC package following https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Documentation~/install.md#case-of-unity-20203
Did you do the same?

**Comment by burakkaraceylan** [comment]
@yinhew  I cloned the git repo and installed from disk to get the latest version. But, you should still be able to edit the scripts anyway. It's an open source package and screen stream sender is just a C# script. However, what I did was I cloned the screen stream sender script and made my own version where I fiddle with it and use it in the stream list.

**Comment by yinhew** [comment]
Got it, thanks a lot! @burakkaraceylan

**Comment by karasusan** [comment]
This issue is fixed #630.
The new version will be released in this month.
