### ISSUE TITLE
[REQUEST] FFMPEG Support for hardware decoding (Maybe even hardware encoding?) or AMD GPU encoding support?

### ISSUE THREAD

**Issue by ZeoWorks** [Unity-Technologies/UnityRenderStreaming#606]
Hello,
FFMPEG is a brilliant open source library that works cross platform (Windows, Linux, MacOS, Android, iOS.etc), if licenses permit I think this would be the best solution to standalone hardware decoding.  It could also even be used as h264 hardware encoding across all GPU's (Nvidia, AMD, Intel).  I was wondering if you would consider support for this library?
I noticed several unity assetstore listings that use FFMPEG as a backend for video players so I can't imagine there will be license conflicts.

In addition, I was wondering if AMD GPU hardware encoding would be support anytime soon for Windows?
Thanks.

-Sean

**Comment by karasusan** [comment]
@ZeoWorks 
You've got a point. Our team need more time to discuss about the topic.

**Comment by ZeoWorks** [comment]
> @ZeoWorks You've got a point. Our team need more time to discuss about the topic.

Hello again, any news regarding this?

**Comment by karasusan** [comment]
@ZeoWorks 
Could you give me your any idea?  Thanks.

**Comment by karasusan** [comment]
Same issue.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/456

**Comment by karasusan** [comment]
memo: WRS-140

**Comment by ZeoWorks** [comment]
@karasusan 'Moonlight' uses FFMPEG to decode across all platforms;
https://github.com/moonlight-stream
'Sunshine' uses FFMPEG to encode with any GPU (AMD, NVIDIA, INTEL).etc.;
https://github.com/loki-47-6F-64/sunshine

If you can utilise ffmpeg for encoding (or decoding) in unity, this will allow universal hardware encoding/decoding support without implementing each individual GPU provider SDK.
Thanks. :)

**Comment by karasusan** [comment]
I am not familiar for OSS license, but I guess it is difficult for many customers to make products depending library under GPL license.

**Comment by karasusan** [comment]
To support this, we need to investigate about license issue for ffmpeg. But in this moment, I think it is difficult, unfortunately.
Thanks for your advice.

**Comment by karasusan** [comment]
@ZeoWorks
Any questions?
Would you mind I close this?
