### ISSUE TITLE
[QUESTION] Need a way to implement the video player in browser synchronizing with the Unity.(Render Streaming/WebRTC)

### ISSUE THREAD

**Issue by ZsjsDinosaur** [Unity-Technologies/UnityRenderStreaming#612]
Hi, i am a novice in Unity.Recently i used the example called 'Broadcast' in the pakage of Unity Render Streaming.
For implementing the function in the browser and unity,i deploy the Node.js and npm. And it is ok when i modify the 'Signaling URL' in the component called 'RenderStreaming' in this example.But i failed when i input the url in the brower.The Unity reports an error like this:'EndOfStreamException: Unable to read beyond the end of the stream.'.   
    How can i solve this problem?

**Comment by karasusan** [comment]
You can post the question to [Unity Forum](https://forum.unity.com/forums/unity-render-streaming.413).
I think Unity could not access the web server.

**Comment by ZsjsDinosaur** [comment]
OK,thanks a lot

**Comment by ZsjsDinosaur** [comment]
@karasusan Thank you very much for your reply
excuse me! 
     The unity no longer reports  the error  after i update the web app which comes from Unity system in the way:"Edit-Render Streaming-Download web app".But it still not working.
     The console report  : "Signaling: WS connection closed, code: 1002" . It was disconnected as soon as it connected to the system after i type the url and click the running buttom in Unity.
     I try many ways to search for the answer but get nothing.How can i solve the problem?
     I sincerely look forward to your reply!

**Comment by karasusan** [comment]
@ZsjsDinosaur
Have you read these documents?
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/sample-broadcast.html

**Comment by karasusan** [comment]
@ZsjsDinosaur 
Have you solved your issue?

**Comment by ZsjsDinosaur** [comment]
Thank you for your consideration!
It hasn't been solved yet.I've been working on something else because my task has been changed.
I will continue to try myself to solve the problem if i finish my work.
Thanks again for your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Unity-Technologies/UnityRenderStreaming"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月21日(星期二) 下午2:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Unity-Technologies/UnityRenderStreaming] [QUESTION] Need a way to implement the video player in browser synchronizing with the Unity.(Render Streaming/WebRTC) (Issue #612)





 
@ZsjsDinosaur
 Have you solved your issue?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
