### ISSUE TITLE
Issue under Android and through Wifi-Direct - bad performance

### ISSUE THREAD

**Issue by syshex** [Unity-Technologies/UnityRenderStreaming#614]
First of all, I'm not at all sure this is a bug, but it is defenetly an issue I've come across, which I suspect is probably related.

**Describe the bug**
I've implemented an Android App in Unity with this Streaming solution. I've set it up using the documentation here https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/create-scene.html .

Then I have another Android App, implemented in Cordova, which I've implemented making a clone of the  Web Application provided.   So, this app is to receive Video.

When I set the Receiver Android device as Hotspot, and connect the Streamer to that hotspot , and then perform Streaming, all works wonderfully, speed is fast, resolution is good, no issues.

If instead of Hotspot ,  I create a WifiDirect connection , then the Streaming that is being received is very very very laggy.  

From everything I've read, WifiDirect should be as fast and regular Wifi. 

**To Reproduce**
1. Create an Android App to Stream a camera
2. Create an Android App to receive the Stream
3. Make a WifiDirect connection
4. Connect the Streamer app to the signal server on the Receiver app, using the IP from the WifiDirect connection.

**Expected behavior**
To work exactly as if it was connect through hotspot etc.

**Screenshots**
I can record a video of the laggyness, but accept that the video will show  2 fps 

**Environment (please complete the following information):**
 - OS: Android on both devices
 - Unity Version 2020.3.20f1
 - Package version 3.1.0-exp1

**Additional context**

**Comment by karasusan** [comment]
@syshex 
Could you compare network bandwidth between WifiDirect and Hotsport?

**Comment by syshex** [comment]
Give a a few details to get more details on this. It is probably related to some bad handling of mine of the Wifi Direct processes.  

I'll get back with more details, or will close the issue with an explanation

**Comment by karasusan** [comment]
I will close this issue if there is no reply until next week. Thanks.

**Comment by kannan-xiao4** [comment]
@syshex 
Since there was no response, close the issue. 
If anything happens, please open or create the issue again.
