### ISSUE TITLE
[BUG] Linux Crash segfault libwebrtc.so

### ISSUE THREAD

**Issue by KuroFox** [Unity-Technologies/UnityRenderStreaming#615]
Hi, I have a problem when I use a linux server with version 3.1.0 exp2
when switching to the scene where I have HDRP with input Browser and someone connect to the server, it crashes and throws this error in the syslog segfault libwebrtc.so

**To Reproduce**
1.Open app
2. Click on renderpileline with input browser
3. Connect by server
4. Crash and close the app

**Expected behavior**
I hope it can connect like I do in windows

**Environment**
 - Linux
 - Browser [Chrome,edge]
 - Unity Version [2020.3.23f1]
 - Package version [3.1.0 exp 2]

[error.txt](https://github.com/Unity-Technologies/UnityRenderStreaming/files/7749940/error.txt)

**Comment by karasusan** [comment]
@KuroFox 
We don't found the cause of crash in your error log.
Could you give me other logs?
And What version of Ubuntu are you using?

Thanks.
