### ISSUE TITLE
[PROBLEM] Why does the GUI display abnormally

### ISSUE THREAD

**Issue by YngJian** [Unity-Technologies/UnityRenderStreaming#616]
I can display normally in the editor, but after connecting to the browser, mouse events and GUI are not displayed.

![image](https://user-images.githubusercontent.com/49049863/147239860-359f93b4-d749-4144-ab4a-73e23f999aa3.png)

![1640261375(1)](https://user-images.githubusercontent.com/49049863/147238719-39721321-9088-43b5-8e80-9078a7669864.jpg)

**Comment by karasusan** [comment]
@YngJian 
**WebBrowserInput** sample uses `CameraStreamSender`, this component send texture displaying on a camera.
If you want to send video with UI, please try **Broadcast** sample.

**Comment by YngJian** [comment]
After I switched, the editor was running normally, but an error was reported after opening the browser.

![image](https://user-images.githubusercontent.com/49049863/147306192-558efbaf-42df-4724-aaf4-0df2945f9436.png)

**Comment by YngJian** [comment]
> 



> @YngJian **WebBrowserInput** sample uses `CameraStreamSender`, this component send texture displaying on a camera. If you want to send video with UI, please try **Broadcast** sample.

**Comment by YngJian** [comment]
> @YngJian **WebBrowserInput** sample uses `CameraStreamSender`, this component send texture displaying on a camera. If you want to send video with UI, please try **Broadcast** sample.

After I switched, the editor was running normally, but an error was reported after opening the browser.

![image](https://user-images.githubusercontent.com/49049863/147306192-558efbaf-42df-4724-aaf4-0df2945f9436.png)

**Comment by karasusan** [comment]
Have you tried with reading this document?
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/sample-broadcast.html

**Comment by YngJian** [comment]
> Have you read this document? https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/sample-broadcast.html

Excuse me, if I have a mouse click event on an object, then the result is displayed through the GUI. I need to be able to operate in the editor, but also in the browser, which way do I need to use in this case

**Comment by karasusan** [comment]
@YngJian
Could you try to use the latest version?
In this present, The latest version is **3.1.0-exp.2**.

**Comment by kannan-xiao4** [comment]
@YngJian In addition: on 3.1.0-exp.2 version's `Broadcast` sample provide uGUI control from browser.

**Comment by YngJian** [comment]
> @YngJian Could you try to use the latest version? In this present, The latest version is **3.1.0-exp.2**.

Not yet, I'll try again.thanks.

**Comment by kannan-xiao4** [comment]
@YngJian Do you have any update?
If nothing, we will close this issue.

**Comment by kannan-xiao4** [comment]
If you have any question, please re-open issue.
