### ISSUE TITLE
[BUG] Received screen upside down (up-down-reversed) with "Screen Stream Sender" on Linux (Ubuntu 20.04)

### ISSUE THREAD

**Issue by yinhew** [Unity-Technologies/UnityRenderStreaming#618]
**Describe the bug**

I tried the https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/sample-broadcast.html sample on both Windows and Linux.
On Windows it's good.
But on Linux I saw the received screen (in browser) was upside-down (up-down-reversed), like below:
https://1drv.ms/u/s!AjzWn-xH-49WlKJoxrJywm6D40Oe3g

**To Reproduce**
1. Follow https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/sample-broadcast.html to run the sample with latest WebRTC package and webserver application, on Linux (I was using Ubuntu 20.04 desktop)
2. Open link "http://localhost/receiver/index.html" in browser (I was using chrome).

**Expected behavior**
The received screen in browser is consistent with the desktop screen.

**Screenshots**
https://1drv.ms/u/s!AjzWn-xH-49WlKJoxrJywm6D40Oe3g

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS Desktop
 - Browser: Chrome
 - Unity Version: 2020.3.25f1
 - Package version: 3.1.0-exp.2

**Additional context**
Looks this issue only happens to "Screen Stream Sender", and doesn't happen to "Camera Stream Sender".
Also, when I built my own unity project with WebRTC package, the same issue happened. So looks it's not an issue of the sample, but a bug of the package or the webserver app.

**Comment by karasusan** [comment]
Is this same issue?
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/597

**Comment by yinhew** [comment]
Yes, it's the same issue. Thanks for pointing to the correct thread!

I saw it mentioned below work around:
       IEnumerator RecordFrame()
        {
            yield return new WaitForEndOfFrame();

            ScreenCapture.CaptureScreenshotIntoRenderTexture(_flippedTexture);
            Graphics.Blit(_flippedTexture, m_sendTexture, new Vector2(1.0f, -1.0f), new Vector2(0.0f, 1.0f));
        }

How can I apply this change in my project?
Do I need to rebuild the WebRTC package?

**Comment by karasusan** [comment]
memo: URS-375

**Comment by karasusan** [comment]
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/597#issuecomment-1032126823

**Comment by karasusan** [comment]
@yinhew
Please check the new version **3.1.0-exp.3**.
