### ISSUE TITLE
[BUG] Keyboard input sending only sends one key at a time

### ISSUE THREAD

**Issue by jmalexan** [Unity-Technologies/UnityRenderStreaming#619]
**Describe the bug**
It seems that by default, the keyboard input is only capable of sending one key at a time to the Unity application.  This causes issues when combined movement is necessary, for example holding "W" and "A" at the same time to move in the combined directions "forward" and "left".  Currently, when pressing both these buttons at once, only the last key to be pressed is sent.

**To Reproduce**
1. Open and run the Multiplay sample scene
2. Select "Host" and click the "Start" button in the UI panel
3. Open the Multiplay remote page and press the play button to connect to the Unity application
4. Press both "W" and "A" at once
5. The ball rolls either forward or left

**Expected behavior**
The ball should roll in the combined directions of forward and left, not one or the other.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Unity Version 2020.3.19f1
 - Package version 3.1.0-exp.2

**Additional context**
It appears this is because, when a new KeyboardState is declared (happens when the "keydown" event is fired in the JS), it always declares a new key state array every time (https://github.com/Unity-Technologies/UnityRenderStreaming/blob/dd174661a859b279c7d9014c85d0201b04c6be73/WebApp/client/public/js/inputdevice.js#L288).  This would override any previous state, and send an event that only indicates the most recently pressed key is being pressed.  The TouchscreenState class just below provides a template for how this could be resolved, by taking the previous state as an argument in the constructor.  Since the fix seemed relatively simple (and I need this functionality to work ASAP) I implemented a fix myself that seems to work, and I'll submit a pull request shortly, in case it's helpful.

**Comment by karasusan** [comment]
@jmalexan 
We will review your pull request. Thank you!

**Comment by karasusan** [comment]
memo: URS-384

**Comment by karasusan** [comment]
We will review this issue next milestone.

**Comment by karasusan** [comment]
I am checking.

**Comment by karasusan** [comment]
#620 is merged.

**Comment by karasusan** [comment]
@jmalexan
Please check the new version **3.1.0-exp.3**.
