### ISSUE TITLE
[REQUEST] Is there a way to run Unity standalone player on a server without desktop/display?

### ISSUE THREAD

**Issue by yinhew** [Unity-Technologies/UnityRenderStreaming#621]
**Is your feature request related to a problem? Please describe.**
I want to run the unity player on a server (or even a docker container), which doesn't have a display / desktop. (e.g. Ubuntu server).
And broadcast the rendered stream to clients through WebRTC.

**Describe the solution you'd like**
I tried to run the Unity standalone player on a Linux server without a display/desktop, but it failed to start.
Even I installed the x11-xserver-utils, it still reported error "Error: Can't open display: :0"

**Describe alternatives you've considered**
I also tried the server build of Unity standalone player, but looks it then didn't do any rendering.
Is there a way to still do rendering with a server build?

**Comment by kannan-xiao4** [comment]
@yinhew 

Can you show me the Unity logs?
Unity app requires graphics devices. ( I guess that the graphics device may not be recognizable.)

**Comment by yinhew** [comment]
Thanks @kannan-xiao4 

I saw two errors in the Unity log when running headless build on Linux:

Error1:

Unable to preload the following plugins:
	libwebrtc.so
Plugins: Couldn't open /home/yinhew/Desktop/.../Plugins/libwebrtc.so, error: /home/yinhew/Desktop/.../Plugins/libwebrtc.so: undefined symbol: glCopyImageSubData
Plugins: Couldn't open /home/yinhew/Desktop/.../Plugins/libwebrtc.so, error: /home/yinhew/Desktop/.../Plugins/libwebrtc.so: undefined symbol: glCopyImageSubData


Error2:

Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
- Completed reload, in  0.072 seconds
ERROR: Shader Sprites/Default shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Sprites/Mask shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Legacy Shaders/VertexLit shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Standard shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader A2 Games/Advance Unlit shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader GUI/Text Shader shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
UnloadTime: 0.739031 ms
AudioSource required
ArgumentException: Graphics device type Null not supported
  at Unity.WebRTC.WebRTC.GetSupportedGraphicsFormat (UnityEngine.Rendering.GraphicsDeviceType type) [0x00094] in <35d438016bb447a099a04286b5d1368d>:0 
  at Unity.WebRTC.WebRTC.GetSupportedRenderTextureFormat (UnityEngine.Rendering.GraphicsDeviceType type) [0x00000] in <35d438016bb447a099a04286b5d1368d>:0 
  at Unity.RenderStreaming.ScreenStreamSender.Awake () [0x00005] in <fc460f7f1165480f97de53db0f54a058>:0

**Comment by kannan-xiao4** [comment]
@yinhew 
Thanks replay

Server build is intended for network games, etc., and graphics and sound functions cannot be used.
Unity needs to recognize the display to use the graphics features. You need a virtual display on Linux.

On Linux, see the Desktop section below for Graphics driver requirements for Unity Desktop apps.
https://docs.unity3d.com/Manual/system-requirements.html

**Comment by ZeoWorks** [comment]
You need to have your scene rendered on the GPU before the camera can even attempt to send the frame to the nvidia encoder

**Comment by kannan-xiao4** [comment]
@yinhew Do you have any update ?

Looking at the error log, it seems that the error is occurring because the version of OnpenGL is old and the Graphics device is not recognized from Unity.

`glCopyImageSubData` is supported  on OpenGL 4 or later.

**Comment by kannan-xiao4** [comment]
I close issue because there is no replay.
If you have any question, please re-open issue.
