### ISSUE TITLE
Video not working in browser

### ISSUE THREAD

**Issue by owais-kali** [Unity-Technologies/UnityRenderStreaming#622]
Input and light on/of is working fine but video is not working in browser in 3.1.0-exp.2 release. It worked fine in 3.1.0-exp.1 release though. 

![image](https://user-images.githubusercontent.com/74670162/149039032-b53e3226-6279-4e42-9b26-1667cb71d445.png)

**Comment by kannan-xiao4** [comment]
@owais-kali 
Currently, we are not able to support updates about template project, so we will investigate.
For now, try the HDRP sample below.
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/sample-renderpipeline.html

memo: URS-33

**Comment by kannan-xiao4** [comment]
memo: URS-33

**Comment by yvanzine** [comment]
I am seeing the same issue with samples. But I cannot see the video all the way back to 2.2.0 Render Streaming release! Please do this test, follow the tutorial to set up a scene and download/build the webserver and run it. I am running in URP pipeline on Linux or Windows and this environment does not produce a video. 

My own project based on 3.0.1-preview release is working fine but I do have a different signaling server. When I use the sample webserver, the video does not show up. Maybe the webserver code is the problem.

I will keep testing earlier releases but for now I am not seeing video at all in the sample code. I was tracking this regression recently and now it is great to see someone else confirm the problem. Please identify what happened to samples and when this regression occured.

**Comment by owais-kali** [comment]
I am able to run 3.1.0-exp.2 samplescene with 3.0.1 release webserver.

**Comment by karasusan** [comment]
@yvanzine
Could you try the latest version? It is difficult for us to identify the regression.

**Comment by karasusan** [comment]
We will maintain the template project.

**Comment by karasusan** [comment]
#646 is merged to the trunk branch and we will release the new version this month.

**Comment by karasusan** [comment]
@owais-kali
The package template is upgraded [here](https://github.com/Unity-Technologies/UnityRenderStreaming/releases/tag/3.1.0-exp.3).

**Comment by owais-kali** [comment]
@karasusan
Thank you for taking the time to work on this issue!  But I ended up downloading from package manager and it is working great.
