### ISSUE TITLE
Video player not working on windows server

### ISSUE THREAD

**Issue by owais-kali** [Unity-Technologies/UnityRenderStreaming#623]
Render streaming works fine on my local computer but when I deploy the build on a windows server 2016 on aws it does not work. I am using the 3.1.0-exp2 release. 

Interesting thing is when I RDP into the windows instance and try and connect using chrome browser and unity build both running on same windows instance it still does not work. I don't understand why it doesn't work when the browser and unity are both running on localhost I am sure there shouldn't be any NAT problems in this case. 

I also tried disabling the firewall but still nothing. I am able to send offer to the signaling which is also running on the same server. Signaling is working fine in unity I see a bunch of debug logs when I press play button in browser and I see a connection is established but nothing happens in the browser. I have also tried running a turn server on a ubuntu instance using this guide [Unity TURN](https://docs.unity3d.com/Packages/com.unity.renderstreaming@2.0/manual/en/turnserver.html). I have tested the turn server using trickle ICE tool and it works fine. But the video player still does not work. 

Please any help would be greatly appreciated!

Specs
Instance type: g4dn.xlarge
AMI name: Windows_Server-2016-English-Full-Base-2021.12.15
GPU: Tesla T4 - 4GB eg1.xlarge

**Comment by kannan-xiao4** [comment]
@owais-kali 
Can I share the Unity Log when connecting from the browser from Windows Server on AWS?

and Does the Windows Server recognize the GPU? 
In that case, Unity Player rendering may not be working.

**Comment by rocco-haro** [comment]
@kannan-xiao4 we got it working in AWS, although now it only works if we run it in the Editor, and fails if ran through a build. I've attached the log
[Player-Editor.log](https://github.com/Unity-Technologies/UnityRenderStreaming/files/7893775/Player-Editor.log)
[Player-Standalone.txt](https://github.com/Unity-Technologies/UnityRenderStreaming/files/7893777/Player-Standalone.txt)
s

**Comment by kannan-xiao4** [comment]
@rocco-haro 
Can you try `Broadcast` Sample ? ( not template-hd project)
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/samples.html

About template project, we don't follow latest package version.  Issued in : https://github.com/Unity-Technologies/UnityRenderStreaming/issues/622

**Comment by kannan-xiao4** [comment]
@owais-kali @rocco-haro Do you have any update?
If there is no reply, we will close the Issue.

**Comment by rocco-haro** [comment]
We were able to resolve the issue, thank you!.
