### ISSUE TITLE
[REQUEST] Is there a way to run Unity standalone file and also to Broadcast the Render Stream on WebRTC with "Http Signaling"

### ISSUE THREAD

**Issue by praveenjha-github** [Unity-Technologies/UnityRenderStreaming#627]
I want to run the unity player standalone file And also broadcast the rendered stream to clients through WebRTC.

I tried to run the game from **Unity Software** with **Http Signaling** and shows the broadcast on a WebRTC (both local and by virtual Machine on Linux) . And it works perfectly fine, I am able to see my Render Stream on the WebRTC.

![http signaling](https://user-images.githubusercontent.com/86768166/151917570-53ae226a-fa6b-4335-9d05-b81b6f86b1d5.jpg)

But, as I made the **Standalone file** of it same, and runs it and tries to show the broadcast on a WebRTC (both local and by virtual Machine on Linux) , so it fails.
I am not able to see my Render Stream on the WebRTC.

![standalone](https://user-images.githubusercontent.com/86768166/151917836-29bfb779-ad37-40e2-9aad-c710e96a0123.jpg)
![newBuild](https://user-images.githubusercontent.com/86768166/151918356-c4799334-a0c1-4256-853d-bc97e2b3b395.jpg)

Whereas if I go with the **WebSocket Signaling** in unity so I am able to see my Render Streaming in both with **Unity Software** running and also if I run my **Standalone file.**

![websocket](https://user-images.githubusercontent.com/86768166/151917861-88705db1-8f6a-4709-96c4-03f0c53bce28.jpg)

![standalone](https://user-images.githubusercontent.com/86768166/151917874-ac019d36-78f5-4826-9271-c97fbc3c6fc4.jpg)

**Comment by karasusan** [comment]
@praveenjha-github
Hi, could you give more info your issue? Thanks.

**Comment by karasusan** [comment]
@praveenjha-github
Remind

**Comment by praveenjha-github** [comment]
Thank  You @karasusan, your attention to my issue was greatly appreciated.
I have already solved the issue by my own and now it is working fine.

Now you can close this issue.
