### ISSUE TITLE
Unity to unity bidirectional render streaming not working.

### ISSUE THREAD

**Issue by Rips04** [Unity-Technologies/UnityRenderStreaming#628]
I am trying to use unity to unity bidirectional render streaming of cameras. One side running an exe with a webcam and 2nd running the unity project with laptop default camera. Also modified the code to, as the second user to connect or join will send the offer only. Once all data(offer, ICE candidate and answer) is been exchanged, only one of the instances is receiving the other instance's feed, the second one receiving images is blank. Also, the instance which sends offer receives the ICE candidate from the other instance before answer thus, it's not accepted due to peer state not being stable. What am I missing here?
Currently using unity render streaming package 3.1.0 - exp 2.

**Comment by karasusan** [comment]
Could you have more information about devices you are testing? 
OS, Graphics API, and video codec (enable HWA or not)

**Comment by Rips04** [comment]
> Could you have more information about devices you are testing? OS, Graphics API, and video codec (enabling HWA or not)

I am testing this on a windows system. both the instances are running on the same system. I didn't enable the hardware encoding option. The same is working between unity and web browser..

**Comment by Rips04** [comment]
Any update? I'm stuck with it for quite a long time..

**Comment by karasusan** [comment]
@Rips04
Did you modified the sample code? Is there a same issue when using the original code?

**Comment by karasusan** [comment]
@Rips04
Hi, have you solved your issue?
I would like to close the ticket if you solved it. Thanks.
