### ISSUE TITLE
[BUG]: Can't actually test

### ISSUE THREAD

**Issue by noe-tiger** [Unity-Technologies/UnityRenderStreaming#635]
### Package version

3.1.0-exp.2

### Environment

```markdown
* OS:Ubuntu 20.4
* Unity version:2020.3
* Graphics API: OpenGL 4.5
* Browser: Forefox
```

### Steps To Reproduce

just follow the tutorial and add manually the dependencies to the project
- com.unity.renderstreaming@3.0.1-preview
- com.unity.webrtc@2.4.0-exp.5
load the WebBrowserInput scene

### Current Behavior

I have three errors : 
- Library/PackageCache/com.unity.renderstreaming@3.1.0-exp.2/Runtime/Scripts/AudioStreamReceiver.cs(43,24): error CS1061: 'AudioStreamTrack' does not contain a definition for 'OnAudioReceived' and no accessible extension method 'OnAudioReceived' accepting a first argument of type 'AudioStreamTrack' could be found (are you missing a using directive or an assembly reference?)
- Library/PackageCache/com.unity.renderstreaming@3.1.0-exp.2/Runtime/Scripts/ScreenStreamSender.cs(93,24): error CS7036: There is no argument given that corresponds to the required formal parameter 'needFlip' of 'VideoStreamTrack.VideoStreamTrack(IntPtr, int, int, GraphicsFormat, bool)'
- Library/PackageCache/com.unity.renderstreaming@3.1.0-exp.2/Runtime/Scripts/VideoStreamReceiver.cs(48,43): error CS1061: 'VideoStreamTrack' does not contain a definition for 'InitializeReceiver' and no accessible extension method 'InitializeReceiver' accepting a first argument of type 'VideoStreamTrack' could be found (are you missing a using directive or an assembly reference?)

### Expected Behavior

no errors at all and the scene runs smoothly

### Anything else?

I have tried to reproduce it on a windows fresh install in a VM (with directx11 installed) and it was the same exact errors

**Comment by karasusan** [comment]
@noe-tiger
We are preparing the new version of the Unity Render Streaming package to upgrade depended package.
We will release it this month.

**Comment by noe-tiger** [comment]
Thank you, definitely keep me informed when it comes up !
Is there a sable enough version that i could use until then (my aim is just to stream the camera feed from Unity to vlc)

**Comment by karasusan** [comment]
@noe-tiger
In this time, you can use **com.unity.renderstreaming@3.1.0-exp.2** and **com.unity.webrtc@2.4.0-exp.4**.

**Comment by karasusan** [comment]
@noe-tiger
Hi,
Please check the new version **3.1.0-exp.3**.

**Comment by noe-tiger** [comment]
Hi ! Its working now, thank you !
Tho i noticed a bug, when i start the scene with some other parameter than `ws://localhost` and `websocketsignaling` in RenderStreaming component (for instance just streaming to another port) it immediately overrides it on start
Any clue ?

**Comment by karasusan** [comment]
I guess the behavior is by design of the sample. Maybe you need to custom the sample code. 
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/samples.html

I am not familiar about integration with python, you can make a thread in the Unity Forum and someone might help you.

**Comment by noe-tiger** [comment]
I loaded the `RenderStreaming` script onto a GameObject in a scene of mine (like you did in the sample scene `Broadcast`) and if i try to change any settings that are set by default, when i press play it resets to the web socket signaling on port 80 wich i would like to keep on my machine. 
Do you know how to fix this ? tho we can open another issue for this topic if you prefer

**Comment by karasusan** [comment]
Please make another issue, thanks.
