### ISSUE TITLE
[BUG]: AudioStreamReceiver throws an error

### ISSUE THREAD

**Issue by coderubrika** [Unity-Technologies/UnityRenderStreaming#636]
### Package version

3.1.0-exp.2

### Environment

```markdown
OS: Windows10
Unity version: Unity 2020.3.6
com.unity.renderstreaming@3.1.0-exp.2
```

### Steps To Reproduce

1. Install com.unity.renderstreaming via Package Manager Unity 2020.3.6

### Current Behavior

Throwing an error after installation

### Expected Behavior

There shouldn't be any errors

**Comment by karasusan** [comment]
```
ibrary\PackageCache\com.unity.renderstreaming@3.1.0-exp.2\Runtime\Scripts\AudioStreamReceiver.cs(43,24): error CS1061: 'AudioStreamTrack' does not contain a definition for 'OnAudioReceived' and no accessible extension method 'OnAudioReceived' accepting a first argument of type 'AudioStreamTrack' could be found (are you missing a using directive or an assembly reference?)
```

**Comment by karasusan** [comment]
@coderubrika
I tried to reproduce your issue but there is no error. How did you install the package?
![image](https://user-images.githubusercontent.com/1132081/153317843-c870a74c-343b-40ce-9e2c-b4f3ab4e3419.png)

**Comment by karasusan** [comment]
@coderubrika
Hi, have you solved the issue?
