### ISSUE TITLE
[BUG]: Video player not working on Local System by accessing Public IP of Windows Server

### ISSUE THREAD

**Issue by praveenjha-github** [Unity-Technologies/UnityRenderStreaming#640]
### Package version

Others

### Environment

```markdown
* OS: Windows 11
* Unity version: Unity 2019.4.32f1
* Graphics API: Radeon Graphics
* Browser: Google Chrome
* Unity Package Version: release/3.0.1
```

### Steps To Reproduce

I have made a VM instance of windows on GCP and there i have uploaded both the WebServer and also the Standalone Build File of Unity.

I have also managed the Inbound Firewall Rules in Windows Server Machine and also the Outbound Firewall rules.

 

### Current Behavior

Render streaming works with Standalone Build File and WebServer on my local computer and when I deploy the **Webserver** and **Standalone Build File** on a windows server on GCP it also works fine with the **Public IP** in the **Chrome browser in Windows Server Machine.**

I am able to see Render Streaming by accessing **Public(External) IP of Windows Server** in Chrome Browser inside **Windows Server Machine.** 

I am using the 3.1.0 release.

### Expected Behavior

But when I access the **public IP** of **Windows Server Machine** in my **Local/Another system** I am not able to see the Render Streaming.

I have also updated the Firewall Rules in my Local system, then also i am unable to see Render Streaming in my Local System with same Public IP of Windows Server Machine

### Anything else?

Any help would be greatly appreciated!

**Comment by karasusan** [comment]
Could you checked this page?
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/turnserver.html

**Comment by karasusan** [comment]
@praveenjha-github
Can you check the log of the TURN server to see whether stream video via the TURN server or not.

**Comment by karasusan** [comment]
memo: URS-391

**Comment by praveenjha-github** [comment]
@karasusan 
I am able to see the log of my TURN server.

![pic1](https://user-images.githubusercontent.com/86768166/153998024-f2e8af38-2b4d-48fe-8041-3f45def49049.jpg)

**Comment by karasusan** [comment]
@praveenjha-github
Looks like the configuration is broken.

**Comment by praveenjha-github** [comment]
@karasusan 

So, any suggestion how can i fix it.
As, i have fully followed this article  https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/turnserver.html

**Comment by praveenjha-github** [comment]
@karasusan 

Now the Log Of TURN Server is also showing:-
![log turn](https://user-images.githubusercontent.com/86768166/154045462-230d353e-dbce-4a50-b4d8-b7ca4b735150.jpg)


**I am stating my problem again,**

**This problem i basically compiles in Two Combinations which i discovered:-**

**1st Combination** :- When i deploy WebServer.exe file on the VM instance of windows on GCP and i also have Standalone Executable file of unity on same windows server on GCP, so i am able to get the Render Stream in the Chrome Browser of Windows Server machine,  but if i try to access Public IP(external IP) of Windows server machine in another system so Render Streaming Fails.

Webserver.exe started on the Windows Server machine on GCP:-
![webserver](https://user-images.githubusercontent.com/86768166/154042489-004c0c6d-d1f0-4f9c-bdc7-ee388a514f52.jpg)

Able to see Render Stream on the Chrome browser of Windows server machine:-
![VM server Chrome Render stream](https://user-images.githubusercontent.com/86768166/154042555-5cf87fa2-5ab5-4604-a924-557c041d7c35.jpg)

IP address of Windows server machine on GCP:-
![ip address of VM windows ](https://user-images.githubusercontent.com/86768166/154042584-963e01b3-8cba-4f7f-9ec7-914558a7057f.jpg)

IP address on chrome of Windows server machine on GCP:-
![ip add at VM chrome](https://user-images.githubusercontent.com/86768166/154042628-ec850855-9047-4efa-9ecd-49600f1929f7.jpg)

The IP add of My VM Instance of Windows on GCP:-
![VM of windows](https://user-images.githubusercontent.com/86768166/154042695-7efc126c-f866-4e74-8c8a-1c55fbe41f42.jpg)




**Now at same time on another system /local system (except Windows Server system)**

tries to access the same IP add on chrome browser:-
![public IP at another system](https://user-images.githubusercontent.com/86768166/154042848-ce8f9659-78ec-4898-809e-1fcf2bf46773.jpg)

So, now Render Stream fails:-
![another system render stream](https://user-images.githubusercontent.com/86768166/154042901-78882e44-7887-4592-9ed8-6c2ff09d2ce8.jpg)




**2rd Combination**:-  When i deploy WebServer.exe file on the VM instance of windows on GCP and i have Unity Runtime on (local/another system), so i am able to get the Render Stream in the Chrome Browser of local/another system),  but if i try to access Public IP(external IP) of Windows server machine in another system so Render Streaming Fails.

![UnityRuntime ](https://user-images.githubusercontent.com/86768166/154045946-b27d2e76-0990-4ba9-882b-7705f8589f28.jpg)




So, by this Render Streaming is only possible in that system in which i have both WebServer.exe and Standalone Executable. If the system changes so Render Streaming fails.

**Comment by karasusan** [comment]
@praveenjha-github
Thank you for pointing this out. Perhaps the connection to the TURN is successful, but it looks like the streaming is not flowing through the TURN.
This is a difficult point for many users, so hopefully we can provide some tools to check the problem in the future.

**Comment by praveenjha-github** [comment]
@karasusan Thanks for your reply.

Can you please tell how can i verify the Streaming flow through my TURN Server?

**Comment by karasusan** [comment]
@praveenjha-github
For example, you can check the ICE exchanging using the Tricle ICE in the WebRTC sample.
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

**Comment by praveenjha-github** [comment]
@karasusan  

I have seen my ICE exchanging, there i am getting this result, after clicking (Add Server) and then (Gather Candidates).

![pic3](https://user-images.githubusercontent.com/86768166/154397260-31b08228-5ef8-4f66-a86c-748c81cf88f3.jpg)
![pic4](https://user-images.githubusercontent.com/86768166/154397266-46ca8e3e-da89-4d60-9f87-34ec2c7fd72e.jpg)

**Comment by karasusan** [comment]
I can see errors in your screenshot. Can you solve errors?
I searched and hit this post.
https://github.com/coturn/coturn/issues/678

**Comment by kannan-xiao4** [comment]
@praveenjha-github
Hi, could you check these errors?
If any other update, we will close this ticket.
