### ISSUE TITLE
[REQUEST]: Expose VideoStreamSender' streaming size

### ISSUE THREAD

**Issue by NicolasAvatar** [Unity-Technologies/UnityRenderStreaming#645]
### Is your feature request related to a problem?

I would like to access the streaming size information in Unity code.

### Describe the solution you'd like

Streaming size could be a read only property, for example something like
`public Vector2Int StreamingSize
{
    get
    {
        return streamingSize;
    }
}`

**Comment by karasusan** [comment]
@NicolasAvatar
This property has already been opened.
You mean that the `set` property should be removed?

**Comment by NicolasAvatar** [comment]
@karasusan my bad, I should have checked the latest source code sorry, now I see that its accessor is public and not protected anymore.

**Comment by karasusan** [comment]
@NicolasAvatar
Thanks for checking the new one. Please let me know another concern about this topic, if you don't have any questions, I would like to close this ticket.

**Comment by NicolasAvatar** [comment]
@karasusan yes please close this ticket.
