### ISSUE TITLE
[BUG]: input via browser broken in 3.1.0-exp.3

### ISSUE THREAD

**Issue by chopin1998** [Unity-Technologies/UnityRenderStreaming#648]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS:Linux
* Unity version: 2020.3.27
* Graphics API: opengl
* Browser: 98.0.4758.102
```

### Steps To Reproduce

unity cannot get input from browser,

back to 3.1.0.exp.2 , fine.

**Comment by karasusan** [comment]
Hi, how about Unity2021.2? and please check the setting below.
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/use-inputsystem.html

I upgraded Input System version 1.3, it is possible to affect the behavior.
Input System was improved for controlling input event without the window focus. But looks like this improvement doesn't work on Unity2020 or earlier.

**Comment by chopin1998** [comment]
some of other plugins stop me to use newer unity editor....

**Comment by karasusan** [comment]
OK, I will try to downgrade the Input System version.

**Comment by karasusan** [comment]
@chopin1998
Could you try that? If this change fixes your issue, we will merge to trunk.
https://github.com/Unity-Technologies/UnityRenderStreaming/tree/fix/downgrade-inputsystem

**Comment by chopin1998** [comment]
i believe there is a simply way to modify code (hardcode) to change the default bitrate setting, could you please tell me where to change it?

@karasusan

**Comment by chopin1998** [comment]
> 

will let you know

**Comment by karasusan** [comment]
@chopin1998
Oh, is there no issue for upgrading Input System 1.3?
I would like to upgrade it if there is no problem.
