### ISSUE TITLE
[REQUEST]: Handler for WebRTC connection end in bidirectional 

### ISSUE THREAD

**Issue by grayhong** [Unity-Technologies/UnityRenderStreaming#659]
### Is your feature request related to a problem?

In bidirectional sample (websocket connection to signaling server), there is no way to detect whether the peer connection is ended or not.

So the connection is remained in one side.

### Describe the solution you'd like

UnityEvent that we can subscribe to handle the connection end.

### Describe alternatives you've considered

Additional server implementation to handle this situation through websocket communication.

**Comment by kannan-xiao4** [comment]
@grayhong 
`OnDisconnect` in `SingleConnection.cs` is invoked if another peer connection closed. 
Or implement `IDeletedConnectionHandler` on your component.

Can't satisfy your requirement?

**Comment by grayhong** [comment]
Oh! I just found this event and it works! Thank you!
