### ISSUE TITLE
[BUG]: Mic volume is too low

### ISSUE THREAD

**Issue by grayhong** [Unity-Technologies/UnityRenderStreaming#660]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS: Editor (Windows 10)
* Unity version: 2021.2
* Graphics API: DirectX 
* Browser: Google Chrome Version 98
* com.unity.renderstreaming version 3.1.0-exp.3
* com.unity.webrtc version 2.4.0-exp.6
```

### Steps To Reproduce

1. Play Bidirectional Sample Scene in Unity editor and web browser bidirectional sample in localhost.
2. The volume from web browser is low that I can barely hear it.

### Current Behavior

I tested this because this low volume problem happened on ios testing between two iphone devices.
My screen is delivered very well, but the audio is too quite. (It's not completely mute, as I can hear it if I listen carefully)
This also happened in previous UnityRenderStreaming release (3.1.0-exp.2) and I upgraded to 3.1.0-exp.3 as the maintainer said there was a fix regarding audio streaming).

I tried to amplify the volume by doing below in `MicrophoneStreamSender.cs`
```

        protected override void OnAudioFilterRead(float[] data, int channels)
        {
            for (int i = 0; i < data.Length; i++)
            {
              data[i] *= 6;
            }
            ...
        }
```
and now volume got increased but the quality is really bad. (a lot of noise and jitter)

Any ideas to fix this problem?

Thank you.

### Expected Behavior

Louder voice from the peer.

**Comment by grayhong** [comment]
I also tested with turning off the `mute` option in `MicrophoneStreamSender.cs` which I believe it plays the input of the microphone, and the sound is much louder than it was in the web browser (the sound received by the peer).

**Comment by kannan-xiao4** [comment]
@grayhong 
If the implementation of volume setting is different between Unity and browser, we will try to match the behavior of the browser.

**Comment by kannan-xiao4** [comment]
@grayhong Have you any update?

**Comment by kannan-xiao4** [comment]
@grayhong We will the issue will be closed. Is there anything?

**Comment by grayhong** [comment]
Sorry for the late reply. I solved this issue and it was not caused by URS but the ios speaker setting. Thanks for the answer!
