### ISSUE TITLE
[REQUEST]: Make RemoteInput Public class

### ISSUE THREAD

**Issue by vmohan7** [Unity-Technologies/UnityRenderStreaming#661]
### Is your feature request related to a problem?

Minor problem

### Describe the solution you'd like

In #644, RemoteInput was made to be an internal class. I actually preferred having it as a public class, which made it easier to use in the VR Render Streaming project. As of 3.1.0-exp-3, I now have to make a copy of RemoteInput in order to use it in my name space.

Not sure if this was intended or not. 

### Describe alternatives you've considered

Making a copy of remote input

**Comment by karasusan** [comment]
@vmohan7
Hi, I would like to deprecate the module near the future, so I suggest you can copy this class to Assets folder in your project.

**Comment by karasusan** [comment]
@vmohan7
What do you think?

**Comment by kannan-xiao4** [comment]
@vmohan7 If you have no update,  We will the issue will be closed. Is there anything?

**Comment by vmohan7** [comment]
If deprecation is in the roadmap, yes I will make a copy. Thanks!
