### ISSUE TITLE
Android have no streaming

### ISSUE THREAD

**Issue by coolcup74** [Unity-Technologies/UnityRenderStreaming#666]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS: Android 10 mobile & Windows 10 laptop
* Unity version: 2020.3.31f1
* Graphics API:
* Browser: Chrome
```

### Steps To Reproduce

I just followed unity user manual for streaming from android mobile to web browser.
and I surely checked IL2CPP and ARM64 for android mobile.

Seeing the log,
It looks like websocket open issue.

android log #1 [Mobile]
03-28 00:35:36.667 21435 21721 I IL2CPP  : 3/28/2022 12:35:36 AM|Fatal|ThreadPoolWorkQueue.Dispatch|Connection refused
03-28 00:35:36.670 21435 21721 I Unity   : Signaling: WS connection closed, code: 1006

android log #2 [Oculus]
03-28 00:20:36.359  1575 16071 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1057 android.content.ContextWrapper.sendBroadcast:448 X.o8.A00:143 X.oO.A00:17 X.oO.handleMessage:90
03-28 00:20:36.361 15498 15641 I Unity   : Signaling: WS connection closed, code: 1006

### Current Behavior

Unity editor standalone play is ok for just screen streaming.
Android app with the same codes have no streaming.

**Comment by karasusan** [comment]
@coolcup74 
It seems the signaling process is not completed.

I would like to check whether the samples works correctly or not.
Could you check the **Host address** in the menu scene?
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/samples.html

**Comment by coolcup74** [comment]
I've check samples as per your guide.
I think that this issue is from mobile side can not reach to localhost port, 127.0.0.1.
What shall I do for this case?

**Comment by karasusan** [comment]
@coolcup74
Please check the instruction for launching web app, and when you run the command, you can see some URLs on the terminal, one of them can use for your local network. like 192.168.11.11.
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/launch-webapp.html

**Comment by coolcup74** [comment]
Yes. I surely did but, It fails...

**Comment by karasusan** [comment]
Have you solved the issue? 
You need to fix the issue for connecting Websocket between two devices.

**Comment by coolcup74** [comment]
Not yet...
I have no idea what to do furthur actually..

**Comment by karasusan** [comment]
@coolcup74
We want to help you but no information for your issue.
