### ISSUE TITLE
[BUG]: The latest version of "broadcast" demo cannot work properly

### ISSUE THREAD

**Issue by ByeTragedy** [Unity-Technologies/UnityRenderStreaming#667]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS:Windows 10
* Unity version:Unity 2020.3.26f1c1
* Graphics API:DirectX11
* Browser:Google Chrome
```

### Steps To Reproduce

The dependency is WebRTC 2.4.0-exp.6 and Input System 1.3.0. When I run the demo,unity has crushed for the first time .Then I restart the project ,the web has nothing in player ,just the black screen ,to prove that the rendering texture stream has been destroyed?

**Comment by karasusan** [comment]
Could you give me the error log?

**Comment by ByeTragedy** [comment]
There are no error log both in unity and chrome, just has printed the same console messages as the 3.1.0-exp.2 executed properly.The only difference is that the browser has not rendered textures through 3.1.0-exp.3,but could succeed through 3.1.0-exp.2.

**Comment by ByeTragedy** [comment]
![image](https://user-images.githubusercontent.com/46556044/160323942-b55b51ba-e906-4c94-82a0-17c40f24d21f.png)

**Comment by karasusan** [comment]
Sure, Please attach Editor.log instead.

**Comment by ByeTragedy** [comment]
[Editor.log](https://github.com/Unity-Technologies/UnityRenderStreaming/files/8359908/Editor.log)

**Comment by karasusan** [comment]
@ByeTragedy 
Are you testing on the same PC?
And, is it same issue?
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/485

**Comment by karasusan** [comment]
@ByeTragedy
Please check the webserver is the latest version.

**Comment by ByeTragedy** [comment]
I tested on two PC. The webserver is on the other,and I updated the webserver to find nothing has changed.

**Comment by ByeTragedy** [comment]
I tested on localhost and nothing changed, still black screen on web.

**Comment by ByeTragedy** [comment]
I never enable "hardware encoder support" from the beginning.

**Comment by karasusan** [comment]
I think the signaling process is no problem.
We need to check more deeply to solve the issue. 

Can you check the WebRTC sample?
https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/sample.html
