### ISSUE TITLE
[BUG]: Apple Silicon Support

### ISSUE THREAD

**Issue by ryneal** [Unity-Technologies/UnityRenderStreaming#668]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS: macOS Monteray 12.2
* Unity version: 2020.3.28f1
* Browser: Chrome
```

### Steps To Reproduce

Run sample apps

### Current Behavior

Sample projects run, but unable to receive the stream from the browser.

README details apple silicon is not currently supported.

### Expected Behavior

Sample projects to work on Apple Silicon. 

### Anything else?

Requesting Apple Silicon support to be added.

**Comment by karasusan** [comment]
@ryneal
I guess it should work using Rosetta2, but I am not sure.

Could you try the arm64 runtime instead of Rosetta2 ?
You need Unity2021 to build arm64 binary.

**Comment by karasusan** [comment]
Looks like signaling process failed.
Could you check the status of webapp?
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/webapp.html

**Comment by ryneal** [comment]
I have been running the webapp through the local build i.e. `./test_webapp.sh`

I have now run the webapp as per the manuals instructions (download & run), and now the socket error code has changed to 1002.

I've attached the webapp output & the browser network calls below.

```
GET /receiver/images/Play.png 200 0.589 ms - 483163
GET / 200 2.805 ms - 2324
PUT /signaling/ 200 51.431 ms - 52
GET /signaling/connection 200 17.064 ms - 18
POST /signaling/candidate 200 4.004 ms - 2
GET /signaling/offer?fromtime=1648622617434 200 13.918 ms - 13
GET /signaling/answer?fromtime=1648622617434 200 0.865 ms - 14
GET /signaling/candidate?fromtime=1648622617434 200 0.219 ms - 17
GET /receiver/images/FullScreen.png 200 51.762 ms - 19164
POST /signaling/offer 200 1.430 ms - 2
POST /signaling/candidate 200 0.379 ms - 2
GET /signaling/connection 304 0.583 ms - -
GET /signaling/offer?fromtime=1648622647000 200 0.455 ms - 13
GET /signaling/answer?fromtime=1648622647000 200 0.222 ms - 14
GET /signaling/candidate?fromtime=1648622647000 200 0.262 ms - 17
```
<img width="598" alt="Screenshot 2022-03-30 at 07 45 48" src="https://user-images.githubusercontent.com/11350526/160770159-84575947-84f6-4325-b839-f739fb044ffc.png">

Any assistance or guidance on debugging this would be greatly appreciated!

**Comment by kannan-xiao4** [comment]
@ryneal 
An error occurs because the client is trying to connect with Websocket while WebServer is running with Http.
Please start webserver in Websocket mode (try  this `./webserver -w`)

**Comment by kannan-xiao4** [comment]
@ryneal 
Do you have any updates?
If not, this issue will be closed.

**Comment by ryneal** [comment]
@kannan-xiao4 I can confirm this guidance provided got it working!

I will close the issue, however it may be worthwhile updating the documentation, as this solution does work on M1 Macs
