### ISSUE TITLE
[BUG]: 当我处于单机状态，服务和客户端都在同一台电脑时，客户端无法播放视频，如果连接到局域网络，或者热点时，视频就恢复正常播放了

### ISSUE THREAD

**Issue by 1652185936** [Unity-Technologies/UnityRenderStreaming#673]
### Package version

3.1.0-exp.3

### Environment

```markdown
操作系统：Windows10
统一版本：统一 2021.2
图形 API：DirectX11
浏览器：谷歌浏览器版本 97
```

### Steps To Reproduce

拔掉网线处于单机状态，然后进行正常操作。

### Current Behavior

单机时无法播放视频

### Expected Behavior

找到错误原因

### Anything else?

是否是webrtc必须处于局域网状态呢。

**Comment by kannan-xiao4** [comment]
Do you have any updates?
If not, we will close Issue.
