### ISSUE TITLE
[BUG]: 无法正常连接报Signaling: WS connection closed, code: 1002

### ISSUE THREAD

**Issue by Rain624** [Unity-Technologies/UnityRenderStreaming#678]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS:Windows11
* Unity version:Unity 2020.3.30
```

### Steps To Reproduce

服务器正常开启，但是unity端运行显示两条log：1、Signaling: Connecting WS ws://localhost  2、Signaling: WS connection closed, code: 1002

**Comment by kannan-xiao4** [comment]
@Rain624 
Did you add the `-w` argument when starting the server?
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/sample-broadcast.html

**Comment by Rain624** [comment]
> @Rain624 Did you add the `-w` argument when starting the server? And do you following manual step? https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/sample-broadcast.html
应该是这个原因，我在package.json中修改了端口并添加了-w可以正常使用了

**Comment by kannan-xiao4** [comment]
@Rain624 
Did you solve the problem?
If so, we will close this issue.

**Comment by Rain624** [comment]
> @Rain624 Did you solve the problem? If so, we will close this issue.

是的，已经解决了

**Comment by caoliyong2** [comment]
I have the same problem. How did you solve it

**Comment by caoliyong2** [comment]
@Rain624 I have the same problem. How did you solve it
