### ISSUE TITLE
[REQUEST]: Encode on a separate thread?

### ISSUE THREAD

**Issue by ZeoWorks** [Unity-Technologies/UnityRenderStreaming#679]
### Is your feature request related to a problem?

Hi, when using either software or hardware encoding;
It seems that the in-game frame rate is limited by the successful encoding frame rate.

Can we have the encoding done on a separate thread so the main thread is free to have as high of a frame rate as it likes?

**Comment by karasusan** [comment]
We discussed about the same issues here. 
https://github.com/Unity-Technologies/com.unity.webrtc/issues/632#issuecomment-1110478225

We are going to support controlling framerate for the next milestone.

**Comment by karasusan** [comment]
memo: WRS-229

**Comment by ZeoWorks** [comment]
> We discussed about the same issues here. [Unity-Technologies/com.unity.webrtc#632 (comment)](https://github.com/Unity-Technologies/com.unity.webrtc/issues/632#issuecomment-1110478225)
> 
> We are going to support controlling framerate for the next milestone.

Having the frame rate controlled by another variable is a different thing than it being encoded on a separate thread no?

**Comment by pilzinho** [comment]
+1 
De-/Encoding video on its own thread would be absolutely essential for this type of application if this is not already the case.

**Comment by karasusan** [comment]
@ZeoWorks
In the next version of WebRTC package, the encoding process runs on the worker thread, not rendering thread. There was one more problem with that, the encoding framerate is limited by the in-game framerate.

**Comment by rocco-haro** [comment]
@karasusan may you please share a link to the file where the encoding process takes place?

**Comment by karasusan** [comment]
@rocco-haro
The encoding process is implemented in the native code.
https://github.com/Unity-Technologies/com.unity.webrtc/tree/develop/Plugin~

**Comment by rocco-haro** [comment]
@karasusan thanks, but that link leads to a 404 page.

**Comment by ZeoWorks** [comment]
> ~

Link seems broken, you need to include ~ at the end of it.

**Comment by karasusan** [comment]
We already merged the fix which updates the dependencies of WebRTC package, so you can test the encoder on a separated thread and check the performance. 
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/683
