### ISSUE TITLE
[BUG]: Input not work through web browser and fullscreen mapping error

### ISSUE THREAD

**Issue by gawinwong** [Unity-Technologies/UnityRenderStreaming#680]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS: ubuntu 18.04
* Unity version: 2020.3.3f1
* Graphics API: Vulkan/Opengl
* Browser: chrome 100.0.4896.75
```

### Steps To Reproduce

1. start linux version webapp "./webserver -w"
2. use sample "Broadcast"
3. browser open tab "http://127.0.0.1/receiver/index.html"

### Current Behavior

can not process the input actions

### Expected Behavior

can press the button and the picture changes 

### Anything else?

![image](https://user-images.githubusercontent.com/13494956/167987778-41de1025-105e-4551-8c26-712d0b50d3cd.png)

**Comment by karasusan** [comment]
Have you checked this page?
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/use-inputsystem.html

**Comment by gawinwong** [comment]
Alright, 2020.3 need settings same as "For Unity 2021.2", it works now.

**Comment by sx351967213** [comment]
@karasusan When will version 3.1.0-exp.4 be released?

**Comment by karasusan** [comment]
@sx351967213
Probably, in August.

**Comment by karasusan** [comment]
@gawinwong
Should I fix the doc?

**Comment by gawinwong** [comment]
> @gawinwong Should I fix the doc?

Yes, please update the doc.

In addition, if I click the full screen button, the input mapping is not accurate, the mouse position no longer corresponds to the button I set, is there any way to fix it?

**Comment by gawinwong** [comment]
I found the method to correct the mapping bug. Because 'resize' event is not working for div, we can use ResizeObserver to monitor div dimension changes.
```diff
#client/public/js/sender.js
- this._elem.addEventListener('resize', this._onResizeEvent.bind(this), false);
+const observer = new ResizeObserver(this._onResizeEvent.bind(this));
+observer.observe(this._elem);
```

**Comment by karasusan** [comment]
@gawinwong
Great, could you make the pull request?

**Comment by karasusan** [comment]
URS-446
