### ISSUE TITLE
[REQUEST]: Furioos signaling for native client app

### ISSUE THREAD

**Issue by robco5** [Unity-Technologies/UnityRenderStreaming#689]
### Is your feature request related to a problem?

Hi All!

I've tried Furioos signaling with my app deployed to Furioos. My client is not a web-browser app, but rather another native app based on render streaming. However, I was not able to run it properly. Is such setup even possible?

Thank you!

### Describe the solution you'd like

Enable Furioos signaling for native clients.

**Comment by karasusan** [comment]
memo: URS-448

**Comment by karasusan** [comment]
@robco5
Thank you for feedback.
Unfortunately, we have not supported yet but your idea is so valuable for many developers. We will discuss about your issue in our team and make a plan to support.

**Comment by robco5** [comment]
Thank you for your interest and support on this, highly appreciated!

I'd be happy to go into deeper product talks and share some of the roadmap in more details. Let's schedule a video call, if interested. robert@digitalnationent.com

**Comment by robco5** [comment]
@karasusan , do you want to get on a call?

**Comment by karasusan** [comment]
@robco5
Thank you for invitation for a call but I don't have time to get it, unfortunately.
Your issue is escalated our backlog. Thank you again!

**Comment by robco5** [comment]
@karasusan 
No problem, looking forward! Thank you!

**Comment by karasusan** [comment]
Furioos has already been discontinued. I close this ticket.
