### ISSUE TITLE
[BUG]: name `EncoderType` could not be found

### ISSUE THREAD

**Issue by lookoutking** [Unity-Technologies/UnityRenderStreaming#695]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS: Windows 10
* Unity version: 2020.3.33f1
* Graphics API: DirectX11
* Browser:
```

### Steps To Reproduce

1. Install WebRTC 2.4.0-exp.7 by the package manager
2. Install Unity Render Streaming 3.1.0-exp.3 by the package manager
3. The error message show up.

### Current Behavior

When I install WebRTC and Unity Render Streaming in Unity, the error show up as the attached figure.
![image](https://user-images.githubusercontent.com/7221471/172554906-b0c1f344-c626-4a76-8a7e-f3032ce08228.png)
It seems that the missing of  `EncoderType` in WebRTC namespace makes this happened.

**Comment by karasusan** [comment]
Have you tried to install according this docs?
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/installation.html

**Comment by lookoutking** [comment]
Yes, I followed the document to install the Unity Render Streaming package, but I installed the latest WebRTC (2.4.0-exp.7) package first.

**Comment by karasusan** [comment]
@lookoutking
It might be conflict the dependencies. Can you remove WebRTC package from Package Manager, or try to clean install?

**Comment by lookoutking** [comment]
Thank you for your help. I tried to clean install and it works.
