### ISSUE TITLE
[BUG]:   Run after the WebBrowserInput.unity is published, Not in the Unity editor environment, videoplayer/index.html will not show the video

### ISSUE THREAD

**Issue by chenweichao199111** [Unity-Technologies/UnityRenderStreaming#699]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS: Windows10
* Unity version: Unity 2020.3.25
* Graphics API: DirectX11
* Browser: Google Chrome Version 102.0.5005.63
```

### Steps To Reproduce

1.Run webserver
2.Publish WebBrowserInput.unity
3.Run exe
4.Open Browser, visit videoplayer/index.html

**Comment by kannan-xiao4** [comment]
@chenweichao199111 
Now, we don't maintenance  `WebBrowserInput.unity`.
Please try `Broadcast.unity` and `receiver/index.html` combination.

Please let me know if you have any reason to use `WebBrowserInput`.

**Comment by karasusan** [comment]
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/702

**Comment by karasusan** [comment]
Could you try Unity 2021.3 instead of Unity 2020.3?
