### ISSUE TITLE
[BUG]: Open Browser, visit receiver/index.html，The unity ui button can only be clicked if the window size changes

### ISSUE THREAD

**Issue by chenweichao199111** [Unity-Technologies/UnityRenderStreaming#702]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS:Windows10
* Unity version: Unity 2020.3.25
* Graphics API: DirectX11
* Browser: Google Chrome Version 102.0.5005.115
```

### Steps To Reproduce

1. Open Browser, visit receiver/index.html
2. unity ui button can't be clicked

**Comment by karasusan** [comment]
Please check this doc.
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/use-inputsystem.html
