### ISSUE TITLE
[BUG]: I can`t use this in Ubuntu with HDRP version

### ISSUE THREAD

**Issue by martint028** [Unity-Technologies/UnityRenderStreaming#732]
### Package version

3.1.0-exp.4

### Environment

```markdown
* OS:Ubuntu 18.04.6 LTS and Ubuntu 20.04.4 LTS
* Unity version:2021.3.5f1 and 2020.3.37f1
* Graphics API:Vulkan Instance Version: 1.1.70
* Browser:Chrome and Firefox

I use windows to build Windows version, everything is right, but when select Linux version, Mono or IL2cpp, the RenderPipeline or WebBrowserInput crash without log, 
Unity ordinary pipeline works normally
```

### Steps To Reproduce

1. I followed the documentation steps exactly to deploy Ubuntu 
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/index.html

2. run in the system
3. Then it crashed, the crash log can't see the crash location

**Comment by martint028** [comment]
[Player.log](https://github.com/Unity-Technologies/UnityRenderStreaming/files/9287715/Player.log)

**Comment by martint028** [comment]
![image](https://user-images.githubusercontent.com/12568845/183584435-349ad420-7391-4b98-af40-55b62762a71b.png)

**Comment by martint028** [comment]
Whether this project supports the rendering of the HDRP pipeline on Linux, I have not found any relevant discussions, or rendering in Docker, I have not seen relevant documents, there are many articles discussing pixel steaming in Unreal, and the discussion on unity is a little bit few

**Comment by karasusan** [comment]
@martint028
Sorry but 3.1.0-exp.4 is not released on Package Manager, it is not stable yet.
Surely, we haven't make the document for using it with docker.

**Comment by karasusan** [comment]
@martint028
 I release the latest package last week.
Can you check it?

**Comment by karasusan** [comment]
@martint028
Thank you for cheking.
Please make the new issue if you have other problems.
