### ISSUE TITLE
[BUG]: Resolution causes crash

### ISSUE THREAD

**Issue by tututu411** [Unity-Technologies/UnityRenderStreaming#733]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS:windows 11
* Unity version:Unity 2021.3.1f1c1
* Graphics API:DirectX11
* Browser:Chorme 104.0.5112.81
```

### Steps To Reproduce

Using a custom 2560*1080 resolution, sometimes it works and sometimes the editor crashes.

**Comment by tututu411** [comment]
Browse the problem area and find the same problem. In which version do you plan to fix it?

**Comment by karasusan** [comment]
@tututu411
Dows this crash occur when the resolution is lower than 2560*1080 ?
