### ISSUE TITLE
[BUG]: 高版本unity无法正常使用RenderStreaming

### ISSUE THREAD

**Issue by Rain624** [Unity-Technologies/UnityRenderStreaming#734]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS:Windows11
* Unity version:Unity 2021.2
* Graphics API:DirectX11
```

### Steps To Reproduce

在Unity2021.2.11f1中无法正常使用云渲染功能，服务器正常开启，网页正常显示画面，但是无法用鼠标移动镜头，但键盘可以正常响应。

**Comment by Minamiyama** [comment]
大概你需要在另外一台电脑上打开，我也是本机上开网页使用不会响应

**Comment by Rain624** [comment]
你的unity版本是2021吗？我这边测试的是2020版本是没有问题的，但是2021版就不能操作了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月17日(周三) 下午4:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Unity-Technologies/UnityRenderStreaming] [BUG]: 高版本unity无法正常使用RenderStreaming (Issue #734)




 
大概你需要在另外一台电脑上打开，我也是本机上开网页使用不会响应

**Comment by Minamiyama** [comment]
> 

我用的是2022

**Comment by ZeoWorks** [comment]
Same issue occurs for me also.
This happens if the game window is not focused.  So if you're testing on the same PC it will not work.

This is not an ideal solution either, as some users are hoping to run the game in the background like on a server.

**Comment by ZeoWorks** [comment]
The old input system before the switch to unity.inputsystem worked a whole lot better.
No idea why they changed this.

**Comment by karasusan** [comment]
@Rain624
How about Unity 2021.3 latest version?

**Comment by karasusan** [comment]
I closed this ticket because the reporter haven't replied. Please reopen this issue if you have the additional info.
