### ISSUE TITLE
[BUG]: Multiplay Sample can't send img to browser

### ISSUE THREAD

**Issue by projoy** [Unity-Technologies/UnityRenderStreaming#754]
### Package version

3.1.0-exp.4

### Environment

```markdown
* OS:Windows 10
* Unity version: 2021.3.5f1c1 Personal
* Graphics API: DX 11
* Browser:chrome 102.0.5005.63
```

### Steps To Reproduce

I am running the multiplay sample of the exp.4
 when i open the broswer and click the "play" button, the unity app can add a player of "ball", and it can send keyborad and mouse message to the unity app, but, the browser's image is black, there is no image on the screen.

The log like this:
 **Screen position out of view frustum (screen pos 0.000000, -nan(ind)) (Camera rect 0 0 1280 720)**

### Current Behavior

The screenshot like this:
<img width="1355" alt="图片111" src="https://user-images.githubusercontent.com/1763252/187848862-6bb59c3b-c988-4ff1-80d2-33b6ee75b516.png">

**Comment by karasusan** [comment]
Thank you for reporting the issue. We are fixing this bug in the PR.
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/751

**Comment by projoy** [comment]
thank you!!!
