### ISSUE TITLE
[BUG]: Multiplay sample crashed on ubuntu20.04 

### ISSUE THREAD

**Issue by projoy** [Unity-Technologies/UnityRenderStreaming#761]
### Package version

3.1.0-exp.4

### Environment

```markdown
* OS:Ubuntu 20.04
* Unity version: 2021.3.5f1c1 Personal
* Graphics API: OpenGLCore
* Browser: chrome 102.0.5005.63
  Graphic device:  GeForce RTX 3090
  CUDA SDK: 11.7.20220504
```

### Steps To Reproduce

hello
   i am running Multiplay sample of exp.4 on ubuntu20.04.  When it receive a signaling of client , it is crashed immediately! It happens every time.   and it happened on exp.3 too.

   1.project settings->Player->Graphics APIs for Linux
        choose "OpenGLCore"
   2.Target Platform : linux
   3.Build 
   4.Runing Multiplay sample app on ubuntu20.04
   5.Open a browser, and click "Play" button
   6.Multiplay sample app crashed

### Current Behavior

   I have opened the nativate log flag, the log like this:
   _**[009:727](OpenGLGraphicsDevice.cpp:281): cuGraphicsD3D11RegisterResource error999**_
the detail  is in this log file.
[Player (7).log](https://github.com/Unity-Technologies/UnityRenderStreaming/files/9502100/Player.7.log)

   the error was throwed in OpenGLGraphicsDevice.cpp 281
<img width="971" alt="E44B1545-132B-458b-93B9-E10F6BD42628" src="https://user-images.githubusercontent.com/1763252/188772355-4166b512-65b3-4b78-8738-24bc321d07dd.png">

   **otherwise,** if I choose "Vulkan", and it will work normal.  But it's only can open three browser, if i open the fourth browser, it will can't show image, and the graphic device is  only use 30%，how can i open more browser? 

 can you help me?
   thank you

**Comment by karasusan** [comment]
Please see the column **Max # of concurrent sessions** in this matrix. GeForce series has a restriction.
https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new#Encoder

Of course, we need to fix the crash bug, but you cannot use multiple sessions unlimitedly even if the bug would be fixed.

**Comment by projoy** [comment]
OK, I see.  Thank you! 👍

**Comment by karasusan** [comment]
memo: URS-507

**Comment by projoy** [comment]
thank you
