### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Zumbalamambo** [Unity-Technologies/UnityRenderStreaming#780]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS:Ubuntu 20.0.4
* Unity version:2022.16.1f1
* Browser:Chrome
```

### Steps To Reproduce

sudo ./webserver

### Current Behavior

```
start as public mode
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)

```

### Anything else?

How do I pass the url and the port via cli while running webserver?

**Comment by karasusan** [comment]
You can see options for the webserver here.
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/webapp.html
