### ISSUE TITLE
[BUG]: signaling.js:43 Uncaught (in promise) ReferenceError: logger is not defined     at Signaling.loopGetOffer (signaling.js:43:7)

### ISSUE THREAD

**Issue by zhaochao10** [Unity-Technologies/UnityRenderStreaming#782]
### Package version

Others

### Environment

```markdown
* OS:Windows11
* Unity version:2019.4.4
* Graphics API:Auto Graphics API for Windows
* Browser:Google Chrome Version 105.0.5195.127
```

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/94681796/191169634-0cf21cdf-598d-4ec1-8945-174f137c0d45.png)
![image](https://user-images.githubusercontent.com/94681796/191169707-281218df-879e-4d77-8d84-0b7c2ef07623.png)

### Current Behavior

I ran WebBrowserInput, then opened it in a local browser, and it showed signaling. Js :43 Uncaught (in promise) ReferenceError: Logger is not defined  
At Signaling. LoopGetOffer (Signaling. Js :43:7), I read the document carefully, I wonder what the problem is? 

### Expected Behavior

After the WebBrowserInput scene of Unity Render Streaming runs, the screen is black when opened in Google Chrome, and there is an error message signaling.js:43 Uncaught (in promise) ReferenceError: logger is not defined
     at Signaling.loopGetOffer (signaling.js:43:7) I don't know what to do, can anyone help?

### Anything else?

![image](https://user-images.githubusercontent.com/94681796/191176559-ae011b9b-5d90-4206-ac12-45f007654bd5.png)
![image](https://user-images.githubusercontent.com/94681796/191176698-0ee2daf0-2cb2-4ab1-bcf1-1947a0f9b2e9.png)

**Comment by karasusan** [comment]
Hi, which version of the package are you using? Is it `3.1.0-exp.3` ?

**Comment by karasusan** [comment]
@zhaochao10
Could you reply?
