### ISSUE TITLE
[BUG]: Multiplay 

### ISSUE THREAD

**Issue by gushenjie** [Unity-Technologies/UnityRenderStreaming#794]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS:Windows10
* Unity version:Unity 2020.3.29
* Graphics API:DirectX11
* Browser: Google Chrome Version 97
```

### Steps To Reproduce

The Multiplay sample can stream video and audio to multi Unity applications. This sample works with the combination of Unity-Unity or Unity-Browser. I didn't see this feature in the Multiplay Demo. Do I need to enable it?

**Comment by karasusan** [comment]
Have you read this doc?
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/sample-multiplay.html

**Comment by karasusan** [comment]
@gushenjie
Any questions?

**Comment by gushenjie** [comment]
solve it
