### ISSUE TITLE
[BUG]: Failed to use locally packed WebApp

### ISSUE THREAD

**Issue by xiasun** [Unity-Technologies/UnityRenderStreaming#795]
### Package version

3.1.0-exp.4

### Environment

```markdown
* OS: Windows 11
* Unity version: 2021.3.10
* Graphics API: DirectX11
* Browser: Chrome 106
```

### Steps To Reproduce

I ran `npm run pack` to pack a webserver.exe with npm run pack locally ( with no modification on commit 2080d509b74bda6af9c14d3014a4ee612b935906 )

After webserver.exe was generated, I started it with `webserver.exe -w`.

Then I start the game, and launch page `http://localhost/videoplayer/index.html` in chrome, following error was printed from browser console:
```
 Failed to load resource: the server responded with a status of 404 (Not Found)    signaling.js:1 
 Failed to load resource: the server responded with a status of 404 (Not Found)    peer.js:1 
 Failed to load resource: the server responded with a status of 404 (Not Found)    logger.js:1 
 Failed to load resource: the server responded with a status of 404 (Not Found)    keymap.js:1 
```
If I run server with `run.bat`, everyting is fine.

**Comment by xiasun** [comment]
Thank you @ChanceTheMaker, I currently copied the four missing js files into a newly created `module` folder to make the packing process work, as a temp solution. 

But I can't get the point why would it work to call the packed `webserver` program inside container? There seems to be no difference between calling direcly from host system?

**Comment by karasusan** [comment]
@xiasun
We reproduced the issue and will fix soon. Thank you.

**Comment by karasusan** [comment]
memo: URS-543

**Comment by yslab1** [comment]
@karasusan Any news here? When it be possible to fix it?

**Comment by xiasun** [comment]
looks great!
