### ISSUE TITLE
[BUG]: No ability to handle input by more than one client

### ISSUE THREAD

**Issue by Rhanjie** [Unity-Technologies/UnityRenderStreaming#802]
### Package version

3.1.0-exp.4 _(nevest WebApp and RenderStreaming package from /develop branch)_

### Environment

```markdown
* OS: Windows 10 x64
* Unity version: Unity 2021.3.0f1
* Graphics API: DirectX11
* Browser: Brave v1.45.118
```

### Steps To Reproduce

1. Download template project and use the local render streaming package from cloned repository
3. Build the latest web application from source and run with websocket mode
4. Run broadcast example with default options
5. Open streaming in browser using two devices or just several browser tabs (more than one)

### Current Behavior

When the other client connects to active stream, the problem appears. For the previous client, either it does not detect touch gestures at all or it is blocked for some reason. After refreshing the previous tab, the client has restored ability to control the application but the second one loses it. The problem occurs even if I use two separated devices like PC and mobile phone.

According to the official response:
> @Rhanjie I haven't assumed that the use-case which multiple users control one camera. The `InputReceiver` class is designed for controlling input by single player [...]

In addition, there is a slight offset in the detected position, which is not very problematic, but makes it a little difficult to use the application. The problem occurs when a second client takes the application focus. Before this situation, the position is ok.

### Expected Behavior

For my application, I would need the ability to operate the application from several connected clients, not just one. In addition, it would be good to eliminate the offset that appears when the second client takes control of the application

### Anything else?

I presented the problem in the video below:
https://www.youtube.com/watch?v=rFifZz6fXkI

**Comment by karasusan** [comment]
Thank you @Rhanjie!

I consider this issue and one of the solution is making InputReceiver per users. I guess customising Multiplay sample is good for the first step.

**Comment by Rhanjie** [comment]
Thank you for quick response. Customizing the multiplay sample allowed me to understand better the whole system and add the functionality that I wanted. I rewrote my application and now everything works perfectly! 🎉 

If anyone needed any advice, in this case, just set the guest prefabs to point to one main ball (from the host). This will allow each connected client to operate on the same object. Following this line of thinking, you can already do everything else.
