### ISSUE TITLE
[BUG]: Video quality and latency are substantially worse than Quest Link Air or Virtual Desktop in LAN

### ISSUE THREAD

**Issue by JoaoReallyInteractive** [Unity-Technologies/UnityRenderStreaming#803]
### Package version

3.1.0-exp.4

### Environment

```markdown
* OS: Windwos 10 / Quest (1 & 2)
* Unity version: 2021.3.8f1
* Graphics API:
* Browser:
```

### Steps To Reproduce

- Run a streamer app on a Windows PC with 1920x1080 resolution, 60 or 30 fps.
- Run a receiver app on Quest

- Video works as expected, however video quality and latency is worse that one would hope for.

### Current Behavior

I've successfully setup a Video Stream with with default codec from Windows PC to Quest. That works ok-ish.
However, when compared with other apps that do similar things, both the video quality and the latency is underwhelming.

I've tried manually setting the codecs with no improvements and with the H264 codec, only the Constrained Baseline profile worked.

### Expected Behavior

I'd expect the quality and speed to match these other apps that stream from the Desktop to Quest over LAN.

**Comment by karasusan** [comment]
@JoaoReallyInteractive 
Can you use the H264 codec on Oculus Quest? 
I've never checked it on the Oculus Quest.

**Comment by JoaoReallyInteractive** [comment]
Yes. However, only the Constrained Baseline profile works.

**Comment by karasusan** [comment]
To use other profiles, sender and receiver should support same profiles to use it.
I guess the receiver side doesn't support the profiler which you want to use.

**Comment by karasusan** [comment]
@JoaoReallyInteractive
Any questions?

**Comment by JoaoReallyInteractive** [comment]
I don't at the moment. I haven't had the time to explore this further.
I believe Quest does support other profiles besides Constrained Baseline though.

Maybe this link is of use:
https://creator.oculus.com/blog/encoding-high-resolution-360-and-180-video-for-oculus-go/

I'll close this issue since I won't be able to assist with more info at the moment.
