### ISSUE TITLE
[BUG]: All Scene UI and inputAction for iOS Safair does not interact

### ISSUE THREAD

**Issue by martinmi** [Unity-Technologies/UnityRenderStreaming#807]
### Package version

3.1.0-exp.4

### Environment

```markdown
* OS:Window
* Unity version:2021.3.13f1
* Graphics API:
* Browser:IOS safair 12,13,14+
```

### Steps To Reproduce

Use ws and Https mode
In IOS safair, Click Button can  Change Highlighted Color, But No Change Pressed Color and No Click Event
InputAction No Any Event 

In Android is Ok

**Comment by karasusan** [comment]
@martinmi
Is it a same issue?
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/454

**Comment by karasusan** [comment]
@martinmi
Have you checked above?
