### ISSUE TITLE
[BUG]: Firefox not showing video

### ISSUE THREAD

**Issue by ThePatrykOOO** [Unity-Technologies/UnityRenderStreaming#809]
### Package version

3.1.0-exp.4

### Environment

```markdown
* OS: Windows 10 x64
* Unity version: Unity 2021.3.0f1
* Graphics API: DirectX11
* Browser: Firefox (actual the newest)
```

### Steps To Reproduce

1. Run unity, node, frontend app (using WebSocket)
2. Click start to connect with stream
3. Our client has been connected
4. On Firefox I cannot see video stream, I see black background video. However on the Chrome browser everything works perfectly.
5. Click event is sending, but I cannot my video stream

### Expected Behavior

I have to see stream from unity app

**Comment by karasusan** [comment]
We have found the ristriction with the firefox.
Could you check the docs?
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/video-streaming.html

**Comment by kannan-xiao4** [comment]
@ThePatrykOOO
Have you checked above?
