### ISSUE TITLE
Samples cannot be streaming on the Android tablet

### ISSUE THREAD

**Issue by yongliancai** [Unity-Technologies/UnityRenderStreaming#812]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS:windows11
* Unity version:2020.3.30f1
* Graphics API:Directx12
* Browser:Google Chrome Version 108
```

### Steps To Reproduce

1.Run the samples in PC and it run successful.(can streaming in Chrome).
2.Deploy in Sansung Tab A8 and run it, it can't streaming in Google Chrome. 

### Current Behavior

I think the  problem is in URL.
How can I connect to the PC webserver.

**Comment by karasusan** [comment]
@yongliancai
Have you set the signaling URL correctly?
