### ISSUE TITLE
How can I build samples on Android system tablet

### ISSUE THREAD

**Issue by yongliancai** [Unity-Technologies/UnityRenderStreaming#813]
### Package version

3.1.0-exp.4

### Environment

```markdown
* OS:windows11
* Unity version:2020.3.30f1
* Graphics API:Direct12
* Browser:Google Chrome108
* Android device: Sansung Tab A8
```

### Steps To Reproduce

Where are the example teaching files

**Comment by karasusan** [comment]
What kind problem are you having?

**Comment by yongliancai** [comment]
Follow the sample, there is no way to live broadcast after pouring to the tablet, I guess the part of the URL is not connected to the PC SERVER (localhost)

**Comment by yongliancai** [comment]
Do you have relevant documents?

**Comment by karasusan** [comment]
@yongliancai
You need to set IP address on the mobile device.
Please see the docs for samples.

https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/sample-receiver.html

**Comment by yongliancai** [comment]
How to set IP address?And Get my IP address

**Comment by yongliancai** [comment]
![image](https://user-images.githubusercontent.com/74762143/208835632-427744ef-235b-49fb-a00b-c8520d7f6a46.png)
![image](https://user-images.githubusercontent.com/74762143/208835682-d19ef94d-1cce-40e3-b551-390ad1d3c4dc.png)

**Comment by karasusan** [comment]
@yongliancai
If you want to test on intranet, you need to replace `localhost` to `192.168.11.18`.

**Comment by karasusan** [comment]
@yongliancai 
Any questions?
