### ISSUE TITLE
[BUG]: Running Webapp with websocket signaling type causes disconnect after 1.5 minutes

### ISSUE THREAD

**Issue by aidenkoh801** [Unity-Technologies/UnityRenderStreaming#824]
### Package version

3.1.0-exp.4

### Environment

```markdown
* OS: Windows 10
* Unity version: unity 2021.3.15f1
* Graphics API: DirectX12
* Browser:Chrome Version 108
```

### Steps To Reproduce

1. Run node.js application: webserver -w
2. Set signaling type to websocket in Unity
3. Start videoplayer in webapp.

### Current Behavior

After 1 minute and 30 seconds is up, the session is disconnected. Switching to HTTPSignaling is my temporary solution at the moment. Here are the logs:

On Unity-side:
```
Signaling: Receiving message: {"type":"disconnect","connectionId":"753d28a1-5c69-48a7-ae58-67780f20c19e"}
UnityEngine.Debug:Log (object)
Unity.RenderStreaming.Signaling.WebSocketSignaling:WSProcessMessage (object,WebSocketSharp.MessageEventArgs) (at Library/PackageCache/com.unity.renderstreaming@3.1.0-exp.4/Runtime/Scripts/Signaling/WebSocketSignaling.cs:179)
```

There are no obvious warnings or errors in the logs generated webapp-side.

I suspect that a Timeout is occuring, as the disconnect event occurs consistently 1.5 minutes after session starts.

### Expected Behavior

session to remain connected indefinitely while using websocket signaling type, similar to using http signaling type.

**Comment by karasusan** [comment]
It sounds strange. We don't set the timer in the web server for the session. 
Are you trying the package samples?

**Comment by karasusan** [comment]
@aidenkoh801 
Can you reply me?

**Comment by tete1030** [comment]
Had the same problem. In my case it turns out nginx reverse proxy timeout caused the problem. By default nginx automatically disconnect proxied websocket if it's quiet for 30s, and in WebApp the interval of checking WebSocket connection state is 100s, hence you are experiencing around 1m30s disconnect.
