### ISSUE TITLE
[BUG]: Video Stream Sender with the Video Source Type set to Texture does not properly set the texture resolution of the sender

### ISSUE THREAD

**Issue by tim-depthkit** [Unity-Technologies/UnityRenderStreaming#859]
### Package version

3.1.0-exp.5

### Environment

```markdown
* OS: Windows 11
* Unity version: 2020.3.44f1
* Graphics API: Direct3D 11
* Browser: N/A
```

### Steps To Reproduce

1. Add a texture asset to your project that is high resolution, preferably 4096x4096
2. Configure a Video Stream Sender with the Video Source Type set to Texture and and the texture from step 1 set as the texture
3. Configure a video stream receiver in another scene, and note that after connecting the sender and receiver, the receiver reports its video texture resolution is only 1280x720.
4. change the Video Stream Sender Video Source Type to Camera, then choose a custom resolution, like 2048x2048
5. Change the Video Stream Sender Source Type back to Texture, and test again
6. Note that the sent video dimensions are now 2048x2048

### Current Behavior

Regardless of the resolution of the texture, the dimensions sent will always be whatever is configured in the Camera or Screen dimensions, not the dimensions of the texture.
I was not able to configure this custom resolution to be higher than 3840x2160. The receiver refuses to connect when attempting to set the sender to 4096x4096.

### Expected Behavior

When using a Texture source, the VideoStreamSender should either expose the video resolution in the same manner as is done when using Camera or Screen capture, or use the actual resolution of the Texture itself. It looks like there is code to do this within the `source` and `sourceTexture` setters but it is not working as expected.

### Anything else?

It would also be great if we could send resolutions higher than 3840x2160.

**Comment by karasusan** [comment]
memo: URS-595
