### ISSUE TITLE
[BUG]: SignalingManager cant add item

### ISSUE THREAD

**Issue by XiaoMinghui** [Unity-Technologies/UnityRenderStreaming#865]
### Package version

3.1.0-exp.6

### Environment

```markdown
* OS:Win 10
* Unity version:2021.3.15
* Graphics API:DX11
* Browser:Chrome
```

### **SignalingManager cant add item**
![image](https://user-images.githubusercontent.com/36829808/217744533-6e2ee201-f205-4812-8215-5d958c1f3f93.png)

**Comment by karasusan** [comment]
This issue was fixed.
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/863
