### ISSUE TITLE
Receiver Sample that is on the web, but it is inside Unity

### ISSUE THREAD

**Issue by a1ansa1a** [Unity-Technologies/UnityRenderStreaming#879]
I suggest that you create a scan of the same content as the Receiver Sample that is on the web, but it is inside Unity, where it receives the video from within Unity. I tried to make it using Render Streaming, but I did not succeed. Are there any suggestions?

Or how can I make Bidirectional bear more than two connections on one channel, as I want to make a live the same principle as the Live Tik Tok applications ...

I will very appreciate your help

**Comment by eaphone** [comment]
https://github.com/Unity-Technologies/com.unity.webrtc/tree/experimental/webgl-platform
this branch support webgl webrtc. which match your case on the web inside unity. however, it is not merge into main branch or render streaming project.

**Comment by a1ansa1a** [comment]
Well, I tried the version that allows WebGL, but it didn't work and even an error occurred in Unity and it closed. I tried a lot to do a live broadcast, but it did not work for me in any way, although I modified the javascript so that the server meets the requirements of what I want, but the result is the same, anyway I decided to use wowza, it is a better option for the application of live broadcasting, as it will not I have to manually setup or program the server, anyway, thanks for the reply
