### ISSUE TITLE
[BUG]: It’s not available in the 2020.3.15f editor.

### ISSUE THREAD

**Issue by CowenLee** [Unity-Technologies/UnityRenderStreaming#891]
### Package version

3.1.0-exp.6

### Environment

```markdown
* OS: windows 10
* Unity version: 2020.3.15f
* Graphics API: 
* Browser: NVIDIA Quadro P5000
```

### Steps To Reproduce

Import the [RenderStreaming] package (v3.1.0-exp.6) in the package manager.

### Current Behavior

There have two bugs In the editor, so I can't run my project and use the streaming feature.

### Expected Behavior

Bugs fixed.

### Anything else?

![image](https://user-images.githubusercontent.com/91596711/228777084-25b3390c-62ec-4eee-845f-0c22bd8a30f5.png)

**Comment by karasusan** [comment]
Could you try the latest LTS version 2020.3.46f ?

**Comment by CowenLee** [comment]
Thanks, it works fine in the 2020.3.46f version.

**Comment by kannan-xiao4** [comment]
@CowenLee
I'm glad. I close this issue.
