### ISSUE TITLE
[BUG]: SignalingManager ignoring command line argument

### ISSUE THREAD

**Issue by pyropig** [Unity-Technologies/UnityRenderStreaming#895]
### Package version

3.1.0-exp.6

### Environment

```markdown
* OS: Windows10
* Unity version: Unity 2022.2.2f1
* Graphics API: Vulcan/OpenGL
* Browser: Google chrome ver 112.0.5615.137 (64 bit)
```

### Steps To Reproduce

1. Build the project using renderStreaming in Production env
2. run the project unity.exe in cmd with commandline arg -signalingUrl <url>
3. observe the signaling manager ignores the arg and still signals to default setting url

### Current Behavior

Currently, when signaling manager is enabled with run on awake, its Awake() function calls _Run() with a signaling setting created from project default setting. However, _Run() only use parsed commandline argument when it get a null for signaling setting, which means it completely ignores whatever I give it in commandline.

### Expected Behavior

It should correctly take commandline arg when starting from batch.

**Comment by kannan-xiao4** [comment]
memo: URS-613

**Comment by pyropig** [comment]
@karasusan 
Hi, I checked my previous setting in editor and it seems that toggling "use default setting" and "run on awake" open in editor and save the scene will affect this.
In editor, I saved url and port in default setting file so I don't need to write it in editor's field. However, it seems the SignalingManager keep using this default file even when project is built and packed if I don't toggle it off. This make the use of a different port impossible when running the packed project
I can't reproduce the it here now as now I'm manually calling the _Run function to control the SignalingManager and it works good under this situation. I think you can close this and if I came accross this problem again I'll get a more detailed reproduce steps.

**Comment by karasusan** [comment]
@pyropig
Thanks for the detail.

**Comment by karasusan** [comment]
@pyropig
Can you check #934

**Comment by karasusan** [comment]
@pyropig
Please try the new version 3.1.0-exp.7.
This ticket will be closed if no response by the end this week.
