### ISSUE TITLE
[BUG]: Broadcast limitation when using H264 codec

### ISSUE THREAD

**Issue by JohnnyNgo** [Unity-Technologies/UnityRenderStreaming#898]
### Package version

3.1.0-exp.6

### Environment

```markdown
* OS: Windows 10
* Unity version: Unity 2021.3.18f1
* Graphics API: Auto
* Browser: Version 113.0.5672.93 (Official Build) (64-bit)
```

### Steps To Reproduce

Using the broadcast sample scene. Using more than then 4 or 5 additional tabs or PCs to connect.
Switch Video Stream Sender codec to H264 (any profile) and compare with other codecs

### Current Behavior

Broadcasting with H264 seems to work for only 3-4 screens. Any more will not broadcast to new connecting users.

### Expected Behavior

Broadcasting should work for an unlimited amount of users (with other hardware limitations of course). When changing to VP8/VP9/AV1 codecs, it does just that.

**Comment by karasusan** [comment]
I think the reason of this issue is graphics card limitation.
Please check Max of concurrent session in this matrix.
https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

**Comment by Yibiu** [comment]
> 



> > I think the reason of this issue is graphics card limitation. Please check Max of concurrent session in this matrix. https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new
> 
> Do you know if this is only for h264 (hardware)? I did see another pull request about using hardware vs software encoder. Also unsure why the other codecs don't have this limitation

Because it's Nvidia‘s limitation

**Comment by OdCheban** [comment]
@JohnnyNgo  how did you choose h264? I don't have this mode available
