### ISSUE TITLE
[BUG]: Transparent background video show as black background in web

### ISSUE THREAD

**Issue by se7enXF** [Unity-Technologies/UnityRenderStreaming#901]
### Package version

3.1.0-exp.6

### Environment

```markdown
* OS: Windows11
* Unity version: Unity 2021.3.5
* Graphics API: DX11
* Browser: Microsoft Edge 114.0.1823.37
```

### Steps To Reproduce

1. Follow [Unity Render Streaming Tutorial](https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/tutorial.html) and make it work. 
2. Change `Video Source type` to Texture in `Video Stream Sender`.
3. Create a script and attach it to Main Camera, codes in script: 

``` c#
using System.Collections;
using System.IO;
using Unity.RenderStreaming;
using UnityEngine;

public class CaptureTransparent : MonoBehaviour
{
    public VideoStreamSender videoStreamSender;
    public Shader transparentShader;
    RenderTexture rt;
    Texture2D tex;

    Material transparentMaterial;

    private void Awake()
    {
        transparentMaterial = new Material(transparentShader);
        rt = new RenderTexture((int)videoStreamSender.width, (int)videoStreamSender.height, 0);
        tex = new Texture2D(rt.width, rt.height, TextureFormat.RGBA32, false);
        videoStreamSender.sourceTexture = rt;
    }


    private void OnRenderImage(RenderTexture source, RenderTexture destination)
    {
        Graphics.Blit(source, rt, transparentMaterial);
        Graphics.Blit(source, destination);
    }


    private IEnumerator OnPostRender()
    {
        if (rt != null)
        {
            yield return new WaitForEndOfFrame();

            RenderTexture.active = rt;
            tex.ReadPixels(new Rect(0, 0, rt.width, rt.height), 0, 0);
            tex.Apply();
        }
    }


    public void CapturePNG()
    {
        var data = tex.EncodeToPNG();
        File.WriteAllBytes(Application.dataPath + "/../" + "capture.png", data);
    }

}
```

4. Create a shader and attach to the upper script in Main Camera, codes in shader:

```
Shader "Custom/TransparentFlipShader"
{
    Properties
    {
        _MainTex("Texture", 2D) = "white" {}
        _TransparentColorKey("Transparent Color Key", Color) = (0,0,0,1)
    }
    SubShader
    {
        // No culling or depth
        Cull Off ZWrite Off ZTest Always

        Pass
        {
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag

            #include "UnityCG.cginc"

            struct appdata
            {
                float4 vertex : POSITION;
                float2 uv : TEXCOORD0;
            };

            struct v2f
            {
                float2 uv : TEXCOORD0;
                float4 vertex : SV_POSITION;
            };

            float4 _MainTex_TexelSize;

            v2f vert(appdata v)
            {
                v2f o;
                o.vertex = UnityObjectToClipPos(v.vertex);
                o.uv = v.uv;
                return o;
            }

            sampler2D _MainTex;
            float3 _TransparentColorKey;
            float _TransparencyMargin;

            fixed4 frag(v2f i) : SV_Target
            {
                fixed4 col = tex2D(_MainTex, i.uv);
                float deltaR = abs(col.r - _TransparentColorKey.r);
                float deltaG = abs(col.g - _TransparentColorKey.g);
                float deltaB = abs(col.b - _TransparentColorKey.b);

                if (deltaR == 0 && deltaG == 0 && deltaB == 0)
                {
                    return fixed4(0.0f, 0.0f, 0.0f, 0.0f);
                }

                return col;
            }
            ENDCG
        }
    }
}

```
The attachment like this:   
![image](https://github.com/Unity-Technologies/UnityRenderStreaming/assets/33513042/d6205752-699e-40e9-adb1-180a44fe70c7)

5. Change Main Camera Clear Flag to Solid Color and set background color to black, which is consistent with the color _TransparentColorKey in upper shader.  
6.  Run unity.

### Current Behavior

Open web and select Receiver Sample, the background of video is black. If encode target rt to PNG in unity, background is transparent. And I know that only VP8/VP9 support RGBA data format, I tested them but all black.
To test if a video has transparent background, you can play it in browser, press F12 to open developer options, select the video tag and add a custom style in style window, just like this: 
```css
element.style {
    background: red;
}
```
the transparent part in video will be red. 

### Expected Behavior

Video has transparent background if I render it as transparent when using VPX as video encoder.

### Anything else?

Webm support transparent background because it use VPX/OGG as video encoder, which support RGBA format of texutre. If we have a PNG sequence with transparent background, we can compose it into a webm using FFmpeg. Background of the webm is transparent. Using my shader, we have a transparent texture. I have no idea which process drop the alpha channel of RGBA texture, EncodeData in WebRTC.Context.Encode or show video in web UI.

**Comment by karasusan** [comment]
Unity Render Streaming doesn't support the video codec which has an alpha channel. You need to add an alpha mask into each render texture.

**Comment by karasusan** [comment]
memo: WRS-159

**Comment by se7enXF** [comment]
> Unity Render Streaming doesn't support the video codec which has an alpha channel. You need to add an alpha mask into each render texture.

In my code, I already have a RT(render texture) with alpha channel, and I feed it into Video Stream Sender.  I am confused about “add an alpha mask into each render texture”. Do I need to modify the C# code about render texture in  Unity Render Streaming and WebRTC? I already debug all the code in Unity Render Streaming where my code step into until WebRTC. Finding that the format of render texture is ARGB or RGBA, which has alpha channel. I do not know which render texture drop my alpha channel data. 

Please help me find out the right way.

**Comment by karasusan** [comment]
This thread in Unity forum may helps you to understand your issue.
https://forum.unity.com/threads/help-render-streaming-ar.1153802

**Comment by se7enXF** [comment]
> This thread in Unity forum may helps you to understand your issue. https://forum.unity.com/threads/help-render-streaming-ar.1153802

Thanks for reply. I read the thread and get the following conclusions: 

1. WebRTC package uses the NVIDIA Codec v.9.1 which not support alpha encoding for frame buffer.  
2. The solution jwgsbbc proposed could work only encoding and decoding frame both in unity.   

So, I get this:  we can encode frame by jwgsbbc's method but can not decode it in web. It is hard for me to decode custom video data into correct video data in web. Maybe I should start an issue in Unity WebRTC.

**Comment by karasusan** [comment]
@se7enXF
Excuse me, to my understanding, VP8/VP9 don't support alpha channels natively.

FYI, I hope this page is helpful to understand your issue.
https://webrtchacks.com/how-to-make-virtual-backgrounds-transparent-in-webrtc/

**Comment by se7enXF** [comment]
@karasusan  
Sorry I was wrong. I read the [WIKI of WEBM](http://wiki.webmproject.org/alpha-channel), and find that it use the same way as mentioned before in https://forum.unity.com/threads/help-render-streaming-ar.1153802. It is WEBM supports alpha channels but VPX. 

Maybe I should study on how to make video into WEBM format in WebRTC.

**Comment by karasusan** [comment]
@se7enXF
WEBM is a video container format, not a video codec.
WebRTC doesn't have a feature dealing with the video container.

**Comment by se7enXF** [comment]
@karasusan 
Yes, you are right. There is nothing I can do with WebRTC. 
Is it possible to decode video on client web side using decoding method in https://forum.unity.com/threads/help-render-streaming-ar.1153802? I will have a try.

**Comment by karasusan** [comment]
@se7enXF 
Unfortunately, I have no idea to solve your issue on the browser side.

**Comment by se7enXF** [comment]
@karasusan 
That's fine. You help me a lot, thanks.
