### ISSUE TITLE
[BUG]: Input.PreUpdate taking over 500ms when using Unity 2021.3.20f1

### ISSUE THREAD

**Issue by andylewisart** [Unity-Technologies/UnityRenderStreaming#902]
### Package version

3.1.0-exp.6

### Environment

```markdown
* OS: Windows 11
* Unity version: 2021.3.20f1
* Graphics API: DirectX11
* Browser: Chrome
```

### Steps To Reproduce

1. Import Render Streaming package into a fresh HDRP 12.1 project. 
2. Open any scene, even a scene with nothing in it
3. Defocus the Unity Editor and grab a cup of coffee for about 5 minutes
4. Refocus Unity Editor
5. Editor slows to a crawl, with Input.PreUpdate taking over 500ms in the editor profiler. 

### Current Behavior

Profiler shows this after following the steps to reproduce:
![image](https://github.com/Unity-Technologies/UnityRenderStreaming/assets/6510538/86902b5c-b2a4-400a-b7eb-6136522acfe8)

This happens in a blank HDRP project with nothing added to it but the Render Streaming package. When I remove the package, the lag goes away. 

### Expected Behavior

I expect to be able to run the Unity Editor with Render Streaming imported.

**Comment by andylewisart** [comment]
I want to mention that this is fixed when I upgrade to 2021.3.27f1. After upgrading and verifying it was fixed, I tried downgrading back to 2021.3.20f1 and the issue happened again, for whatever that's worth.

**Comment by karasusan** [comment]
@andylewisart
That is interesting..., If the performance issue is fixed by Unity version, it is a chance it is the bug of Input System?

**Comment by karasusan** [comment]
@andylewisart
If you have this issue when using the latest version of Unity Editor, please share me which version you reproduce it.

**Comment by kannan-xiao4** [comment]
@andylewisart I close this issue. If you have any question, please re-open issue. Thanks
