### ISSUE TITLE
[REQUEST]: Example with Furioos Signalling and Furioos Bridge

### ISSUE THREAD

**Issue by emrahtoy** [Unity-Technologies/UnityRenderStreaming#905]
### Is your feature request related to a problem?

It is always a dead end when I try to find documentation related to render streaming and the furious signaling or furioos bridge.

Could anyone share some examples of furioos signalling and furious bridge? How do they distinct and how we could use them?
At least documentation explains what they do. and how they work.

### Describe the solution you'd like

I am trying to create a connection between a webpage that creates a stream for the user's webcam and sends it to the application working on Furioos. I believe Furioos signaling and Furioos bridge are there for such problems. Unfortunately, there is no documentation or an example.

### Describe alternatives you've considered

Alternatively, I can set up a relay server between the Unity application and the web application ( something like vivox ). But this will cause latency, and cost extra effort, and money.

**Comment by emrahtoy** [comment]
@karasusan  [This page](https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/signaling-type.html) is giving a piece of shallow information about signaling ( only for the unity side, it is not giving any information about the web side )

When it comes to the Furioos signaling section, it is referring to [this page](https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/deploy-to-furioos.md) but the page is missing and it seems like has never been there ( I have checked older versions )

**Comment by karasusan** [comment]
@emrahtoy
Hi, sorry for confusing you. Furioos integration isn't available for the latest version of Unity Render Streaming.
We need to fix the document.

**Comment by emrahtoy** [comment]
@karasusan This is not only about the latest version. There is no version that explains how it works. On the other hand, are you telling me that both furioos and render streaming is not able to work together even if they belong to the same company ? If so do you have any suggestions to achieve a scalable provisioning and remote render stream solution?

**Comment by karasusan** [comment]
@emrahtoy
Sorry but render streaming and furioos is not able to work together.
We don't provide scalable solution for render streaming, however, some users make custom solution to make scalable like this.
https://github.com/ossrs/srs-unity

**Comment by emrahtoy** [comment]
@karasusan I am not so sure how to evaluate your answer. Because I am using RenderStreaming and Furioos together already, just not in a collaborative way. I have a signaling server working on my own server for render streaming. And also Furioos have a signaling server for its own usage. RenderStream and Furioos SDK should use the same signaling server in ideal conditions. To achieve this collaborative way, you guys have already developed Furioos Signaling option and the Furioos team already developed Furioos Bridge for render streaming. These tools already exist and this or that way they are capable of working together. There are 2 problems;

1. These tools are not documented at all(!).
2. As there is no documentation also nobody talking about how to use these furioos signaling options and the Furioos bridge on the web.

What would I like to know;

1. How furious signaling works and what are the addresses of its servers?
2. How does Furioos Bridge coming with Furioos SDK work, and what kind of stream it does carry?
3. Why is nobody working on documentation for many versions despite those tools are always there?
4.  Both Furioos and RenderStreaming teams are using WebRTC already. Why are both teams not working together in this context? 

Thank you for suggesting SRS but it is more related to broadcasting. But I need a bidirectional stream solution.

**Comment by karasusan** [comment]
@emrahtoy
Sorry for late reply, you may received the email about Furioos service are shutting down on October.
This is the sad news for us. I am glad if you try other solution instead of Furioos.

**Comment by emrahtoy** [comment]
Unfortunately, I received the email @karasusan 
I wish they could open source the project because their provisioning system was very good to us. Now we have to deal with it by ourselves too. That means one more front to fight with. It is sad to see our investment in furioos become useless. I close the issue with many thanks.
