### ISSUE TITLE
[REQUEST]: How to hide UI on streaming

### ISSUE THREAD

**Issue by Syooian** [Unity-Technologies/UnityRenderStreaming#912]
### Is your feature request related to a problem?

Hi, I'm first working on UnityRenderStreaming, and I want to know is that possible I can see the UI on my PC and but invisible on streaming?
I tried with 2 display and it's OK, but wanna know is that possible to do this with only 1 screen?

thanks.

**Comment by kannan-xiao4** [comment]
@Syooian 
I think it would be better to prepare a camera for the UI and a camera for the stream, and send only the video of the camera for the stream.
Use Camera as the Video Source Type. (Screen is used in the sample)
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/video-streaming.html

**Comment by kannan-xiao4** [comment]
@Syooian Any qestions?

**Comment by Syooian** [comment]
> @Syooian Any qestions?

Thanks for reply, sorry for a long time no response, I'm still trying what you say, and I think I still need some time for this, so just close this is OK. 
Have a good day.
