### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by odcheban1333333333** [Unity-Technologies/UnityRenderStreaming#950]
### Package version

3.1.0-exp.1

### Environment

```markdown
* OS: Windows 11
* Unity version: 2019.4.40f1
* Graphics API: DirectX11
* Browser: Google Chrome Version 116.0.5845.142
```

### Steps To Reproduce

1. git clone https://github.com/Unity-Technologies/UnityRenderStreaming
2. cd WebApp
3. npm install
4. npm run build
5. npm run start
Recorded process on video: https://drive.google.com/drive/folders/1t4wTB7OYhHvy_WKy2Z3qRtmmSmCx0n5h?usp=sharing.

### Current Behavior

The project from Edit/RenderStreaming/DownloadWebApp starts and works correctly.
Project following the [instruction](https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.0/manual/customize_webapp.html) starts incorrectly, broadcasting does not work.

### Expected Behavior

Broadcast is displayed on the site

### Anything else?

Recorded process on video: https://drive.google.com/drive/folders/1t4wTB7OYhHvy_WKy2Z3qRtmmSmCx0n5h?usp=sharing.

**Comment by karasusan** [comment]
@odcheban1333333333 
You need to change Signaling Type option to **WebSocket Signaling** instead of **HTTP signaling**.
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/settings.html

**Comment by odcheban1333333333** [comment]
> @odcheban1333333333 You need to change Signaling Type option to **WebSocket Signaling** instead of **HTTP signaling**. https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/settings.html

Button presses are synchronized and information is transmitted, but no picture is displayed 
Video: https://drive.google.com/file/d/1ikN-tEsf6XvjuM0RVCVO-FGDfSV8Ren-/view?usp=sharing

**Comment by karasusan** [comment]
@odcheban1333333333
Please update the package to the latest version. 3.1.0-exp.1 is old.

**Comment by karasusan** [comment]
@odcheban1333333333
Please update the package to the latest version. 3.1.0-exp.1 is old.

**Comment by odcheban1333333333** [comment]
Thanks for your help, problem solved. 
Updated to the latest version (3.1.0-exp.3)
