### ISSUE TITLE
[BUG]: SignalingManager ignoring command line argument on mac app

### ISSUE THREAD

**Issue by xiazhibin** [Unity-Technologies/UnityRenderStreaming#956]
### Package version

3.1.0-exp.7

### Environment

```markdown
* OS:macOS 12.6 
* Unity version:2021.3.11f1c2
* Graphics API: Vulcan/OpenGL
* Browser:Chrome
```

### Steps To Reproduce

1. follow the step [create-scene](https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.1/manual/create-scene.html)
2. `./test-render-streaming2 -signalingUrl ws://127.0.0.1:8088 -signalingType websocket -logFile a.txt`

### Current Behavior

still run on default setting ws://127.0.0.1

### Anything else?

I have check [#895](https://github.com/Unity-Technologies/UnityRenderStreaming/issues/895)
SignalingManager toggled run on awake and evaluate Commandline Arguments

There is the log

Mono path[0] = '/Users/bin/unity-projs/test-render-streaming2/build/mac/mac.app/Contents/Resources/Data/Managed'
Mono config path = '/Users/bin/unity-projs/test-render-streaming2/build/mac/mac.app/Contents/MonoBleedingEdge/etc'
Found 3 interfaces on host : 0) 192.168.105.11 1) 10.211.55.2 2) 10.37.129.2
Multi-casting "[IP] 192.168.105.11 [Port] 55399 [Flags] 2 [Guid] 2342167858 [EditorId] 2020468764 [Version] 1048832 [Id] OSXPlayer(1,bin-Pro.local) [Debug] 0 [PackageName] OSXPlayer [ProjectName] test-render-streaming2" to [225.0.0.222:54997]...
AS: AutoStreaming module initializing.
New input system (experimental) initialized
Initialize engine version: 2021.3.11f1c2 (2c7757f00bfe)
[Subsystems] Discovering subsystems at path /Users/bin/unity-projs/test-render-streaming2/build/mac/mac.app/Contents/Resources/Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=0
DELL S2722DC preferred device: AMD Radeon Pro 5500M (high power)
Metal devices available: 2
0: AMD Radeon Pro 5500M (high power)
1: Intel(R) UHD Graphics 630 (low power)
Using device AMD Radeon Pro 5500M (high power)
Initializing Metal device caps: AMD Radeon Pro 5500M
Begin MonoManager ReloadAssembly
- Completed reload, in  0.097 seconds
UnloadTime: 1.031472 ms
Signaling: Connecting WS ws://127.0.0.1
 - GetStacktrace(int)
 - DebugStringToFile(DebugStringToFileData const&)
 - DebugLogHandler_CUSTOM_Internal_Log(LogType, LogOption, ScriptingBackendNativeStringPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*)
 -  (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log

**Comment by karasusan** [comment]
Is this enable this flag?
![image](https://github.com/Unity-Technologies/UnityRenderStreaming/assets/1132081/79d51659-b5c6-4ec1-8973-d89f87223e3f)
